Update fx_profiling_tutorial.py (번역)
PyTorchKorea/tutorials-kr pull request #374
Opened 2021-11-09 11:48 UTC by taehui530

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [ ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(357)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
fx_profiling_tutorial.py을 번역하였습니다.

2021-11-19 13:44 UTC, hyoyoung requested changes
1. 라이센스 동의에 체크해주세요

2. 클래스 이름 자체는 번역하지 않습니다

3. 강조의 의미가 아니면 주어는 생략합니다

2021-11-22 14:04 UTC, hyoyoung requested changes
전반적으로 읽기 어려운 문장이 보입니다.
주어가 그대로 표시된 부분도 여러 부분 남아있습니다
다시 확인부탁드립니다

2021-11-22 14:04 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +**번역:** `김태희 <https://github.com/taehui530>`_
저자와 번역의 : 위치가 다릅니다

2021-11-22 14:04 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# ``Interpreter`` 를 계승함으로써, 다양한 기능을 재정의하고 원하는 프로파일링 동작을 설치할 수 있습니다.
위에서 inherit을 상속으로 번역했는데, 여기서는 계승이라고 되어있네요

2021-11-22 14:04 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +#``Profiling Interpreter`` 클래스를  정의해봅시다.:
클래스 이름에는 띄어쓰기가 없습니다. 똑같이 맞춰주세요

2021-11-23 02:15 UTC, taehui530 commented on intermediate_source/fx_profiling_tutorial.py
> +# 즉, 다음 호출을 위해 모델의 어떤 부분이 가장 오래 걸릴까요?
넵 저도 조금 고민되던 문장이었는데 수정해보겠습니다! 확인부탁드립니다!

2021-11-23 02:16 UTC, taehui530 commented on intermediate_source/fx_profiling_tutorial.py
> +**번역:** `김태희 <https://github.com/taehui530>`_
넵 수정했습니다!

2021-11-23 02:16 UTC, taehui530 commented on intermediate_source/fx_profiling_tutorial.py
> +# ``Interpreter`` 를 계승함으로써, 다양한 기능을 재정의하고 원하는 프로파일링 동작을 설치할 수 있습니다.
넵 수정했습니다 감사합니다!

2021-11-23 02:17 UTC, taehui530 commented on intermediate_source/fx_profiling_tutorial.py
> +#``Profiling Interpreter`` 클래스를  정의해봅시다.:
넵 수정했습니다 감사합니다!

2021-11-23 14:51 UTC, hyoyoung requested changes
> 강조의 의미가 아니면 주어는 생략합니다

요거 코멘트로 적고 있는데, 아래에는 안고쳐진게 많이 눈에 띕니다
제 생각엔 해당 주어들(우리, 당신 등) 다 생략가능할것으로 보입니다.
수정후에 다시 요청부탁드리겠습니다

2021-12-09 08:25 UTC, hyoyoung commented
2주 이상 피드백이 없어서 닫습니다 필요하면 다시 열어주시기 바랍니다

2021-12-09 08:25 UTC, closed without merging