intermediate/tensorboard_profiler_tutorial 번역
PyTorchKorea/tutorials-kr pull request #376
Opened 2021-11-11 04:31 UTC by woojinsong

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #348 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
tensorboard_profiler_tutorial 튜토리얼에 대한 번역

2021-11-17 06:48 UTC, Taeyoung96 reviewed
번역하시느라 고생많으셨습니다. 전체적으로 종결어미의 통일성을 가져야할 것 같다고 생각이 들었습니다. comment를 단 부분 외에도 종결어미를 다른 글들과 비슷하게 가져야 할 것 같습니다 😄

2021-11-17 06:48 UTC, Taeyoung96 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +GPU측에서 실행되는 CUDA 커널 기록을 수행할 수 있는 업데이트된 프로파일러 API를 포함하고 있다.
포함하고 있다. >> 포함하고 있습니다.  
로 바꾸는 것이 좋을 것 같습니다.

2021-11-17 06:48 UTC, Taeyoung96 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +#   TensorBoard에서 프로파일을 분석하기 위해 이 디렉토리를 ``logdir`` 매개변수로 지정한다.
이 문장 위로 모두 종결어미를 '~입니다.'로 바꾸는 것이 좋을 것 같습니다.  
다른 번역 글들도 그렇게 통일성을 가져왔기 때문입니다!

2021-11-18 13:40 UTC, hyoyoung requested changes

2021-11-18 13:40 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +텐서보드를 사용한 파이토치 프로파일러
다른 문서를 보면 아시겠지만 보통은

**저자**: `원저자 <https://github.com/원저자>`_
**번역**: `번역자 <https://github.com/번역자>`_

형태로 제목 밑에 표기하여 둡니다

2021-11-18 13:40 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +이 튜토리얼은 모델의 병목 현상을 감시하기위해 텐서보드 플러그인을 파이토치 프로파일 어떻게 사용하는지
감시하기위해 -> 감시하기 위해
프로파일 -> 프로파일러를

2021-11-18 13:40 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 그후 입력데이터를 준비한다. 이 튜토리얼에서는 CIFAR10 데이터셋을 사용한다.
그후 -> 그 후

2021-11-18 13:40 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 프로파일러는 컨텍스트 매니저를 통해 활성화 되고 가장 유용한 여러 파라미터를을 수용한다:
보통은 파라미터는 매개변수로 번역합니다

참조 : https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2021-12-03 15:06 UTC, woojinsong commented on intermediate_source/tensorboard_profiler_tutorial.py
> +텐서보드를 사용한 파이토치 프로파일러
원저자명 나와있지않아 번역자만 추가해서 수정했습니다 감사합니다

2021-12-03 15:06 UTC, woojinsong commented on intermediate_source/tensorboard_profiler_tutorial.py
> +GPU측에서 실행되는 CUDA 커널 기록을 수행할 수 있는 업데이트된 프로파일러 API를 포함하고 있다.
수정하였습니다!

2021-12-03 15:07 UTC, woojinsong commented on intermediate_source/tensorboard_profiler_tutorial.py
> +#   TensorBoard에서 프로파일을 분석하기 위해 이 디렉토리를 ``logdir`` 매개변수로 지정한다.
전체적으로 종결어미 통일하도록 수정하였습니다 감사합니다

2021-12-03 15:08 UTC, woojinsong commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 프로파일러는 컨텍스트 매니저를 통해 활성화 되고 가장 유용한 여러 파라미터를을 수용한다:
수정하였습니다 감사합니다

2021-12-09 08:33 UTC, hyoyoung requested changes

2021-12-09 08:33 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +번역: 번역자 <https://github.com/woojinsong>_
원 저자 명이 없을경우 해당 번역 라인을 삭제하시거나
번역자 말고 본인의 성함을 넣어주시기 바랍니다

2021-12-09 08:33 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +이 튜토리얼은 모델의 병목 현상을 감시하기위해 텐서보드 플러그인을 파이토치 프로파일 어떻게 사용하는지
문장이 어색합니다

텐서보드 플러그인과 파이토치 프로파일러를 사용하여 어떻게 모델 병목 현상을 찾는지 보여주는 튜토리얼입니다

이정도가 괜찮지 않을까요?

2021-12-09 08:33 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 원하는 포맷으로 데이터를 변환하고 데이터로더를 사용하여 각각 배치크기로 로드합니다.
로드합니다 -> 읽어들입니다

로 바꾸면 어떨까요?

2021-12-09 08:33 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 측정기준의 세부사항은  `여기 <https://github.com/guyang3532/kineto/blob/readme/tb_plugin/docs/gpu_utilization.md>`_.
문장 종결이 빠진거 같습니다

세부사항은 ... 입니다 정도가 있어야할거 같습니다

2021-12-09 08:33 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 5. 프로파일러의 도움으로 성능을 증진시킨다.
증진보다는 향상이 더 어울릴듯합니다

2021-12-09 08:33 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 이 예에서는 "Performance Recommendation"에 따라 "num_workers"를 다음과 같이 설정하고,
위에서는 Performance Recommendation을 성능 권장 사항 으로 번역하셨습니다
통일감있게 번역하던지, 고유명사 그대로 번역 안하던지 해야할듯합니다

2021-12-09 09:44 UTC, 9bow commented on intermediate_source/tensorboard_profiler_tutorial.py
> +번역: 번역자 <https://github.com/woojinsong>_
삭제하지 않으실 경우, 이름으로 변경하시고 링크를 위해 다른 문서를 ` 을 추가해주시기 바랍니다.
reStructuredText 문법은 [이 문서](https://docutils.sourceforge.io/docs/user/rst/cheatsheet.html)를 참고해주세요.

2021-12-17 14:05 UTC, des00 commented
@woojinsong
혹시 리뷰 확인하시고 수정 가능하신지요?
피드백이 없으면 close 처리하고자 합니다.

2021-12-25 17:20 UTC, hyoyoung commented
2주 이상 피드백이 없어서 닫습니다 필요하면 다시 열어주시기 바랍니다

2021-12-25 17:20 UTC, closed without merging