advanced/rpc_ddp_tutorial 번역
PyTorchKorea/tutorials-kr pull request #382
Opened 2021-11-15 09:45 UTC by dajeongPark-dev

Translate rpc_ddp_tutorial.rst and main.py

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #361 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

advanced/rpc_ddp_tutorial을 번역했고 rpc_ddp_tutorial.rst 파일과 rpc_ddp_tutorial파일 안에 있는 main.py를 수정했습니다.
번역 작업을 마친 후 'make html -noplot'을 통해 결과물을 확인하려고 했으나
어려움이 생겨서 그 부분까지 확인을 잘 하지 못했습니다. 하지만 최대한 reStructureText 규칙에 맞춰 수정하려고 노력했습니다.
부족한 부분이 있다면 피드백 부탁드립니다.

2021-11-22 05:27 UTC, puhuk reviewed
리뷰 남깁니다.

2021-11-22 05:27 UTC, puhuk commented on advanced_source/rpc_ddp_tutorial.rst
> +2) 모델의 정방 전달(forward pass)을 실행하고 해당 출력을 검색(retrieve)합니다.
```아래 제안드립니다. (정방 -> 전방)
2) 모델의 전방 전달(forward pass)을 실행하고 해당 출력을 검색(retrieve)합니다.
```

2021-11-22 12:32 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +2) 모델의 정방 전달(forward pass)을 실행하고 해당 출력을 검색(retrieve)합니다.
리뷰 감사합니다. 전방으로 수정하겠습니다.

2021-11-30 13:59 UTC, hyoyoung requested changes
전체적으로 backward는 역방향으로 바꿔주세요

2021-11-30 13:59 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +**Authors**: `Pritam Damania <https://github.com/pritamdamania87>`__ and `Yi Wang <https://github.com/SciPioneer>`__
authors는 보통 저자로 번역합니다

2021-11-30 13:59 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +   트레이너는 또한 전방 전달(forward pass), 후방 전달(backward pass) 및 옵티마이저 단계를 실행해야 합니다.
forward는 보통 순방향
backward는 역방향으로 번역하고 있습니다

2021-11-30 13:59 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +   트레이너는 또한 전방 전달(forward pass), 후방 전달(backward pass) 및 옵티마이저 단계를 실행해야 합니다.
옵티마이저는 최적화 단계로 바꿔도 괜찮을듯합니다

2021-11-30 13:59 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +1) 마스터는 매개변수 서버에 임베딩 테이블을 홀딩(holding)하고 있는
여기서 holds는 가지고 있다 이거나 담고 있다로 바꿔도 괜찮을듯합니다

2021-11-30 13:59 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +   임베딩 룩업을 수행한 다음 DDP 내부에 래핑된 FC 레이어를 실행하는 ``HybridModel``을 생성합니다.
룩업은 찾아본다는 의미로 바꿔도 괜찮을듯합니다

2021-11-30 13:59 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +여러 에포크(ephoc)와 각 배치(batch)에 대해 트레이닝 루프를 실행합니다:
epoch의 오타

2021-12-02 05:43 UTC, Taeyoung96 reviewed
고생하셨습니다. 몇 가지 리뷰를 남깁니다. :)

2021-12-02 05:43 UTC, Taeyoung96 commented on advanced_source/rpc_ddp_tutorial.rst
> +5) 후방 전달(backward pass)의 일부로 FC 레이어의 그라디언트(gradient)가 먼저 계산되고 DDP의 allreduce를 통해 모든 트레이너와 동기화됩니다.
여기 나오는 backward도 수정이 필요해 보입니다.

2021-12-02 05:43 UTC, Taeyoung96 commented on advanced_source/rpc_ddp_tutorial/main.py
> +    # 100개의 에폭크(ephoc)에 대해 학습합니다.
에포크 오타 수정이 필요합니다  
[용어 사용 규칙](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md)에 따르면 `에폭`이 약속된 규칙으로 보입니다.

2021-12-06 04:37 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +**Authors**: `Pritam Damania <https://github.com/pritamdamania87>`__ and `Yi Wang <https://github.com/SciPioneer>`__
감사합니다! 참고하겠습니다.

2021-12-06 04:50 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +   트레이너는 또한 전방 전달(forward pass), 후방 전달(backward pass) 및 옵티마이저 단계를 실행해야 합니다.
감사합니다! 수정했습니다.

2021-12-06 04:50 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +1) 마스터는 매개변수 서버에 임베딩 테이블을 홀딩(holding)하고 있는
감사합니다! 수정했습니다.

2021-12-06 04:52 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +   트레이너는 또한 전방 전달(forward pass), 후방 전달(backward pass) 및 옵티마이저 단계를 실행해야 합니다.
감사합니다! 수정했습니다.

2021-12-06 04:54 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +여러 에포크(ephoc)와 각 배치(batch)에 대해 트레이닝 루프를 실행합니다:
감사합니다! 수정했습니다.

2021-12-06 04:54 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +5) 후방 전달(backward pass)의 일부로 FC 레이어의 그라디언트(gradient)가 먼저 계산되고 DDP의 allreduce를 통해 모든 트레이너와 동기화됩니다.
감사합니다! 수정했습니다.

2021-12-06 04:54 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +    # 100개의 에폭크(ephoc)에 대해 학습합니다.
감사합니다! 수정했습니다.

2021-12-06 05:44 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +   임베딩 룩업을 수행한 다음 DDP 내부에 래핑된 FC 레이어를 실행하는 ``HybridModel``을 생성합니다.
'임베딩 룩업'이라고 주로 표현 되는 거 같아 그대로 작성해보았었는데 피드백해주신 내용을 토대로 임베딩 색인 작업(embedding lookup)이라고 수정해보았습니다! 감사합니다.

2021-12-07 13:31 UTC, hyoyoung requested changes

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +   매개변수 서버에서 임베딩 색인 작업(embedding lookup)을 수행하는 데 사용할 수 있습니다.
embedding lookup을 임베딩 색인 작업으로 번역하셨는데, 의미차이가 있습니다.
색인 작업(indexing)은 문서에서 필요한 단어 자체를 추출하는 작업이고
찾아보기(lookup)은 단어를 찾은뒤에 문서를 찾아보는 작업으로 사용하고 있습니다.
물론 색인 자체도 찾아보다는 뜻이 있기는한데, lookup은 임베딩 찾기정도가 더 적절하지 않을까요?

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +   여러 worker에 걸쳐 모델의 단계를 파이프라인할 수 있고
pipeline 번역이 까다로운 편인데, 파이프라인(pipeline)으로 병기하는것도 방법일것 같습니다

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +   또한 마스터는 두 트레이너의 트레이닝 루프를 구동합니다.
트레이닝 자체는 학습으로도 해도 좋을듯합니다
여기서 drive는 수행한다에 더 가까울듯합니다

두 트레이너의 학습 루프를 수행합니다.

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +6) 다음으로, Distributed Autograd는 매개변수 서버로 그라디언트를 전파합니다. 여기서 임베딩 테이블의 그라디언트가 업데이트됩니다.
그라디언트는 변화도로 사용하기로 용어집에서 정의해두었습니다

https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial.rst
> +래핑하여 모든 트레이너에서 이 레이어를 복제하고 동기화합니다.
래핑은 감싸다로도 바꿀수 있을듯합니다

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +    전역에서 nn.Linear를 실행하는 전방 전달(forward pass)를 실행합니다.
전방 -> 순방향

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +    후방 전달(backward pass) 동안에 DDP는 조밀한 부분(nn.Linear)에 대한 그래디언트(gradient) 집계를 담당하고
후방 -> 역방향
그래디언트 -> 변화도

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +    # 100개의 에폭크(ephoc)에 대해 학습합니다.
에폭크 오타가 수정이 안되었습니다

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +        # Distributed autograd context를 생성합니다.
아래에서는 Distributed를 분산으로 번역되어있습니다

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +                # 분산 후방 전달(distributed backward pass)을 실행합니다.
후방 -> 역방향

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +                # Distributed optimizer를 실행시킵니다.
여기도 Distributed

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +                # 반복할 때마다 다른 그래디언트를 호스팅하는 하나의 다른 distributed autograd context를 생성하므로
여기 그래디언트도 수정 필요

2021-12-07 13:31 UTC, hyoyoung commented on advanced_source/rpc_ddp_tutorial/main.py
> +    # Rank 2 는  master를 의미하고, 3은 is 매개변수 서버, 그리고 0과 1은 트레이너를 뜻한다.
어투가 위에서는 ~입니다 인데
여기서는 뜻한다 이므로 통일성있게 맞춰야합니다

2021-12-17 14:06 UTC, des00 commented
@dajeongPark-dev 
혹시 리뷰 확인하시고 수정 가능하신지요?
피드백이 없으면 close 처리하고자 합니다.

2021-12-17 14:53 UTC, dajeongPark-dev commented
> @dajeongPark-dev 혹시 리뷰 확인하시고 수정 가능하신지요? 피드백이 없으면 close 처리하고자 합니다.

늦은 피드백 죄송합니다... 빠르게 수정하도록 하겠습니다!

2021-12-17 15:22 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +   매개변수 서버에서 임베딩 색인 작업(embedding lookup)을 수행하는 데 사용할 수 있습니다.
피드백 감사합니다! 임베딩 찾기 작업으로 수정하였습니다! 늦게 답장 드려 죄송합니다.

2021-12-17 15:23 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +   여러 worker에 걸쳐 모델의 단계를 파이프라인할 수 있고
파이프라인(pipeline)으로 수정했습니다! 감사합니다.

2021-12-17 15:24 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +   또한 마스터는 두 트레이너의 트레이닝 루프를 구동합니다.
트레이닝 단어들을 모두 찾아 학습으로 변경해놓았습니다! 그리고 번역본 기준으로 37번째줄에 drive를 구동하다라고 해석했었는데 수행한다로 변경했습니다. 감사합니다.

2021-12-17 15:26 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +6) 다음으로, Distributed Autograd는 매개변수 서버로 그라디언트를 전파합니다. 여기서 임베딩 테이블의 그라디언트가 업데이트됩니다.
수정했습니다! 감사합니다.

2021-12-17 15:26 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial.rst
> +래핑하여 모든 트레이너에서 이 레이어를 복제하고 동기화합니다.
수정했습니다. 감사합니다.

2021-12-17 15:27 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +    전역에서 nn.Linear를 실행하는 전방 전달(forward pass)를 실행합니다.
main.py 리뷰 감사합니다. 수정했습니다!

2021-12-17 15:29 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +    후방 전달(backward pass) 동안에 DDP는 조밀한 부분(nn.Linear)에 대한 그래디언트(gradient) 집계를 담당하고
수정했습니다! 감사합니다.

2021-12-17 15:33 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +                # 분산 후방 전달(distributed backward pass)을 실행합니다.
수정했습니다! 감사합니다.

2021-12-17 15:34 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +                # 반복할 때마다 다른 그래디언트를 호스팅하는 하나의 다른 distributed autograd context를 생성하므로
수정했습니다! 감사합니다.

2021-12-18 15:57 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +    # Rank 2 는  master를 의미하고, 3은 is 매개변수 서버, 그리고 0과 1은 트레이너를 뜻한다.
수정했습니다. 감사합니다.

2021-12-18 15:58 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +                # Distributed optimizer를 실행시킵니다.
수정했습니다. 감사합니다.

2021-12-18 15:58 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +        # Distributed autograd context를 생성합니다.
수정했습니다. 감사합니다!

2021-12-18 15:59 UTC, dajeongPark-dev commented on advanced_source/rpc_ddp_tutorial/main.py
> +    # 100개의 에폭크(ephoc)에 대해 학습합니다.
수정했습니다~ 감사합니다.

2021-12-18 16:20 UTC, des00 commented
@dajeongPark-dev 
밤늦은 시간까지 업데이트하시느라 고생이 많으시군요.
같은 수업을 들으시는 몇몇 분들의 불성실함과 비교되는 훌륭한 작업물입니다.
번역하신 부분 리뷰하며 저도 많이 배우고 있습니다.

혹시 수정이 완료되었으면 기존에 리뷰하셨던 분들에게
`@user_id`로 호출하여 수정한 부분 재리뷰를 청해보시는 것은 어떨런지요.
지속적으로 피드백을 주고 받는 만큼 얻어가시는 것이 많으리라 확신합니다.

2021-12-18 16:37 UTC, dajeongPark-dev commented
> @des00
번역 작업이 처음이라 쉽지는 않았지만 많은 분들께서 리뷰도 해주시고 원활한 작업 진행을 위해 옆에서 힘써주심에 많은 것을 배워가는 시간이었습니다. 응원과 격려에 감사드립니다!
현재 리뷰해 주신 부분들을 다 수정한 상태이고 마지막으로 한 번 더 검토 중이었습니다! 여러 번 봐도 놓치는 부분이 있을 때도 있어서요 :)

오늘 안으로 마지막 검토를 마치고 알려주신 방법으로 재리뷰 부탁드리도록 하겠습니다! 감사합니다.

2021-12-20 02:54 UTC, dajeongPark-dev commented
@puhuk
안녕하세요! 이번에 rpc_ddp_tutorial 번역을 거의 다 완료하여 재리뷰를 부탁드리게 되었습니다.
저번에 피드백 주신 backward pass는 역방향 전달로 수정하게 되었습니다.

감사합니다!

2021-12-20 02:56 UTC, dajeongPark-dev commented
@Taeyoung96
안녕하세요! 이번에 rpc_ddp_tutorial 번역을 거의 다 완료하여 재리뷰를 부탁드리게 되었습니다.
저번에 주신 피드백을 참고하여 전반적으로 수정했습니다 :)

감사합니다!

2021-12-20 03:03 UTC, dajeongPark-dev commented
@hyoyoung 
안녕하세요! 이번에 rpc_ddp_tutorial 번역을 거의 다 완료하여 재리뷰를 부탁드리게 되었습니다.
저번에 주신 피드백을 참고하여 전반적으로 수정했습니다 :)

그리고 초반에 optimizer를 최적화로 번역하면 어떨지 조언을 해주셨는데 그 부분에 대해서는 최적화가 어울릴 것라고 판단이 되어 그렇게 수정을 했지만 이후에 나오는 부분에서는 번역 용어집을 참고해보았을 때도 음차 표기 방식을 이용한다고 되어 있어 옵티마이저로 변경해 놓았습니다!

감사합니다!

2021-12-20 07:01 UTC, puhuk commented
@dajeongPark-dev 
고생하셨습니다!

2021-12-20 11:28 UTC, Taeyoung96 commented
@dajeongPark-dev   
확인했습니다! 고생하셨습니다 :)

2022-01-09 12:27 UTC, 9bow approved these changes
@puhuk @Taeyoung96 @hyoyoung 
다시 리뷰 요청드립니다. 특이 사항이 없으시면 차주 중 반영하려고 합니다.

2022-01-10 01:35 UTC, puhuk commented
LGTM 👍

2022-01-10 07:27 UTC, Taeyoung96 reviewed
LGTM! :+1:

2022-01-10 10:42 UTC, merged