beginner/hyperparameter_tuning_tutorial 번역
PyTorchKorea/tutorials-kr pull request #384
Opened 2021-11-22 06:48 UTC by Junepp

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [ ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2021-11-23 14:54 UTC, hyoyoung requested changes
라이센스 항목은 필수로 체크해야하며,
PR 종류도 체크해주셔야합니다

2021-11-25 14:44 UTC, puhuk reviewed
몇가지 리뷰 남깁니다.
`wrap in function` 은 `함수에 포장하다` 말고 좋은 번역이 있을 것 같은데 생각이 안나네요..
다른 리뷰어분들도 고민해주시면 좋을 것 같습니다.

2021-11-25 14:44 UTC, puhuk commented on beginner_source/hyperparameter_tuning_tutorial.py
> +보시다시피, 몇가지 수정만 추가하면 됩니다.
`수정`-> `수정사항` 으로 수정하는게 읽기 편할 것 같습니다.

2021-11-25 14:44 UTC, puhuk commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 이 방법을 통해 서로다른 시도(trials)간 데이터 디렉토리(directory)를 공유할 수 있습니다.
서로다른 -> 서로 다른
으로 제안드립니다.

2021-11-25 14:44 UTC, puhuk commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 짐작과 같이 ``config`` 파라미터는 훈련하고자 하는 하이퍼파라미터들을 전달받게됩니다.
`짐작과 같이` 는 문맥이 조금 어색한 것 같습니다.
`짐작한 것 처럼` 으로 제안드립니다.

2021-11-25 15:32 UTC, Taeyoung96 reviewed
고생하셨습니다! 몇 가지 comment를 남겼습니다 :smile:

2021-11-25 15:32 UTC, Taeyoung96 commented on beginner_source/hyperparameter_tuning_tutorial.py
>  ---------------
reST 문법상 `-----`를 바로 윗줄인 34Line보다 길게 해줘야 합니다.

2021-11-25 15:32 UTC, Taeyoung96 commented on beginner_source/hyperparameter_tuning_tutorial.py
> +imports를 시작으로 진행합니다:
의역으로 `패키지를 가져오는 것을 시작으로 진행합니다.` 는 어떨까요?

2021-11-25 15:32 UTC, Taeyoung96 commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 완전연결계층(fully connected layers)에서 계층(layer)의 크기가 해당됩니다.
띄어쓰기가 이루어져야 할 것 같습니다.  
완전연결계층 >> 완전 연결 계층

2021-11-26 13:37 UTC, Junepp commented on beginner_source/hyperparameter_tuning_tutorial.py
> +보시다시피, 몇가지 수정만 추가하면 됩니다.
반영했습니다!

2021-11-26 13:39 UTC, Junepp commented on beginner_source/hyperparameter_tuning_tutorial.py
>  ---------------
감사합니다. 주신 의견들 모두 반영했습니다!

2021-12-01 13:24 UTC, lewha0 commented
앞부분 살펴보며 의견 몇 가지를 남겨 보았습니다. 참고 부탁드립니다.

2021-12-17 14:07 UTC, des00 commented
@Junepp 
혹시 리뷰 확인하시고 수정 가능하신지요?
피드백이 없으면 close 처리하고자 합니다.

2021-12-25 17:20 UTC, hyoyoung commented
2주 이상 피드백이 없어서 닫습니다 필요하면 다시 열어주시기 바랍니다

2021-12-25 17:20 UTC, closed without merging