advanced/torch-script-parallelism.rst 번역
PyTorchKorea/tutorials-kr pull request #386
Opened 2021-11-25 15:41 UTC by Taeyoung96

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #381 
- #189 
- #194

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

#194 에서 나온 comment들을 모두 update하고 좀 더 자연스럽게 의역을 해보았습니다.

2021-11-29 08:05 UTC, puhuk reviewed
고생하셨습니다.
리뷰 몇개 남깁니다:)

2021-11-30 13:36 UTC, lewha0 commented
외래어 표기법에 따라 method를 메소드가 아니라 메서드로 번역하면 어떨까 싶은데요, 저장소를 검색해 보니 현재는 혼용되고 있는 듯 합니다. 용어 통일에 대해 한 번 고민해보면 어떨지 제안드립니다. (여기에 남기는 게 좀 어색하지만..)

2021-11-30 13:43 UTC, hyoyoung commented
method는 TTA규정에서는 메소드, 외래어 표기법에서는 메서드로 되어있습니다
TTA규정을 기여자들이 친숙해해서 메소드로 우선 정해둔 상태인데,
나중에 개선할때 다시 투표를 해보고 정리를 할 수도 있습니다
https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2021-11-30 13:46 UTC, lewha0 commented
아.. 제가 미처 규칙 확인을 못 했습니다. 댓글 달고 찾아보고 있었는데 어디에 있는지 헷갈렸네요. 확인 감사합니다!

2021-11-30 13:48 UTC, hyoyoung requested changes

2021-11-30 13:48 UTC, hyoyoung commented on advanced_source/torch-script-parallelism.rst
> +        # 병렬로 `foo` 를 호출합니다:
여기서 parallelism은 아래 문단의 normally는 비교되는 단어 선택인듯 합니다
아래에서는 일반적으로 호출한다고 되어있으니
여기서는 병렬적으로 호출한다고 변경하는게 어떨까요?

2021-11-30 13:48 UTC, hyoyoung commented on advanced_source/torch-script-parallelism.rst
> +이러한 구조는 함수 내에서 명령문 실행을 오버랩하거나
오버랩은 중첩으로 바꿔도 좋을듯합니다

2021-11-30 13:48 UTC, hyoyoung commented on advanced_source/torch-script-parallelism.rst
> +당신은 이 코드에 더 많은 병렬화 기회가 있다는 것을 눈치챘을지도 모릅니다:
주어는 빠져도 좋을듯합니다

2021-11-30 13:48 UTC, hyoyoung commented on advanced_source/torch-script-parallelism.rst
> +또는, 만약 당신이 간결함을 중요하게 생각한다면 리스트 컴프리헨션(list comprehension)을 사용할 수 있습니다.
주어 생략

2021-11-30 13:48 UTC, hyoyoung commented on advanced_source/torch-script-parallelism.rst
> +인트로에서 설명했듯이, 우리는 루프를 사용해 앙상블의 각 모델들에 대한 작업을 나눴습니다.
인트로는 서두에서로 변경해도 좋을듯합니다

2021-12-02 05:37 UTC, Taeyoung96 commented
Comment 주신 부분들을 모두 반영했습니다.  
감사합니다! :smile:

2021-12-04 15:43 UTC, hyoyoung approved these changes
looks good to me

2021-12-04 15:43 UTC, merged