Update audio_io_tutorial.py
PyTorchKorea/tutorials-kr pull request #406
Opened 2021-12-03 21:07 UTC by kimgooq

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #388 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
해당 파일 번역 및 마크다운 문법 수정 완료

2021-12-04 13:48 UTC, puhuk reviewed
몇가지 리뷰 추가합니다.

2021-12-04 13:48 UTC, puhuk commented on beginner_source/audio_io_tutorial.py
> +# path-like object 또는 file-like object를 제공할 수 있습니다.
파일의 경로 또는 파일을 제공할 수 있습니다. 로 제안드립니다.

2021-12-04 13:48 UTC, puhuk commented on beginner_source/audio_io_tutorial.py
> +# -  ``sample_rate`` 는 오디오의 샘플링 속도입니다
샘플링 비율로 제안드립니다.

2021-12-04 13:48 UTC, puhuk commented on beginner_source/audio_io_tutorial.py
> +# 값 범위는 ``[-1.0, 1.0]`` 내에서 정규화됩니다.
위에 문장과 중복됩니다. 삭제해도 괜찮을 것 같습니다.

2021-12-04 15:06 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# path-like object 또는 file-like object를 제공할 수 있습니다.
좋은 리뷰 감사드립니다. 수정했습니다.

2021-12-04 15:08 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# -  ``sample_rate`` 는 오디오의 샘플링 속도입니다
확인하고 수정했습니다, 감사드립니다.

2021-12-04 15:09 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# 값 범위는 ``[-1.0, 1.0]`` 내에서 정규화됩니다.
놓친 부분이 있었네요.. 감사드립니다.

2021-12-07 13:40 UTC, hyoyoung requested changes

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# 오디오 메타데이터 쿼리
quering은 질의하기로 바꿔쓸수 있습니다

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# 파일의 경로 또는 파일을 제공할 수 있습니다.
함수는 ... 가져옵니다의 문장과 파일의 ... 있습니다. 앞뒤 문장이 이어지지 않습니다
파일의 경로 앞에 이때를 넣어보는건 어떨까요?

이때 파일의 경로 또는 파일을 제공할 수 있습니다.

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# -  ``"UNKNOWN"`` 위에 없는것
위에서 정의되지 않는것 정도로 바꾸는게 더 좋아보입니다

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# ``info`` 는 파일류 객체에서 작동합니다.
file-like는 파일류 보다
파일 같은 객체에서 가 더 자연스럽지 않을까요?

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +print("Source:" , SAMPLE_WAV_URL)
원본 소스 코드의 indent는 바꾸지 말아주세요

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# **참고** 파일류 객체를 전달할 때, ``info`` 는 모든 기본 데이터를 읽지 않습니다.
underlying data는 기본 데이터보다는 기저의 모든 데이터 정도가 더 충실한 의미를 제공할 수 있을듯합니다

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# Tensor에 오디오 데이터 로드
로드는 읽어들이기로도 바꿀수 있습니다

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# 이 함수는 경로류 객체 또는 파일류 객체를 입력으로 받습니다.
경로류 객체보다는 경로 같은 객체

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# 슬라이싱 팁
슬라이싱은 자르기로도 바꿀수 있습니다

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +print("파형의 결과 확인 중... ", end="")
파형의 결과가 아니라 결과 파형 확인 중이 더 자연스럽지 않을까요?

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# 이 함수는 path-like object 또는 file-like object를 받습니다.
위에서는 path-like, file-like를 해석했는데 여기서는 영문으로 두었습니다

2021-12-07 13:40 UTC, hyoyoung commented on beginner_source/audio_resampling_tutorial.py
>  """
이 파일 자체는 indent만 변화했으므로 pr에서 제거하여주세요

2021-12-07 15:02 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# 오디오 메타데이터 쿼리
해당 사당 확인 후 수정했습니다. 감사합니다.

2021-12-07 15:02 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# 파일의 경로 또는 파일을 제공할 수 있습니다.
자연스러운 문장 감사합니다. 수정했습니다.

2021-12-07 15:03 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# -  ``"UNKNOWN"`` 위에 없는것
위에서 정의되지 않은 것 으로 수정했습니다.

2021-12-07 15:03 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# ``info`` 는 파일류 객체에서 작동합니다.
확인 후 해당 워딩에 --같은 으로 통일하였습니다. 감사합니다.

2021-12-07 15:03 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +print("Source:" , SAMPLE_WAV_URL)
해당 사당 확인 후 수정했습니다. 감사합니다.

2021-12-07 15:04 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# **참고** 파일류 객체를 전달할 때, ``info`` 는 모든 기본 데이터를 읽지 않습니다.
좋은 번역 및 리뷰 감사드립니다. 수정했습니다.

2021-12-07 15:04 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# Tensor에 오디오 데이터 로드
확인 후 해당 load 관련하여 용어 통일했습니다.

2021-12-07 15:05 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# 슬라이싱 팁
자르기 로 수정했습니다. 감사합니다.

2021-12-07 15:05 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +print("파형의 결과 확인 중... ", end="")
조금 더 와닿는 워딩인 것 같습니다. 수정했습니다.

2021-12-07 15:06 UTC, kimgooq commented on beginner_source/audio_io_tutorial.py
> +# 이 함수는 path-like object 또는 file-like object를 받습니다.
위에서 해당 내용 확인 후 전체 내용에서 통일시켜 주었습니다.

2021-12-07 15:06 UTC, kimgooq commented on beginner_source/audio_resampling_tutorial.py
>  """
확인 후 수정했습니다. 감사합니다.

2021-12-09 08:21 UTC, hyoyoung requested changes

2021-12-09 08:21 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# Google Colab에서 이 튜토리얼을 실행할 때 다음을 사용하여
> 다음을 사용하여 필수 패키지를 설치하십시오.

이 문장보다

아래와 같이 필수패키지를 설치하십시오. 가 조금 더 읽기 편할듯 합니다

2021-12-09 08:21 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +#@markdown 이 튜토리얼에서는 Creative Commos BY 4.0에 따라 라이선스가 부여된 [VOiCES dataset](https://iqtlabs.github.io/voices/)의 음성 데이터를 사용합니다.
라이선스가 부여된이라는 표현보다

라이선스를 따르는 표현이 더 무난해보입니다

2021-12-09 08:21 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# 파일같은 객체 질의하기
띄어쓰기를 통일해주세요
아래에서는 파일 같은 객체라고 번역했는데, 이 문장에서는 파일같은 객체로 되어 있습니다

2021-12-09 08:21 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# file-like object를 전달할 때 함수가 어떤 형식을 사용해야 하는지 알 수 있도록 인수 ``format`` 도 제공해야 합니다.
file-like 번역 필요

2021-12-09 08:21 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# path-like object의 경우 함수는 확장자에서 형식을 유추합니다.
path-like 번역 필요

2021-12-09 08:21 UTC, hyoyoung commented on beginner_source/audio_io_tutorial.py
> +# file-like object에 저장할 때 ``format`` 인수가 필요합니다.
file-like 번역 필요

2021-12-09 08:26 UTC, closed without merging

2021-12-09 08:26 UTC, 9bow commented
번역기를 돌리시더라도 전체적으로 원문과 비교하여 제대로된 번역으로 기여해주시기 바랍니다.
적절하게 번역이 되었는지 확인을 하는 작업은 번역과 비슷하거나 더 많은 시간과 노력을 필요로 하는 작업입니다.
이 PR 및 연관하여 올리신 모든 PR은 닫도록 하겠습니다.