Update audio_resampling_tutorial.py
PyTorchKorea/tutorials-kr pull request #407
Opened 2021-12-03 21:20 UTC by kimgooq

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #389 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

문서 번역 및 문법 검토 완료

2021-12-05 13:22 UTC, puhuk reviewed
우선 170 line 까지의 번역을 리뷰하였습니다.

2021-12-05 13:22 UTC, puhuk commented on beginner_source/audio_resampling_tutorial.py
> +#@제목 데이터와 유틸리티 함수를 준비합니다. {display-mode: "form"}
@title 은 번역하지 않고 그냥 두셔도 될 것 같습니다.

2021-12-05 13:22 UTC, puhuk commented on beginner_source/audio_resampling_tutorial.py
> +  offset은 음의 무한대 `log(offset + x)`를 피하기 위해 사용됩니다.
조금 풀어서 설명하는게 이해하기 쉬울 것 같습니다. 아래 제안드립니다.
x 가 0일 경우 log 값이 음의 무한대로 가는 것을 피하기 위해 다음과 같이 offset 을 더해 줍니다. `log(offset + x)`

2021-12-05 13:22 UTC, puhuk commented on beginner_source/audio_resampling_tutorial.py
> +  # 로그 스케일 주요 주파수 값이 속하는 x축 값을 찾습니다.
아래 제안드립니다.
로그 스케일로 변환된 주요 주파수 값의 값을 x축에서 찾습니다.

2021-12-06 20:08 UTC, kimgooq commented on beginner_source/audio_resampling_tutorial.py
> +#@제목 데이터와 유틸리티 함수를 준비합니다. {display-mode: "form"}
@title 그대로 두도록 하겠습니다

2021-12-06 20:09 UTC, kimgooq commented on beginner_source/audio_resampling_tutorial.py
> +  offset은 음의 무한대 `log(offset + x)`를 피하기 위해 사용됩니다.
훨씬 쉬운 번역 감사드립니다.

2021-12-06 20:11 UTC, kimgooq commented on beginner_source/audio_resampling_tutorial.py
> +  offset은 음의 무한대 `log(offset + x)`를 피하기 위해 사용됩니다.
좋은 리뷰 및 쉬운 번역 감사드립니다. 수정했습니다.

2021-12-06 20:13 UTC, kimgooq commented on beginner_source/audio_resampling_tutorial.py
> +  # 로그 스케일 주요 주파수 값이 속하는 x축 값을 찾습니다.
좋은 리뷰 감사드립니다. 해당 내용으로 수정했습니다.

2021-12-07 13:52 UTC, hyoyoung requested changes

2021-12-07 13:52 UTC, hyoyoung commented on beginner_source/audio_resampling_tutorial.py
> +# 두 리샘플링 방법 모두 `bandlimited sinc 보간 <https://ccrma.stanford.edu/~jos/resample/>`__ 을 사용하여
bandlimited는 대역 제한으로 번역 가능합니다

2021-12-07 13:52 UTC, hyoyoung commented on beginner_source/audio_resampling_tutorial.py
> +# 임의의 시간 단계에서 신호 값을 계산합니다. 구현에는 컨볼루션이
convolution은 용어집에 합성곱으로 되어있습니다
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2021-12-09 08:26 UTC, closed without merging

2021-12-09 08:26 UTC, 9bow commented
번역기를 돌리시더라도 전체적으로 원문과 비교하여 제대로된 번역으로 기여해주시기 바랍니다.
적절하게 번역이 되었는지 확인을 하는 작업은 번역과 비슷하거나 더 많은 시간과 노력을 필요로 하는 작업입니다.
이 PR 및 연관하여 올리신 모든 PR은 닫도록 하겠습니다.