advanced_source/ddp pipeline.py 번역
PyTorchKorea/tutorials-kr pull request #428
Opened 2022-01-28 13:08 UTC by spongebob03

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #418 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
advanced_source/ddp pipeline.py 문서 지문 번역했습니다. 주석 번역도 곧 추가하겠습니다.

2022-01-28 13:23 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +확장판이며 파이프라인 병렬화가 어떻게 트랜스포머 모델 학습에 쓰이는지 증명하기 위해 이전 튜토리얼에서의
`분산 데이터 병럴 처리` 라는 말이 빠졌다는 생각이 듭니다.

```suggestion
확장판이며 분산 데이터 병럴 처리와 파이프라인 병렬화가 어떻게 트랜스포머 모델 학습에 쓰이는지 증명하기 위해 이전 튜토리얼에서의
```

2022-01-28 13:28 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +분산 데이터 병렬 처리와 파이프라인 병렬화를 사용한 트랜스포머 모델 학습
[advanced_source/torch-script-parallelism.rst](https://github.com/PyTorchKorea/tutorials-kr/pull/386/files)
여기에서는 Parallelism이 병렬 처리라고 되어 있는데 여기에는 병렬화라고 번역이 되어 있군요.
개별 문서 내에선 의미가 통하지만 전체적으로는 조금씩 불일치가 보여
parallel, parallelism 이라는 용어를 정리해야 될 필요는 있겠군요.

2022-01-28 13:32 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 일부 정보를 주입합니다.
일부 정보라는 뜻은 위치 정보 중의 일부분만 시퀀스에 주입한다는 느낌이 들기도 하는군요.
`상대적` 이라는 단어와 쌍을 갖추게 뒤쪽에도 적을 붙여서 `절대적` 이라고 쓰면 어떨까 싶기도 합니다.
`상대적, 절대적 위치에 대한 몇몇 정보` 정도는 어떠신지요.

2022-01-28 13:36 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 프로세스는 분산 데이터 병렬처리로 두 복제본을 학습시킵니다.
자세히는 모르지만, 분산 환경에서 레플리카라는 것이 복제품이면서 예비용으로 데이터를 백업해 둔다는 의미 등
여러가지 의미를 가지는 용어라서 원본 뉘앙스를 유지하기 위해 
`복제본(replica)` 이렇게 원문을 추가해 주면 어떨지요.

2022-01-28 13:40 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 결과적으로, ``nn.TransformerEncoder`` 에 중점을 두고 있으며
our focus를 번역하여 사용하면 한국어에서는 자주 쓰이지 않는 우리의 관심사는~ 이런 식으로 쓰여
생략을 하신 것이 잘 되었다고 생각합니다.
약간 문장을 순화시키자면 이 튜토리얼 내부에서 ``nn.TransformerEncoder`` 집중한다는 의미를 강조하기 위해
튜토리얼 이라는 단어를 해당 문장의 주어로 삽입하면 어떨까 싶습니다.

`결과적으로, 이 튜토리얼에서는 ``nn.TransformerEncoder`` 에 중점을 두고 있으며`

2022-01-28 13:43 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# ``Decoder`` 섹션을 분리된 모듈로 빼낸 다음, 원본 트랜스포머 모듈을
영어를 직역하자면 이를 위해서`,` 라고 뒤에 숨표가 들어가야 되고 모듈로 빼낸 다음`,` 쉼표가 없어야 되지만
한국어 사용법에 맞게 쉼표를 적절하게 생략 및 삽입을 하여 좋은 번역을 하셨다는 생각이 듭니다.

2022-01-28 13:47 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 다음 단어인 ``Target`` 이 필요합니다. 에를 들어 ``bptt`` 의 값이 2라면,
`예를 들어` 오타가 있군요.

2022-01-28 13:48 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +#
잘못된 공백이 삽입된 것 같습니다.

2022-01-28 13:49 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 청크가 차원 0을 속하며
`차원 0에 속하며` 가 더 부드러운 표현이 아닐까 싶네요.

2022-01-28 13:51 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 트랜스포머 모델의 ''S'' 차원과 일치한다는 것을 유의해야 합니다.
S를 감싸고 있는 따옴표가 원문은 backtick인데 번역문엔 single quoto가 쓰였습니다.
문장 제일 뒤에 공백도 한 칸 추가되어 있네요.

2022-01-28 13:52 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 트랜스포머 계층 규모를 적절히 확장시킵니다. We use an embedding
원문을 안지우셨군요.

2022-01-28 13:53 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 4096차원의 임베딩 벡터, 4096의 은닉 사이즈, 16개의 어텐션 헤드(attention head)와  총 8 개의
`어텐션 헤드(attention head)와` 뒤에 공백이 두 칸이군요.
하나는 삭제하셔도 될 것 같습니다.

2022-01-28 13:54 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 이때 RPC 프레임워크는 오직 하나의 하나의 worker로 초기화를 해야 하는데,
문장 마지막에 공백이 들어가 있군요.

2022-01-28 13:59 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 다른 GPU에 8개의 트랜스포머 레이어로 초기화됩니다. 한 파이프는 GPU 0, 1에 거쳐 설정되고
위에서 레이어를 계층이라는 단어로 번역하셔서 `계층`이라는 단어를 일관성 있게 쓰는게 어떨까요.
`처음 8개의 트랜스포머와` 에서도 계층 관련해서 설명하고 있기 때문에 계층이라는 단어를 집어 넣어
명확하게 해 주는게 어떨까 싶습니다.

`한 GPU에 8개의 트랜스포머 계층과 다른 GPU에 8개의 트랜스포머 계층으로 초기화됩니다.`

2022-01-28 14:01 UTC, des00 commented on advanced_source/ddp_pipeline.py
> +# 다른 하나는 GPU 2, 3에 설정됩니다. 그런 다음 분산 데이터 병렬을 사용하여 두 파이프가 모두 복제됩니다.
`DistributedDataParallel` 이게 클래스 이름이라서 원문을 유지해야 될 거 같습니다.

2022-01-28 14:04 UTC, des00 commented
오래간만에 번역 작업을 하신걸 보니 반갑군요.
간단하게 리뷰 의견 남겨드립니다.

2022-01-29 02:56 UTC, spongebob03 commented on advanced_source/ddp_pipeline.py
> +분산 데이터 병렬 처리와 파이프라인 병렬화를 사용한 트랜스포머 모델 학습
피드백 주셔서 감사합니다! 짚어주신 것처럼 컴퓨터 프로세스 부분에서 병럴처리로 배웠는데 병렬화라는 용어는 어색한거 같네요. 따라서 `Pipeline Parallelism`을 `병렬 처리 파이프라인`으로 수정했습니다. Pipeline Parallelism에 대한 용어정리를 용어집에 추가하도록 건의해보겠습니다.

2022-01-29 05:43 UTC, codingbowoo requested changes
긴 문서 번역하느라 수고하셨습니다. 
번역이 까다로운 부분이 많았을 것 같은데 전반적으로 수월하게 읽을 수 있었습니다. 
오탈자나 대소문자, 일부 번역을 리뷰했으니 확인해보시면 좋겠습니다. 
정말 수고하셨습니다! 👍

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 둘을 합칠 수 있습니다. 여기서, 주파수가 다른 ``sine`` 과 ``cosine`` 기능을
여기서 function은 `기능` 이라기보다는 `함수` 로 보입니다.

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# `분산 데이터 병럴 처리 <https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html>`__
오타가 있는 것으로 보입니다.
- 병럴 -> 병렬

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 모델은 바로 `NN.TRANSFORMER 와 TORCHTEXT 로 시퀀스-투-시퀀스(SEQUENCE-TO-SEQUENCE) 모델링하기
위와 동일한 대소문자 표현을 제안드립니다.
- nn.Transformer 와 TorchText 로 시퀀스-투-시퀀스(Sequence-to-Sequence) 모델링하기

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# ``Decoder`` 섹션을 분리된 모듈로 빼낸 다음, 원본 트랜스포머 모듈을
오 진짜 이 부분 번역이 매끄럽네요!

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 각자 두 개의 GPU에서 자체 파이프라인을 구동하는 두 가지 프로세스를 시작합니다.
이건 좀 너무 사소한 어감의 차이를 말씀드리나 싶습니다만, 
- `각자` 라고 하면 각각의 사람이 따로따로 라는 뜻이고, 
- `각각` 이라고 하면 사람이나 물건의 하나하나마다 라고 합니다. 

그래서 여기서는 `각각` 을 사용하는게 , 그리고 `두 가지` 보다는 `두 개의` 프로세스라고 하면 더 자연스러울 것 같습니다. 
(근본적으로 두 프로세스가 하는 일(train the two replicas)은 같기 때문- 두 가지라 그러면 서로 하는 일이 다를 것 같아요)

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 병렬 처리 파이프라인을 활용한 대형 트랜스포머 모델 학습을 증명하기 위해,
앞과 마찬가지로 `증명하기 위해` 대신 `보이기 위해`를 제안드립니다.

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 이는 향후 호스트 파이프라인을 교차 확장할 수 있도록 하기 때문입니다.
호스트 파이프라인을 교차 확장할 수 있도록 해주는게 RRef 라는 점이 더 잘 드러나야 할 것 같습니다. 

- Pipe가 향후 호스트 파이프라인을 교차 확장할 수 있도록 해주는 `RRef <https://pytorch.org/docs/stable/rpc.html#rref>`__ 를 통해 RPC 프레임워크에 의존하기 때문입니다.

는 어떠실까요? (마크다운 문법때문에 블록이 생기네요)

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 손실(loss)을 추적하기 위해 `CrossEntropyLoss <https://pytorch.org/docs/master/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss>`__ 가
용어집에 loss는 손실로 정의되어있어서, 이 부분은 영문 표기를 병기하지 않아도 괜찮을 것 같습니다.

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 적용되며, 옵티마이저(optimizer)로서 `SGD <https://pytorch.org/docs/master/optim.html?highlight=sgd#torch.optim.SGD>`__
용어집에 옵티마이저는 음차 표기 하는 것으로 정의되어 영문 표기 병기하지 않아도 괜찮을 것 같습니다.

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 학습률(learning rate)은 5.0로 설정됩니다. `StepLR <https://pytorch.org/docs/master/optim.html?highlight=steplr#torch.optim.lr_scheduler.StepLR>`__ 는
용어집에 따라 영문 표기를 병기하지 않아도 괜찮을 것 같습니다.

2022-01-29 05:43 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 에폭(epoch)에 따라서 학습률을 조절하는 데 사용됩니다. 학습하는 동안,
용어집에 따라 영문 표기를 병기하지 않아도 괜찮을 것 같습니다.

2022-01-30 03:20 UTC, spongebob03 commented on advanced_source/ddp_pipeline.py
> +이번 튜토리얼은 `NN.TRANSFORMER 와 TORCHTEXT 로 시퀀스-투-시퀀스(SEQUENCE-TO-SEQUENCE) 모델링하기 <https://tutorials.pytorch.kr/beginner/transformer_tutorial.html>`__ 의
제안해주신 표기로 수정하니 참고 문서 제목에 대해 더 잘 인식할 수 있는거 같습니다. 피드백 감사합니다!

2022-01-30 03:56 UTC, des00 approved these changes
LGTM

2022-01-30 04:03 UTC, spongebob03 commented on advanced_source/ddp_pipeline.py
> +# 손실(loss)을 추적하기 위해 `CrossEntropyLoss <https://pytorch.org/docs/master/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss>`__ 가
제안해주신 대로 좀 더 간결하게 서술할 수 있을거 같습니다. 다만 용어집에 있는 용어 중 문서 상에 처음으로 등장하는 용어는 영문과 함께 표기하였습니다. 문서를 읽는 사용자는 저장소의 용어집을 모를 수 있으니 손실의 경우 아래 참고 코드에서 `loss`, `total_loss`등으로 쓰여서 처음 등장할 떄 같이 표기해주는 것이 참고 코드 이해에 좀 더 나을거 같았습니다. 같이 짚어주신 부분들도 이러한 이유로 유지하는건 어떨까요..?

2022-02-01 14:10 UTC, codingbowoo commented on advanced_source/ddp_pipeline.py
> +# 손실(loss)을 추적하기 위해 `CrossEntropyLoss <https://pytorch.org/docs/master/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss>`__ 가
네 좋습니다 :)

2022-02-01 14:11 UTC, codingbowoo approved these changes
좋습니다 :) 수고하셨습니다!

2022-02-02 04:57 UTC, 9bow approved these changes

2022-02-02 04:57 UTC, merged