Update char_rnn_generation_tutorial.py
PyTorchKorea/tutorials-kr pull request #500
Opened 2022-07-28 06:06 UTC by stella-oh

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [ ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2022-07-28 13:00 UTC, garam24 commented
위에 라이선스 동의에서 체크 박스 표시가 반영되지 않은 것 같습니다!

### 라이선스 동의
동의하시면 아래 [ ]를 [x]로 만들어주세요.

[x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

2022-07-28 15:06 UTC, hyoyoung requested changes
라이선스 동의 해주세요

2022-08-01 09:55 UTC, stella-oh commented
라이선스 동의 완료했습니다 :)

2022-08-03 02:34 UTC, gorae17 approved these changes
`몇 번 train() 을 호출하고` -> `train() 을 몇 번 호출하고` 로 바꾸면 더 자연스러울 것 같습니다.

2022-08-03 13:09 UTC, hyoyoung approved these changes
> `몇 번 train() 을 호출하고` -> `train() 을 몇 번 호출하고` 로 바꾸면 더 자연스러울 것 같습니다.

gorae17 님이 남겨주신 comment입니다 다음번 혹시 개선 pr 주실때 참고 부탁드립니다

good

2022-08-03 13:09 UTC, merged