add words #544
PyTorchKorea/tutorials-kr pull request #545
Opened 2022-08-06 14:11 UTC by gorae17

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #544

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [x] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
TRANSLATION_GUIDE.md에 용어 build와 nightly build를 추가합니다.

2022-08-07 01:58 UTC, bub3690 commented
nightly 빌드 라고하면, 빌드만 해석이 된 것 같아요.

'나이틀리 빌드'
'일단위 빌드' 이런건 어떨까요?

아니면 따로 용어집에 추가 안하는게 좋아보입니다.

2022-08-08 10:03 UTC, gorae17 commented
> nightly 빌드 라고하면, 빌드만 해석이 된 것 같아요.
> 
> '나이틀리 빌드' '일단위 빌드' 이런건 어떨까요?
> 
> 아니면 따로 용어집에 추가 안하는게 좋아보입니다.

@bub3690 
용어의 특성 상 번역하는 것보다 그대로 사용하는 것이 자연스러워보였고, 
통일성을 위해 번역을 하지 않는 경우도 용어집에 추가를 하는 듯 하여 추가해보았습니다. 
`나이틀리(nightly) 빌드` 로 표현할 수는 있을 것 같은데, 나이틀리 라는 용어를 자주 사용하는 것은 아니라서 원문만 쓰는 것이 깔끔하지 않을까 싶었어요.

2022-08-17 00:29 UTC, hyoyoung commented
둘다 좋은 PR이나 nightly 빌드 같은 경우는 여러 생각해볼 여지가 있을듯합니다
몇몇 오픈소스에서는 nightly build를 개발자 빌드라고 하기도 합니다
nightly build는 다른 PR로 분리해서 보내주시기 바랍니다

2022-08-17 00:29 UTC, hyoyoung requested changes
2개의 PR로 분리 필요

2022-09-01 12:29 UTC, gorae17 commented
용어 빌드는 https://github.com/PyTorchKorea/tutorials-kr/pull/591 로 분리하여 올렸습니다.

2022-09-01 12:29 UTC, closed without merging