prototype_source/skip_param_init.rst 번역
PyTorchKorea/tutorials-kr pull request #559
Opened 2022-08-13 05:13 UTC by updaun

vscode-hanspell을 활용하여 맞춤법 검사를 진행했습니다.

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(558)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
prototype_source/skip_param_init.rst 파일을 영문에서 한문으로 수정합니다.
https://tutorials.pytorch.kr/prototype/skip_param_init.html 페이지가 한글화됩니다.

* 연습용 레포에서 피드백 받은 내용입니다. (https://github.com/hyoyoung/22-tutorials-ex/pull/23)
* 피드백 내용을 반영하였습니다.
* vscode-hanspell을 활용하여 추가적으로 맞춤법 검사를 진행했습니다.
* make html-noplot 빌드하여 최종 웹화면을 확인했습니다.

* device의 번역 관련하여 매개변수로 활용되는 경우 device로 번역하지 않았으며, 
* CPU device -> CPU 장치 와 같이 의미적으로 활용되는 경우 장치로 번역하였습니다.

2022-08-13 05:43 UTC, terri1102 commented
이슈번호 링크가 걸리지 않은 것 같습니다!

2022-08-17 03:31 UTC, YunjinJo requested changes
일부분만 일단 수정 사항 남겼습니다. 나머지 부분은 나중에 시간 되면 다시 코멘트 달도록 하겠습니다!

2022-08-17 03:31 UTC, YunjinJo commented on prototype_source/skip_param_init.rst
> +        # 모든 서브 모듈은 device를 재귀적으로 전달해야 합니다.
두 문장을 하나로 합치신 것 같은데 세미콜론은 뒷 문장을 연결하는 역할이기 때문에 문장을 나누는게 좋을 것 겉습니다.

2022-08-28 15:16 UTC, terri1102 reviewed
전반적으로 매끄러운 번역입니다. 수고하셨습니다!

2022-09-04 13:47 UTC, hjvision96 commented
잘 번역하신 것 같습니다. 고생하셨습니다!

2022-09-04 14:07 UTC, hjvision96 reviewed
잘 번역하신 것 같습니다. 고생하셨습니다.

2022-09-06 14:48 UTC, hyoyoung requested changes
전반적으로 읽기 편한 번역입니다. 몇가지 수정사항을 부탁드립니다

2022-09-06 14:48 UTC, hyoyoung commented on prototype_source/skip_param_init.rst
> +모듈이 업데이트된 것을 나타냅니다.
원본 문장 자체가 복잡하니 쪼개서 번역하는 것도 방법일것 같습니다

> The following example demonstrates a module updated to support the `device`
> kwarg by passing it along to any created parameters, buffers, or submodules

> The following example demonstrates a module updated to support the `device` kwarg by passing

>  it along to any created parameters, buffers, or submodules

아래 예시는 모듈이 `device` 키워드 인자(keyword argument) 전달을 지원하기 위해 업데이트 된것을 보여줍니다.

생성된 파라미터, 버퍼, 서브모듈를 따라서.

합쳐보면 

다음은 `device` 키워드 인자(keyword argument)가 생성된 파라미터, 버퍼, 서브모듈로 따라 전달되기 위한
모듈 업데이트를 보여주는 예시입니다.

2022-09-06 14:48 UTC, hyoyoung commented on prototype_source/skip_param_init.rst
> +모듈은 "meta" 장치 (device)로 인스턴스화하여 동작합니다. tensor shape 정보를 가지고 있지만 스토리지는 할당하지 않습니다.
스토리지는 저장 공간으로 바꿔써도 좋을듯합니다

2022-09-06 14:48 UTC, hyoyoung commented on prototype_source/skip_param_init.rst
> +:ref:`Updating` 에 설명된 대로 이 패턴은 모듈 구성 중 `device` 키워드 인자 (keyword argument)를 적절히 지원하는 모듈에서만 작동합니다.
키워드 인자(keyword argument)는 여러차례 나오므로
맨 처음 이외에는 그냥
키워드 인자라고만 써도 될것 같습니다

2022-09-07 13:09 UTC, YunjinJo reviewed
LGTM

2022-09-07 13:09 UTC, YunjinJo approved these changes
LGTM

2022-09-07 14:45 UTC, hyoyoung approved these changes
good

2022-09-07 14:45 UTC, merged