prototype_source/tracing_based_selective_build.rst 번역
PyTorchKorea/tutorials-kr pull request #565
Opened 2022-08-16 17:44 UTC by bub3690

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(562)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

- https://github.com/hyoyoung/22-tutorials-ex/pull/26 피드백 반영해서 수정 완료 했습니다.
- Make html-noplot으로 문법 적용 확인했습니다.
- 또한 'Conclusion', '더 배우기' 에서 링크가 <>_ 으로 걸려있지 않은 것들을 수정했습니다.

2022-08-28 13:39 UTC, bub3690 commented
Challengers C조에서 한번 수정을 받았습니다.
간단히 체크 부탁드립니다.

2022-09-11 15:49 UTC, hyoyoung requested changes
긴 글 번역하느라 수고하셨습니다.

몇가지 수정사항을 제안드립니다

2022-09-11 15:49 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +(prototype)  추적-기반 선택적 빌드 모바일 Android, iOS 인터프리터
추적 앞에 공백이 한칸 더 들어가있는듯 합니다

2022-09-11 15:49 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +    # 비교를 위해, jit 전체 버전 모델을 출력합니다.(가벼운 인터프리터와는 호환되지 못합니다.)
호환되지 못합니다 보다는 호환되지 않습니다가 조금 더 자연스러울 듯 합니다

2022-09-11 15:49 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +    # 가벼운 인터프리터 버전 모델을 출력합니다.( 가벼운 인터프리터와 호환됩니다.)
(과 '가벼운' 사이에 공백은 없어도 될듯합니다

2022-09-11 15:49 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +    # 단계 3. 모델과 단계2에서 준비된 인풋을 같이 묶어줍니다. 가능한 많은 인풋을 묶어줍니다.
인풋을 그대로 쓰기보다는 입력으로 순화가 가능할듯 합니다

2022-09-11 15:49 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +이미지 영역 분할 예제를 수행하며 모델에 들어갈 인풋을 어떻게 묶는지 보여주었고, 묶인 인풋과 모델을 추적함으로써 연산자 리스트를 생성했고,  추적된 결과의 연산자 리스트와 소스로 커스텀 torch 라이브러리를 빌드했습니다.
여기서도 인풋은 입력으로 순화 가능할듯 합니다

2022-09-12 14:41 UTC, gorae17 approved these changes
맞춤법 위주로 남겼습니다, 고생하셨습니다!

2022-09-12 14:41 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +추적-기반 선택적 빌드는 라이브러리 사이즈를 줄이기 위한 프로토타입 기능입니다. 추적된 결과는 모델 입력과 추적된 환경에 의존합니다. 따라서, 만약 추적기가 모바일 인터프리터가 아닌 다른 환경에서 실행되면, 연산자 리스트가 실제 사용된 연산자 리스트와 다를 수 있고 빠진 연산자들이 오류를 발생 시킬수 있습니다.
발생 시킬수 -> 발생시킬 수

2022-09-12 14:41 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +이 튜토리얼은 모바일 인터프리터 사이즈를 더욱 더 최소화 하기위해, 모바일 인터프리터 빌드를 커스터마이즈하는 새로운 방법을 소개합니다. 컴파일된 이진 파일에 포함되는 연산자들을 목표 모델에 실제로 필요로하는 집합 만큼으로 제한합니다. 파이토치의 모바일 배포의 이진 파일 사이즈를 줄이는 기술입니다. 추적 기반 선택적 빌드는 모델을 특정 대표 입력값들과 함께
- 더욱 더 -> 더욱더
- 최소화 하기위해 -> 최소화하기 위해 
- 필요로하는 -> 필요로 하는
- 집합 만큼으로 -> 집합만큼으로
- 포함하게됩니다 -> 포함하게 됩니다

2022-09-12 14:41 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +만약 ``x86`` 의 Pixel 4 emulator에서 테스트 된다면, cmd 에서 ``BUILD_LITE_INTERPRETER=1 ./scripts/build_pytorch_android.sh x86`` 사용하여, 빌드 시간을 절약하기 위해 abi를 명시 해줍니다.
명시 해줍니다 -> 명시해줍니다

2022-09-12 14:41 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +2. **이미지 영역 분할 App 소스에서 빌드된 Pytorch Android 라이브러리를 사용합니다**: 경로에 `libs` 폴더를 만들고, 경로는 root 저장소로 부터 `ImageSegmentation/app/libs` 가 됩니다. `pytorch_android-release` 를 경로 ``ImageSegmentation/app/libs/pytorc
저장소로 부터 -> 저장소로부터

2022-09-12 14:41 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +이미지 영역 분할 예제를 수행하며 모델에 들어갈 인풋을 어떻게 묶는지 보여주었고, 묶인 인풋과 모델을 추적함으로써 연산자 리스트를 생성했고,  추적된 결과의 연산자 리스트와 소스로 커스텀 torch 라이브러리를 빌드했습니다.
'추적된' 앞에 띄어쓰기가 두 개인 것 같습니다.

2022-09-12 14:41 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +읽어주셔서 감사합니다! 언제나, 어떤 피드백이든 환영합니다, 그러니  `<https://github.com/pytorch/pytorch/issues>`_ 에 이슈를 생성해주세요.
'그러니'를 빼고, '언제나 어떤 피드백이든 환영합니다. `<https://github.com/pytorch/pytorch/issues>`_ 에 이슈를 생성해주세요.'가 조금 더 자연스럽다는 의견 남깁니다. 이 부분은 취향 차이일 수 있으니 반영하시지 않아도 괜찮습니다!

2022-09-14 15:27 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +이 튜토리얼은 모바일 인터프리터 사이즈를 더욱 더 최소화 하기위해, 모바일 인터프리터 빌드를 커스터마이즈하는 새로운 방법을 소개합니다. 컴파일된 이진 파일에 포함되는 연산자들을 목표 모델에 실제로 필요로하는 집합 만큼으로 제한합니다. 파이토치의 모바일 배포의 이진 파일 사이즈를 줄이는 기술입니다. 추적 기반 선택적 빌드는 모델을 특정 대표 입력값들과 함께
감사합니다. 헷갈리는 맞춤법이 많군요

2022-09-14 15:29 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +읽어주셔서 감사합니다! 언제나, 어떤 피드백이든 환영합니다, 그러니  `<https://github.com/pytorch/pytorch/issues>`_ 에 이슈를 생성해주세요.
좋은 의견입니다!

2022-09-15 02:37 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
>  ===============================================================================
제목에 == 길이가 달라서 추가 수정을 진행했습니다.

2022-09-15 14:24 UTC, merged