intermediate/realtime_rpi.rst 번역
PyTorchKorea/tutorials-kr pull request #575
Opened 2022-08-25 19:07 UTC by YunjinJo

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #560 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
https://pytorch.org/tutorials/intermediate/realtime_rpi.html?utm_source=whats_new_tutorials&utm_medium=rpi  
문서를 번역하였습니다.

2022-08-27 23:49 UTC, updaun commented on intermediate_source/realtime_rpi.rst
> +            # 프레임 읽기
opencv에서 보통 프레임이란 단어를 많이 사용하지만, 사진과 같은 이미지를 영상이라고 많이 표현하는 것으로 알고 있습니다! frame을 음차표기 하지 않고 영상으로 사용하는 것은 어떤가요? 

[네이버 어학사전]
https://dict.naver.com/search.dict?dicQuery=%EC%98%81%EC%83%81&query=%EC%98%81%EC%83%81&target=dic&ie=utf8&query_utf=&isOnlyViewEE=

2022-08-27 23:55 UTC, updaun commented on intermediate_source/realtime_rpi.rst
> +            # output으로 무언가를 처리 ...
번역은 맞게 되었지만 해당 부분이 다소 어색하게 느껴집니다. 혹시 가능하다면 토의를 통해서 내용을 조금 변형하는 것은 어떨까요? 해당 부분이 모델에 통과시키는 부분인 것 같은데, 예를 들어 모델 추론과 같은 단어가 추가되는 것이 어떨까 생각해봤습니다!
추가적으로 output은 용어집을 참고하여 출력으로 번역하는 것은 어떤가요? 
![image](https://user-images.githubusercontent.com/82289435/187051833-2d7a802b-17b3-48d6-a96c-a1eae7a4ab2e.png)

2022-08-27 23:56 UTC, updaun approved these changes
내용이 상당히 많은데 정말 고생하셨습니다! 대체적으로 번역이 잘 된 것 같습니다!

2022-08-28 14:39 UTC, terri1102 reviewed
전반적으로 매끄럽게 번역하신 것 같습니다. 고생하셨습니다!

2022-08-28 14:39 UTC, terri1102 commented on intermediate_source/realtime_rpi.rst
> +성능이 낮은 3B에서도 작동합니다.
'reduced performance' 를 '낮은 성능으로 작동'한다고 번역하는 것이 어떨까요? 현재 번역에서는 성능이 떨어진다는 내용이 안 들어간 것 같습니다.
 2GB 모델(variant) 이나 성능이 낮은 3B에서도 작동합니다.-> 2GB 모델(variant) 이나 3B에서도 낮은 성능으로 작동합니다.

2022-08-28 14:39 UTC, terri1102 commented on intermediate_source/realtime_rpi.rst
> +* 방열판 및 팬 (선택사항이지만 사용하는걸 권장합니다.)
'사용하는걸' -> '사용하는 걸' 로 띄어써야 합니다.

2022-08-28 14:39 UTC, terri1102 commented on intermediate_source/realtime_rpi.rst
> +`picamera`는 64-bit Raspberry Pi OS에서 사용이 불가능하고 OpenCV보다 훨씬 느립니다.
`picamera` 뒤에 띄어쓰기가 없는 것 같은데 inline highlighting이 깨지지 않나요?

2022-08-28 14:39 UTC, terri1102 commented on intermediate_source/realtime_rpi.rst
> +프레임을 가져와서 예상하는 형식으로 변환해야 합니다. 이것은 표준 torchvision 변환을 사용하는 것과 동일한 처리입니다.
'model expects'를 '모델이 기대(예상)'하는으로 번역하면 어떨까요?
'프레임을 가져와서 예상하는 형식으로'  -> '프레임을 가져와서 모델이 기대하는 형식으로'

2022-08-28 14:39 UTC, terri1102 commented on intermediate_source/realtime_rpi.rst
> +양자화되었다는 뜻은 표준 float32 연산보다 훨씬 성능이 좋은 int8을 사용하여 계산하는 것입니다.
performant를 어떻게 번역하는 게 좋을지 애매하네요... '훨씬 성능이 좋은'이라고 번역하면 모델 성능이 좋다는 식으로 오독될 수 있을 것 같습니다. '연산 효율적인' 정도로 번역하는 건 어떨까요?

2022-09-04 14:07 UTC, hjvision96 commented on intermediate_source/realtime_rpi.rst
> +레이어에 병합될 수 있습니다.
'things like activation'라 말하고, 그 예시로 'ReLU'를 드는 것 같고, 'the layer before'이라 말하고, 그 예시로 'Conv2d'를 드는 것 같습니다. 그래서 개인적인 의견으로는
(``Conv2d``) 전에 레이어에 -> 이전 레이어(``Conv2d``)에 
등 과 같이 수정이 되면 어떨까요?

2022-09-07 15:03 UTC, hyoyoung requested changes
긴 문서 번역하느라 수고하셨습니다

몇가지 수정사항을 부탁드립니다

2022-09-07 15:03 UTC, hyoyoung commented on intermediate_source/realtime_rpi.rst
> +다음으로 Python 오버헤드를 줄이고 모든 작업을 융합하기 위해 모델을 JIT합니다. JIT 없이는 ~20fps를 제공하지만 JIT은 ~30fps를 제공합니다.
JIT 없이는 ~20fps이지만 JIT를 사용하면 ~30fps입니다.

요렇게 약간 의역하면 어떨까요?

2022-09-09 18:13 UTC, YunjinJo commented on intermediate_source/realtime_rpi.rst
> +PyTorch는 Raspberry Pi 4에서 바로 사용할 수 있습니다.
상자에서 꺼낸다는 말이 잘 와닿지 않을 것 같아서 out of box의 속 뜻인 "별도의 설치 없이도 동작한다" 라는걸 살려서 번역하고 싶은데 잘 생각이 안나네요. 일단 "별도의 설정 없이 지원합니다" 라고 조금이나마 바꿔봤습니다.

2022-09-10 13:26 UTC, hyoyoung requested changes
지난 번에 이어 몇가지 수정사항을 제안드립니다

2022-09-10 13:26 UTC, hyoyoung commented on intermediate_source/realtime_rpi.rst
>  **Author**: `Tristan Rice <https://github.com/d4l3k>`_
Author는 저자로 보통 번역하였습니다

2022-09-10 13:26 UTC, hyoyoung commented on intermediate_source/realtime_rpi.rst
> +  **번역**: `조윤진 <https://github.com/YunjinJo>`_
번역앞에 2칸 공백은 없어도 될듯합니다

2022-09-10 13:26 UTC, hyoyoung commented on intermediate_source/realtime_rpi.rst
> +융합되었다는 뜻은 가능한 경우 연속된 작업이 더 성능이 좋은 버전으로 함께 융합되는 것을 말합니다.
약간의 의역이 더 보기편하게 할 거 같은데요

융합되었다는 뜻은 가능한 경우 연속된 작업이 더 성능이 좋은 버전으로 함께 융합되는 것을 말합니다.

-> 

융합되었다는 뜻은 가능한 경우 연속된 작업이 더 성능이 좋은 버전으로 함께 합쳐진 것을 말합니다.

요정도는 어떨까요?

2022-09-10 13:26 UTC, hyoyoung commented on intermediate_source/realtime_rpi.rst
> +            # 출력으로 무언가를 처리 ...
여기서 output은 출력 변수이기도 하니까

output 출력 변수로 무언가를 처리 ...

이렇게 바꿔는건 어떨까요?

2022-09-12 10:51 UTC, YunjinJo commented on intermediate_source/realtime_rpi.rst
> +  **번역**: `조윤진 <https://github.com/YunjinJo>`_
앞에 공백 없으면 
<img width="275" alt="스크린샷 2022-09-12 오후 7 50 36" src="https://user-images.githubusercontent.com/42915126/189635783-caf27ea5-2827-4e11-9f27-dd1523c72ac1.png">
이런식으로 한 줄로 되던데 괜찮나요?

2022-09-12 13:21 UTC, hyoyoung commented on intermediate_source/realtime_rpi.rst
> +  **번역**: `조윤진 <https://github.com/YunjinJo>`_
보통 한줄 더 내림하는데, 여의치 않으면 그냥 지금처럼 앞에 공백으로 해주세요

미처 생각을 못했는데, 요것도 뭔가 convention이 필요할거 같네요

2022-09-13 12:14 UTC, hyoyoung approved these changes
good

2022-09-13 12:14 UTC, merged