beginner_source/introyt/introyt1_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #580
Opened 2022-08-28 15:05 UTC by kimtaehyeong

Signed-off-by: taehyungkim <kimtaehyeong62@gmail.com>

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #579

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
https://tutorials.pytorch.kr/beginner/introyt/introyt1_tutorial.html 한글 번역

2022-08-30 01:52 UTC, 2kkeullim reviewed
: 만 빼주시면 될 것 같고, 자잘한 것들은 comment 남겼습니다!

2022-08-30 01:52 UTC, 2kkeullim commented on beginner_source/introyt/introyt1_tutorial.py
> +처음으로, 우리는 PyTorch를 import할 것입니다.
First를 '처음으로'보다 '먼저'라고 번역하는 경우가 많더라고요..

2022-08-30 01:52 UTC, 2kkeullim commented on beginner_source/introyt/introyt1_tutorial.py
> +# 종종 결과의 재현성을 위해 PRNG에 대한 특정 시드로 초기화합니다:
: 는 빼주셔도 될 것 같습니다

2022-08-30 01:52 UTC, 2kkeullim commented on beginner_source/introyt/introyt1_tutorial.py
> +# 스칼라를 사용한 연산은 tensor에 분산됩니다:
: 는 빼주셔도 될 것 같습니다

2022-08-30 01:52 UTC, 2kkeullim commented on beginner_source/introyt/introyt1_tutorial.py
> +# -  계층 C3는 다른 합성곱 계층으로, 이 시점은 특징들의 조합을 위해 C1 활성화 맵 검색합니다.
C1 활성화 맵 -> C1 활성화 맵을 로 조사 추가해주셔야할 것 같습니다

2022-08-30 01:52 UTC, 2kkeullim commented on beginner_source/introyt/introyt1_tutorial.py
> +# ``(16, 10)`` 의 형태를 가지고 있습니다..
.이 2개 들어갔어요!

2022-08-30 07:50 UTC, kimtaehyeong commented
> : 만 빼주시면 될 것 같고, 자잘한 것들은 comment 남겼습니다!

좋은 리뷰해주셔서 감사합니다. 해당 부분은 수정하였습니다.

2022-08-30 07:58 UTC, kimtaehyeong reviewed
reflected,

2022-09-04 02:11 UTC, kil-jung-keong commented
번역 잘 해주신것 같습니다!

2022-09-04 06:37 UTC, 95hj commented on beginner_source/introyt/introyt1_tutorial.py
> +#    이미지에서 학습된 각 특징을  위치에 대한 출력 맵을 보여줍니다.
'특징을' 과 '위치에' 사이에 띄어쓰기가 두 번 입력된 것으로 보입니다.

2022-09-04 06:37 UTC, 95hj commented on beginner_source/introyt/introyt1_tutorial.py
> +# 위 에서 다뤘던 내용들을 종합하여 모델을 학습시키겠습니다:
'위에서'에 띄어쓰기 오류입니다.

2022-09-04 06:37 UTC, 95hj commented on beginner_source/introyt/introyt1_tutorial.py
> +# 있는 정확도가 10% 정도 좋은 결과를 보여줍니다. 이 결과는 모델에서
'정확도 보다' 로 번역하는 것이 자연스러워 보입니다.

2022-09-04 13:16 UTC, kimtaehyeong reviewed
해당 리뷰 내용 업데이트하였습니다.

2022-09-04 13:16 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 있는 정확도가 10% 정도 좋은 결과를 보여줍니다. 이 결과는 모델에서
네 해당 내용 수정하였습니다.

2022-09-04 13:16 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 위 에서 다뤘던 내용들을 종합하여 모델을 학습시키겠습니다:
좋은 지적 감사합니다.

2022-09-04 13:16 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# -  계층 C3는 다른 합성곱 계층으로, 이 시점은 특징들의 조합을 위해 C1 활성화 맵 검색합니다.
해당 내용 반영하였습니다.

2022-09-04 13:16 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +#    이미지에서 학습된 각 특징을  위치에 대한 출력 맵을 보여줍니다.
해당 리뷰 수정하였습니다.

2022-09-06 12:55 UTC, 95hj approved these changes
고생하셨습니다!

2022-09-07 15:21 UTC, hyoyoung requested changes
긴 문서 번역하느라 고생하셨습니다.

몇가지 수정사항을 제안드립니다.

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +, 우리는 PyTorch를 import할 것입니다.
주어는 강조의 의미가 아니면 생략합니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# -  계층 C3는 다른 합성곱 계층으로, 이 시점은 특징들의 조합을 위해 C1 활성화 맵 검색합니다.
조합에 원본처럼 *조합*으로 강조를 넣어줘도 좋을듯합니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +#    가져와 10개의 bin 중 하나로 분류하는 분류기입니다.
십진수를 표현하는 10개의 bin 중 하나로 *분류*하는 분류기입니다.

요렇게 바꿔보면 어떨까요?

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +#    ``__init__()`` 함수를 갖는다. (예를들면 NLP 모델은 어휘를 불러올 수 있다)
위 부분의 어투가 다른 문서와 다릅니다
다른 문서는 ~입니다 처럼 써있습니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# 일반적으로 배치 단위의 이미지를 로드하고 텐서로 변환합니다.
일반적으로 배치 단위의 이미지를 읽어들이고, 이미지와 같은 크기의 텐서로 변환합니다.

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# tensor 의 추가 차원인 *batch 차원* 을 알아챘을 수 있다.
어투가 다릅니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# 정답 레이블 출력하기
위에서는 label이라고 썼습니다. 한가지로 통일되면 좋을듯합니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# 이 모델은 3채널(color) 이미지에 맞게 변형된 LeNet 모델이기 때문입니다.
만약 모델 구조가 익숙하게 보인다면, 
이 모델은 이번 영상에서 앞서 다뤄진 3채널(color) 이미지에 맞게 변형된 LeNet 모델이기 때문입니다.

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# 차이를 표현하는 지표입니다. Cross-entropy 손실 함수는 일반적인 분류 모델의
> 손실 함수(loss function)는 데이터 기반으로 모델이 예측한 값과 정답 값이 차이를 표현하는 지표입니다.

'정답 값의 차이'로 바꿔도 좋을듯하나

모델이 예측한 값과 정답 값이 얼마나 차이가 나는지를 표현하는 지표입니다. 정도로 의역해도 좋을듯합니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# 이 예제에서 **학습 에폭 2번** 만 반복합니다(1번째 라인) - 즉, 학습
1번째 라인 보다는
1번째 줄이 더 어울릴것 같습니다

2022-09-07 15:21 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# 일반적인 모델 학습이 발생했음을 보여줍니다.
> 이 결과는 모델에서 일반적인 모델 학습이 발생했음을 보여줍니다.

이 결과는 모델에서 일반적인 학습이 발생했음을 보여줍니다.

2022-09-07 15:43 UTC, kimtaehyeong reviewed
말씀주신 내용 다 변경하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 일반적인 모델 학습이 발생했음을 보여줍니다.
해당 내용 반영하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 이 예제에서 **학습 에폭 2번** 만 반복합니다(1번째 라인) - 즉, 학습
줄로 내용 변경하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 차이를 표현하는 지표입니다. Cross-entropy 손실 함수는 일반적인 분류 모델의
넵, 좀 더 편하게 변역하는게 좋아보입니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 이 모델은 3채널(color) 이미지에 맞게 변형된 LeNet 모델이기 때문입니다.
해당 내용 수정하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 정답 레이블 출력하기
label로 통일하겠습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# tensor 의 추가 차원인 *batch 차원* 을 알아챘을 수 있다.
어투 통일하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 일반적으로 배치 단위의 이미지를 로드하고 텐서로 변환합니다.
해당 내용 반영하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +#    ``__init__()`` 함수를 갖는다. (예를들면 NLP 모델은 어휘를 불러올 수 있다)
입니다 어투로 변경하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +#    가져와 10개의 bin 중 하나로 분류하는 분류기입니다.
넵, 해당 내용 변경하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# -  계층 C3는 다른 합성곱 계층으로, 이 시점은 특징들의 조합을 위해 C1 활성화 맵 검색합니다.
강조 넣어 수정하였습니다.

2022-09-07 15:43 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +, 우리는 PyTorch를 import할 것입니다.
주어 빼고 내용 수정하였습니다.

2022-09-08 15:43 UTC, hyoyoung requested changes
지난 리뷰 검토하느라 수고하셨습니다.

몇가지 제안사항을 드립니다.

2022-09-08 15:43 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +`03:50 <https://www.youtube.com/watch?v=IC0_FRiX-sw&t=230s>`__ 에 시작하는 비디오를 시청하세요.
위에는 video를 영상이라고 하였으니, 여기도 비디오를 영상으로 바꾸는게 좋을듯 합니다

2022-09-08 15:43 UTC, hyoyoung commented on beginner_source/introyt/introyt1_tutorial.py
> +# -  그 외에는 다른 모델처럼 클래스를 구성할 수 있습니다.
> you can build out your model class like any other Python class,
이 부분은 '다른 모델처럼 클래스를 구성할 수 있습니다.'보다

'다른 파이썬 클래스처럼 모델 클래스를 구성할 수 있습니다.'가 좀 더 자연스럽지 않을까요?

2022-09-08 16:31 UTC, kimtaehyeong reviewed
제안해주신 내용 업데이트 하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# `14:00 <https://www.youtube.com/watch?v=IC0_FRiX-sw&t=840s>`__ 에 시작하는 비디오를 시청하세요.
영상으로 통일했습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# -  그 외에는 다른 모델처럼 클래스를 구성할 수 있습니다.
지적해주신 내용으로 자연스럽게 변경하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +#    가져와 십진수를 표현하는 10개의 bin 중 하나로 분류하는 분류기입니다.
해당 내용 강조 넣었습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 위 그림 LeNet-5의 다이어그램은 초기 합성곱 신경망 중 하나이자 딥 러닝에서
"위 그림" 이라는 내용을 빼고 수정하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 이 내용은 다른 비디오에서 자세히 살펴보겠습니다.
영상으로 용어 통일하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +print('\nr의 절대:')
절대값으로 수정하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 다음은 사용 가능한 수학적 연산 작은 예제 입니다:
"작은 수학 연산 예제" 로 변경하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +# 0으로 채워진 32비트 부동소수점 데이터 타입인지 확인합니다.
해당 내용 수정하였습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +, PyTorch를 import할 것입니다.
, 제거했습니다.

2022-09-08 16:31 UTC, kimtaehyeong commented on beginner_source/introyt/introyt1_tutorial.py
> +`03:50 <https://www.youtube.com/watch?v=IC0_FRiX-sw&t=230s>`__ 에 시작하는 비디오를 시청하세요.
영상으로 변경했습니다.

2022-09-09 13:49 UTC, hyoyoung approved these changes
good

2022-09-09 13:50 UTC, merged