beginner/audio_data_augmentation_tutorial 번역 (마스터스 B조)
PyTorchKorea/tutorials-kr pull request #581
Opened 2022-08-29 06:02 UTC by bub3690

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #566 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

- https://tutorials.pytorch.kr/beginner/audio_data_augmentation_tutorial.html 한글 번역.
- effects라는 단어를 '효과' 로 번역했는데 조금 어색하다는 느낌이 드네요.
- re-sampling을 '재 샘플링'으로 번역했습니다. 이것도 조금 어색합니다.

2022-09-04 16:27 UTC, bub3690 commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 코덱 적용 후:
오 좋은 발견이네요

2022-09-08 15:58 UTC, hyoyoung requested changes
긴 글 번역하느라 고생하셨습니다

몇가지 제안드립니다

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +끝에서는, 깨끗한 음성으로 부터 휴대폰 너머의 잡음이 낀 음성을 합성하겠습니다.
'끝에서는' 보다는 '하단부에서는'이 조금 더 어울리지 않을까요?
의외로 고민이 되는 지점이네요. 어떻게 생각하시나요?

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 먼저, 모듈을 불러오고 튜토리얼에 사용할 오디오 자료들을 다운합니다.
'다운합니다'는 '받습니다'로 바꾸면 더 자연스러울듯합니다

아니라면 '다운로드합니다'로 바꿔주세요

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 텐서 객체들과 파일 객체 오디오 소스들에 즉각 적용 해줍니다.
directly는 여기서는 즉각보다는 직접이 더 가까울 듯 합니다

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 사용 가능한 효과들의 리스트를 알고싶다면, `the sox
여기서는 효과들의 리스트보다는 효과들의 목록이 더 자연스러울듯 합니다

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +    # 이것은 샘플 레이트만 변경하기에, 이것 후에
'이것'이 중복으로 나옵니다

이 부분은 샘플 레이트만 변경하기에, 여기 이후에는

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 먼저, RIR을 깨끗하게 만들어줘야합니다. 주요한 충격을 추출하고,
impulse는 충격 보다는 그냥 임펄스로 바꾸거나 원 단어를 번역 안해도 좋을듯 합니다

http://terms.tta.or.kr/dictionary/dictionaryView.do?word_seq=089752-1

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 그 후, RIR 필터와 음성 신호를 컨볼루션 합니다.
용어집에있는 convolution은 아니지만 convolve도 비슷한 의미이기에

컨볼루션 합니다보다 합성곱 해줍니다로 바꾸는건 어떨까요?

2022-09-08 15:58 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# :py:func:`torchaudio.functional.apply_codec` 는 텐서 오브젝트에 코댁을 적용합니다.
위에서는 코덱이라고 하였는데 여기서는 코댁으로 되어있습니다 한가지로 통일 부탁드립니다

2022-09-10 03:12 UTC, bub3690 commented on beginner_source/audio_data_augmentation_tutorial.py
> +끝에서는, 깨끗한 음성으로 부터 휴대폰 너머의 잡음이 낀 음성을 합성하겠습니다.
좋은 의견입니다. 저도 어색하다 느꼈는데, 반영하겠습니다.

2022-09-10 03:20 UTC, bub3690 commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 먼저, RIR을 깨끗하게 만들어줘야합니다. 주요한 충격을 추출하고,
저도 도메인이 없다 보니 뭐로 해석이되나 헤깔렸는데, 임펄스라고 적어주는게 좋아보이네요.

2022-09-10 13:29 UTC, hyoyoung requested changes
지난번에 이어 몇가지 수정사항을 제안드립니다

2022-09-10 13:29 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# documentation <http://sox.sourceforge.net/sox.html>`__. 을 참조해주세요.
__뒤에 .은 필요없을것 같습니다

2022-09-10 13:29 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +    # 이 부분은 샘플 레이트만 변경하기에, 이것 후에
이것 후에 보다는 이 후에 가 조금 더 자연스러울듯합니다

2022-09-10 13:29 UTC, hyoyoung commented on beginner_source/audio_data_augmentation_tutorial.py
> +# 전화 코텍 적용하기
코텍은 코덱의 오타인거 같습니다

2022-09-11 15:50 UTC, hyoyoung approved these changes
good

2022-09-11 15:50 UTC, merged