intermediate_source/speech_recognition_pipeline_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #582
Opened 2022-08-29 13:28 UTC by terri1102

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: (#569 )

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
[intermediate_source/speech_recognition_pipeline_tutorial.py](https://github.com/PyTorchKorea/tutorials-kr/blob/master/intermediate_source/speech_recognition_pipeline_tutorial.py)를 번역하였습니다.

line16에 Heading이 깨지는데 원본 문서도 깨져서 그대로 두었습니다. 
혹시 원인을 아시는 분은 코멘트해주세요!

2022-08-30 10:56 UTC, bub3690 commented
looks good to me!
고생하셨습니다.

2022-08-30 10:56 UTC, bub3690 approved these changes
looks good to me!
고생하셨습니다

2022-09-02 15:14 UTC, updaun approved these changes
내용이 많습니다~! 수고하셨습니다! 
lgtm!!

2022-09-05 00:15 UTC, hjvision96 reviewed
잘 번역하신 것 같습니다. 고생하셨습니다!

2022-09-05 00:15 UTC, hjvision96 commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 인터페이스를 제공합니다. 이를 이용해 샘플링 레이트와 클래스 라벨을 확인하겠습니다.
오타인 것 같습니다. 다음과 같이 수정하면 어떨까요?
생성하고(instantiate)하고 -> 생성(instantiate)하고

2022-09-05 01:41 UTC, YunjinJo requested changes
번역 되게 잘하셨네요! 큰 문제는 못찾았고 일부 사소한 문제들만 리뷰 남겼습니다.

2022-09-05 01:41 UTC, YunjinJo commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 반환되는 특성은 tensor의 리스트이고 각 tensor는 transformer 레이어의 출력입니다.
리스트 -> 배열
음차하지 않아도 될 것 같습니다.

2022-09-05 01:41 UTC, YunjinJo commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 관련 정보를 쉽게 제공합니다. 이런 정보들은
관련 정보를 쉽게 제공합니다 -> 관련 정보를 제공합니다
쉽게 제공한다는 말이 어색하기도 하고, 의미 전달에 큰 영향이 없어 번역하지 않아도 될 것 같습니다.

2022-09-05 01:41 UTC, YunjinJo commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# torchaudio에는 사전 학습된 Wav2Vec2 모델 가중치가 두 종류 있습니다.
torchaudio에는 -> Torchaudio에는

2022-09-05 01:41 UTC, YunjinJo commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +#    하지만 이번 튜토리얼에서는 특성 추출을 하는 방법도 설명하겠습니다.
하지만 이번 튜토리얼에서는 -> 하지만 자세한 설명을 위해
for the sake of 의 뜻을 살려서 약간의 의역을 하였습니다. 튜토리얼 단어를 넣은 번역문은 생각이 안나네요.

2022-09-08 16:08 UTC, hyoyoung requested changes
긴 글 번역하느라 수고하셨습니다.

몇가지 제안을 드립니다.

2022-09-08 16:08 UTC, hyoyoung commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 그리디 디코딩 알고리즘을 정의하겠습니다.
greedy는 보통 탐욕적인, 욕심쟁이 등으로 번역하는 듯 합니다

2022-09-08 16:08 UTC, hyoyoung commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 모델을 만들고 emission을 얻는 모든 과정은 아래의 2줄 만으로도 가능합니다.
emission은 산출물로 번역해도 뜻이 통하지 않을까요?

2022-09-09 12:26 UTC, terri1102 commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 반환되는 특성은 tensor의 리스트이고 각 tensor는 transformer 레이어의 출력입니다.
보통 배열은 'array'를 가리켜서 리스트로 음차했는데, 여기서는 리스트 자료형을 의미하지 않아서 '배열'로 써도 될 것 같긴 하네요.

2022-09-09 12:32 UTC, terri1102 commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 다운로드되고 모델에 불러와집니다.
fetch를 '받아서'로 번역하는 것은 좋은 것 같습니다.
load를 어떻게 번역할지 고민했었는데... '가중치를 모델에 넣어줍니다'라고도 하나요?

2022-09-09 12:33 UTC, terri1102 commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +#    하지만 이번 튜토리얼에서는 특성 추출을 하는 방법도 설명하겠습니다.
'하지만 자세한 설명을 위해 이번 튜토리얼에서는'으로 쓰겠습니다.

2022-09-09 13:18 UTC, terri1102 commented on intermediate_source/speech_recognition_pipeline_tutorial.py
> +# 다운로드되고 모델에 불러와집니다.
'이 과정을 통해 사전 학습된 모델의 가중치를 가져와서 모델에 넣어줍니다.'로 수정하였습니다.

2022-09-09 13:52 UTC, hyoyoung approved these changes
good

2022-09-09 13:52 UTC, merged