recipes_source/quantization.rst 번역
PyTorchKorea/tutorials-kr pull request #589
Opened 2022-08-31 12:10 UTC by hjvision96

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #585 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
recipes_source/quantization.rst를 번역하였습니다.

2022-08-31 12:11 UTC, hjvision96 commented on recipes_source/quantization.rst
> +위의 단계 중 하나를 이용해 양자화된 모델이 생성된 후에, 모바일 장치에서 작동되게 하려면 추가로 `TorchScript` 형식으로 전환하고 모바일 app에 최적화를 진행해야 합니다. 자세한 내용은 `Script and Optimize for Mobile recipe <script_optimized.html>`_\를 확인하세요.
`Script and Optimize for Mobile recipe <script_optimized.html>`
 해당 문서가 아직 번역이 안된 상태입니다. Script and Optimize for Mobile recipe 를 제가 번역하여 적어야 할까요?
 이후에 다른 분이 번역을 다르게 하면 충돌이 되나 걱정이 됩니다. 의견 부탁드립니다~!

2022-09-02 15:36 UTC, updaun approved these changes
대체적으로 번역이 매끄럽게 잘 된 것 같습니다. 고생하셨습니다!

2022-09-03 08:05 UTC, terri1102 commented on recipes_source/quantization.rst
> +위의 단계 중 하나를 이용해 양자화된 모델이 생성된 후에, 모바일 장치에서 작동되게 하려면 추가로 `TorchScript` 형식으로 전환하고 모바일 app에 최적화를 진행해야 합니다. 자세한 내용은 `Script and Optimize for Mobile recipe <script_optimized.html>`_\를 확인하세요.
지금처럼 원문 그대로 적으시면 될 것 같습니다~

2022-09-04 12:02 UTC, terri1102 approved these changes
매끄럽게 잘 번역하신 것 같습니다. 수고하셨습니다~

2022-09-05 02:20 UTC, YunjinJo requested changes
수정사항 남겼습니다!

2022-09-05 02:20 UTC, YunjinJo commented on recipes_source/quantization.rst
> +모델을 양자화하는 데는 전부 세 가지의 접근법 및 작업방식이 있습니다. 학습 후 동적 양자화, 학습 후 정적 양자화, 그리고 양자화를 고려한 학습이 있습니다. 하지만 사용하려는 모델이 이미 양자화된 버전이 있다면, 위의 세 가지 방식을 거치지 않고 그 버전을 바로 사용하면 됩니다. 예를 들어, `torchvision` 라이브러리에는 이미 MobileNet
학습 후 동적 양자화, 학습 후 정적 양자화, 그리고 양자화를 고려한 학습이 있습니다. -> 학습 후 동적 양자화(post training dynamic quantization), 학습 후 정적 양자화(post training static quantization), 그리고 양자화를 고려한 학습(quantization aware training)이 있습니다.
번역된 단어만으로는 정확한 의미를 알기 어려울 수 있을 것 같아 괄호 속에 원문을 넣는게 좋을 것 같습니다!

2022-09-05 02:20 UTC, YunjinJo commented on recipes_source/quantization.rst
> +동적 양자화를 적용하면, 모델의 모든 가중치는 32-비트 크기의 실수 자료형에서 8-비트 크기의 정수 자료형으로 전환되지만, 활성화에 대한 계산을 진행하기 직전까지는 활성 함수는 8-비트 정수형으로 전환하지 않게 됩니다. 동적 양자화를 적용하려면, `torch.quantization.quantize_dynamic`\을 사용하면 됩니다.
32비트, 8비트 위와 동일합니다.

2022-09-05 02:20 UTC, YunjinJo commented on recipes_source/quantization.rst
> +.. warning:: 동적 양자화는 사전 학습된 양자화 적용 모델이 준비되지 않았을 때 사용하기 가장 쉬운 방식이지만, 이 방식의 주요 한계는 `qconfig_spec` 옵션이 현재는 `nn.Linear`\과 `nn.LSTM`\만 지원한다는 것입니다. 이는 당신이 `nn.Conv2d`\같은 다른 모듈을 양자화할 때, 나중에 논의될 정적 양자화나 양자화를
백 슬래시는 일부러 넣으신건가요?

2022-09-05 02:20 UTC, YunjinJo commented on recipes_source/quantization.rst
> +이 방식은 모델의 가중치와 활성 함수 모두를 8-비트 크기의 정수 자료형으로 사전에 바꾸기 때문에, 동적 양자화처럼 추론 과정 중에 활성 함수를 전환하지는 않습니다. 따라서 이 방식은 성능이 상당히 높습니다.
8비트, 위와 내용 동일

2022-09-05 10:47 UTC, hjvision96 commented on recipes_source/quantization.rst
> +모델을 양자화하는 데는 전부 세 가지의 접근법 및 작업방식이 있습니다. 학습 후 동적 양자화, 학습 후 정적 양자화, 그리고 양자화를 고려한 학습이 있습니다. 하지만 사용하려는 모델이 이미 양자화된 버전이 있다면, 위의 세 가지 방식을 거치지 않고 그 버전을 바로 사용하면 됩니다. 예를 들어, `torchvision` 라이브러리에는 이미 MobileNet
넵 감사합니다! 첫 언급 이후 아래 계속 언급될 때는 영어를 안적어줘도 괜찮겠죠?

2022-09-05 10:48 UTC, hjvision96 commented on recipes_source/quantization.rst
> +.. warning:: 동적 양자화는 사전 학습된 양자화 적용 모델이 준비되지 않았을 때 사용하기 가장 쉬운 방식이지만, 이 방식의 주요 한계는 `qconfig_spec` 옵션이 현재는 `nn.Linear`\과 `nn.LSTM`\만 지원한다는 것입니다. 이는 당신이 `nn.Conv2d`\같은 다른 모듈을 양자화할 때, 나중에 논의될 정적 양자화나 양자화를
` 표시 다음에 띄어쓰기 없이 한글이 올 때는 백슬래시를 넣어야 make html-noplot 했을 때 오류가 안생기더라구요!
백슬래시를 넣어서 오류를 안생기게 하냐 vs. 그냥 `표시 뒤에 한글이 오면 띄어 쓰냐
중에서 전자를 선택한거긴 한데, 혹시 후자가 맞는걸까요?

2022-09-05 12:46 UTC, YunjinJo commented on recipes_source/quantization.rst
> +모델을 양자화하는 데는 전부 세 가지의 접근법 및 작업방식이 있습니다. 학습 후 동적 양자화, 학습 후 정적 양자화, 그리고 양자화를 고려한 학습이 있습니다. 하지만 사용하려는 모델이 이미 양자화된 버전이 있다면, 위의 세 가지 방식을 거치지 않고 그 버전을 바로 사용하면 됩니다. 예를 들어, `torchvision` 라이브러리에는 이미 MobileNet
첫 언급 이후에는 필요에 따라 적어도 되고 안 적어도 상관없습니다. 다만 제목인 경우에는 적어주는게 좋을 것 같습니다.

2022-09-05 13:04 UTC, YunjinJo commented on recipes_source/quantization.rst
> +.. warning:: 동적 양자화는 사전 학습된 양자화 적용 모델이 준비되지 않았을 때 사용하기 가장 쉬운 방식이지만, 이 방식의 주요 한계는 `qconfig_spec` 옵션이 현재는 `nn.Linear`\과 `nn.LSTM`\만 지원한다는 것입니다. 이는 당신이 `nn.Conv2d`\같은 다른 모듈을 양자화할 때, 나중에 논의될 정적 양자화나 양자화를
백슬래시를 넣어서 이스케이핑 할 수 있지만 대부분의 문서들이 한 칸 띄어쓰기로 적혀 있기에 통일하는게 좋을 것 같습니다.
꼭 붙여야 하는 경우에는 \ 를 여러개 안 쓰고 맨 뒤에 하나만 붙여도 오류 안 뜰겁니다.

2022-09-05 13:56 UTC, hjvision96 commented on recipes_source/quantization.rst
> +모델을 양자화하는 데는 전부 세 가지의 접근법 및 작업방식이 있습니다. 학습 후 동적 양자화, 학습 후 정적 양자화, 그리고 양자화를 고려한 학습이 있습니다. 하지만 사용하려는 모델이 이미 양자화된 버전이 있다면, 위의 세 가지 방식을 거치지 않고 그 버전을 바로 사용하면 됩니다. 예를 들어, `torchvision` 라이브러리에는 이미 MobileNet
넵 의견 정말 감사드립니다!

2022-09-05 13:56 UTC, hjvision96 commented on recipes_source/quantization.rst
> +.. warning:: 동적 양자화는 사전 학습된 양자화 적용 모델이 준비되지 않았을 때 사용하기 가장 쉬운 방식이지만, 이 방식의 주요 한계는 `qconfig_spec` 옵션이 현재는 `nn.Linear`\과 `nn.LSTM`\만 지원한다는 것입니다. 이는 당신이 `nn.Conv2d`\같은 다른 모듈을 양자화할 때, 나중에 논의될 정적 양자화나 양자화를
아하 대부분의 경우 그렇군요 감사합니다!

2022-09-09 13:59 UTC, hyoyoung requested changes
긴 글 번역하느라 수고하셨습니다

몇가지 제안을 드립니다

2022-09-09 13:59 UTC, hyoyoung commented on recipes_source/quantization.rst
> +이 레시피는 Pytorch 모델을 양자화하는 방법을 설명합니다. 양자화된 모델은 원본 모델과 거의 같은 정확도를 내면서, 사이즈가 줄어들고 추론 속도가 빨라집니다. 양자화 작업은 서버 모델과 모바일 모델 배포에 모두 적용될 수 있지만, 모바일 환경에서 특히 중요하고 매우 필요합니다. 그 이유는 양자화를 적용하지 않은 모델의 크기가 IOS나 Android
IOS -> iOS

2022-09-09 13:59 UTC, hyoyoung commented on recipes_source/quantization.rst
> +모델을 양자화하는 데는 전부 세 가지의 접근법 및 작업방식이 있습니다. 학습 후 동적 양자화(post training dynamic quantization), 학습 후 정적 양자화(post training static quantization), 그리고 양자화를 고려한 학습(quantization awqre training)이 있습니다. 하지만 사용하려는
quantization awqre training -> quantization aware training

2022-09-09 13:59 UTC, hyoyoung commented on recipes_source/quantization.rst
> +.. warning:: 동적 양자화는 사전 학습된 양자화 적용 모델이 준비되지 않았을 때 사용하기 가장 쉬운 방식이지만, 이 방식의 주요 한계는 `qconfig_spec` 옵션이 현재는 `nn.Linear` 과 `nn.LSTM` 만 지원한다는 것입니다. 이는 당신이 `nn.Conv2d` 같은 다른 모듈을 양자화할 때, 나중에 논의될 정적 양자화나 양자화를
'당신'은 제거 해도 될듯 합니다

2022-09-09 13:59 UTC, hyoyoung commented on recipes_source/quantization.rst
> +이 방식은 모델의 가중치와 활성 함수 모두를 8비트 크기의 정수 자료형으로 사전에 바꾸기 때문에, 동적 양자화처럼 추론 과정 중에 활성 함수를 전환하지는 않습니다. 따라서 이 방식은 성능이 상당히 높습니다.
성능이 상당히 높다는 얘기는 고성능입니다라고 하거나
성능이 뛰어나다고 하는게 조금 더 읽기 편할 듯 합니다.

2022-09-11 15:52 UTC, hyoyoung approved these changes
good

2022-09-11 15:52 UTC, merged