beginner_source/introyt/tensorboardyt_tutorial.py 번역 (PyTorchKorea#590)
PyTorchKorea/tutorials-kr pull request #592
Opened 2022-09-01 12:52 UTC by yuyeonseung

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #590 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
https://tutorials.pytorch.kr/beginner/introyt/tensorboardyt_tutorial.html 을 번역하였습니다.

2022-09-01 15:37 UTC, bub3690 requested changes
수고하셨습니다!

주로 `` 앞뒤에 스페이스가 없는데, 빌드해보면 문법 인식이 안될 것 같네요.

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 학습을 위한 loss함수와 옵티마이저, 이미지를 분류하기 위한 모델을 정의해보시다 :
정의해보시다 -> 정의해봅시다

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 그러기 위해서는 모델과 샘플 인풋을 인자로 받는``add_graph()``메소드를 호출하세요.
`` 앞 뒤에 띄어쓰기가 필요합니다.

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 열기 위해서:
"위해서" 라는 말이 when으로 잘못 해석된 것 같네요. 위에 문장과 합쳐서
"그러기 위해서는, 텐서 보드를 열 때 모델과 샘플 인풋을 인자로 받는 ~~~. " 이 좋아보입니다.

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# ``add_embedding()``메소드는 데이터를 삼차원에 큰 분산으로 투영하고 3D 차트로 보여줄것입니다.
`` 앞뒤로 띄어쓰기가 필요합니다

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +``conda``로 설치:
`` 뒤 띄어쓰기 필요

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 데이터셋에서 텐서보드로 샘플이미지를 추가하는것으로 시작해 봅시다.:
: 앞에 . 이 붙어있는데,
본문에도 없다면 떼는게 좋아 보이네요

2022-09-01 15:37 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 탠서보드 로그 디렉토리에 아마자데이터 쓰기
아마자 데이터 -> 이미지 데이터
쓰기 -> 출력하기

2022-09-09 14:08 UTC, hyoyoung requested changes
긴 글 번역하느라 수고하셨습니다

다른 분들 제안과 함께 수정을 부탁드립니다

2022-09-09 14:08 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 위에서 TorchVision과 Matplotlib를 사용해 인풋데이터의 미니배치를 보여주기 위한 그리드를 생성하였습니다.
인풋데이터보다는 입력 데이터로 순화하는 것도 좋을듯 합니다

2022-09-09 14:08 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# add_graph() 는 모델을 통해 샘플 인풋을 추적하고, 그래프를 만듬
샘플 인풋 -> 샘플 입력
만듬 -> 만듭니다

2022-09-12 15:01 UTC, gorae17 reviewed
고생하셨습니다!

2022-09-13 04:43 UTC, yuyeonseung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 기본적으로 기록할 디렉터리는 runs이지만 구체적일 수록 좋음
다른 본문 주석들과 다르게 소스코드 내에 주석이어서 '~음/함' 체로 마무리 하였습니다!

2022-09-13 04:48 UTC, yuyeonseung commented
리뷰 확인하고 수정하여 다시 커밋 올렸습니다!

2022-09-13 05:17 UTC, bub3690 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 기본적으로 기록할 디렉터리는 runs이지만 구체적일 수록 좋음
소스코드 내 주석도 "합니다."체가 좋아 보입니다.
찾아보니 다른 파일들도 "음/함"체는 없네요.

2022-09-16 15:18 UTC, hyoyoung commented
마지막 피드백 이후 15일이 지나면 보통 닫게 됩니다.
진행이 많이 된 PR이므로, 마무리 피드백 처리 부탁드리겠습니다

2022-09-16 15:19 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 파이토치와 학습에 필요한 라이브러리
파이토치 모델과 학습에 필요한 라이브러리

2022-09-16 15:19 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 클레스 라벨
클레스 -> 클래스

2022-09-16 15:19 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 기본적으로 기록할 디렉터리는 runs이지만 구체적일 수록 좋음
문체 통일

2022-09-16 15:20 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 다시 이미지의 1 미니배치를 가져오기
1 -> 한번의

2022-09-27 14:18 UTC, yuyeonseung commented
늦어서 죄송합니다 추가 수정 사항도 적용하여 다시 pr 보냈습니다.

2022-10-01 06:03 UTC, hyoyoung commented
다른 분들이 남겨주신 피드백중에 해결 안된 부분이 있습니다
피드백을 한번씩 보시고 수정 부탁드립니다
https://github.com/PyTorchKorea/tutorials-kr/pull/592/files 이 링크로 보시면 됩니다

2022-10-22 08:25 UTC, hyoyoung commented
피드백이 없어서 닫습니다. 필요하신 경우 다시 열어주시기 바랍니다.

2022-10-22 08:25 UTC, closed without merging