Translation
PyTorchKorea/tutorials-kr pull request #594
Opened 2022-09-04 02:07 UTC by kil-jung-keong

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #593 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
finetuning_torchvision_models_tutorials.py를 번역하였습니다.

2022-09-04 03:32 UTC, kimtaehyeong reviewed
전체적으로 잘 번역해주셨습니다.
중간중간 필요한 내용은 리뷰로 남겼습니다.

2022-09-04 03:32 UTC, kimtaehyeong commented on beginner_source/finetuning_torchvision_models_tutorial.py
>  **Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
원저자라고 표현하는게 좋을 것 같습니다

2022-09-04 03:32 UTC, kimtaehyeong commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 학습을 위한 에포크의 개수
개수보다 횟수가 좀 더 표현이 적절해보입니다.

2022-09-04 04:31 UTC, 2kkeullim reviewed
전반적으로 잘 번역된 것 같습니다! 수고하셨습니다

2022-09-04 04:31 UTC, 2kkeullim commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +                # 학습을 진행하고 있을 때만 과거를 추적한다.
추적합니다. 로 바꾸는 게 좋을 것 같습니다.

2022-09-04 06:43 UTC, 95hj commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 네트워크를 재구성하기위하여, 분류기의 선형층을 다음과 같이 재초기화합니다.
'재구성하기 위하여' 띄어쓰기 오류입니다.

2022-09-04 06:43 UTC, 95hj commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 학습과 학인을 위한 데이터로더 생성
'확인' 오타인 것으로 보이며 validation을 평가로 번역하는 것이 더 자연스러울 것 같다는 의견입니다.

2022-09-04 06:43 UTC, 95hj commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 미세조정을 할 때에 이 리스트는 길어야하며 모든 모델의 파라미터들을 포함하고 있어야합니다.
띄어쓰기 오류입니다.

2022-09-04 12:34 UTC, hyoyoung commented
제목에 문서 이름도 넣어주세요 Translation 이라고만 되어있으면 나중에 헷갈리더라고요

2022-09-10 13:30 UTC, hyoyoung requested changes
용어집 PR이 섞여있습니다
분리해서 번역만 제출부탁드립니다

2022-09-16 15:18 UTC, hyoyoung commented
마지막 피드백 이후 15일이 지나면 보통 닫게 됩니다.
진행이 많이 된 PR이므로, 마무리 피드백 처리 부탁드리겠습니다

2022-10-22 08:25 UTC, hyoyoung commented
피드백이 없어서 닫습니다. 필요하신 경우 다시 열어주시기 바랍니다.

2022-10-22 08:25 UTC, closed without merging