translate hyperparameter_tuning_tutorial.py
PyTorchKorea/tutorials-kr pull request #595
Opened 2022-09-04 06:19 UTC by 95hj

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)
#578 
## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
beginner source 폴더의 hyperparameter_tuning_tutorial.py를 번역하였습니다.

2022-09-05 01:33 UTC, kimtaehyeong reviewed
전체적으로 번역 잘 해주셨습니다.
보완해야 할 내용은 리뷰로 남겼습니다.

2022-09-05 01:33 UTC, kimtaehyeong commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 이 예시를 통해 fully connected layers의 계층 크기를 지정할 수 있습니다.
layer의 계층 크기라는 표현보다 layer 크기를 지정할 수 있습니다가 자연스러워 보입니다.

2022-09-05 01:33 UTC, kimtaehyeong commented on beginner_source/hyperparameter_tuning_tutorial.py
>  #
@@ -149,25 +133,23 @@ def forward(self, x): 부분이 빠진것 같습니다.

2022-09-05 01:33 UTC, kimtaehyeong commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 보다싶이, 대부분의 코드는 원본 예제에서 직접 적용되었습니다.
보다시피가 맞는 표현 같습니다.

2022-09-05 07:45 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
>  #
혹시 어떤 부분인지 조금 더 자세히 설명해주실 수 있나요? 원문하고 비교해봤는데 어디가 빠진건지 잘 모르겠습니다

2022-09-05 07:54 UTC, kimtaehyeong reviewed
해당 부분은 착각한 것 같습니다.

2022-09-05 07:54 UTC, kimtaehyeong commented on beginner_source/hyperparameter_tuning_tutorial.py
>  #
아.. 제가 착각한것 같습니다. 죄송합니다;;

2022-09-05 08:42 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 이 예시를 통해 fully connected layers의 계층 크기를 지정할 수 있습니다.
수정 완료했습니다!

2022-09-05 08:42 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 보다싶이, 대부분의 코드는 원본 예제에서 직접 적용되었습니다.
감사합니다 수정 완료입니다:)

2022-09-07 00:23 UTC, kimtaehyeong commented
수고하셨습니다.

2022-09-10 13:41 UTC, hyoyoung requested changes
긴 문서 번역하느라 고생하셨습니다.
전반적으로 읽기 쉽게 작성되어 보기가 편합니다
다만 문서에 자주 나오는 래핑은 감싸기로 순화 가능할듯 보이고
몇가지 수정사항을 부탁드립니다

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 훈련 스크립트를 ``train_cifar(config, checkpoint_dir=None, data_dir=None)`` 함수로 래핑합니다.
래핑합니다는 감싸둡니다로 번역해도 좋을 듯 합니다

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 복원하는 데 사용됩니다. ``data_dir`` 은 데이터를 로드하고 저장하는 디렉토리를 지정하므로,
데이터를 로드하고 저장하는

->

데이터를 읽고 저장하는

이 조금 더 자연스러울듯 합니다

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 따라서 여러 GPU에서 데이터 병렬 훈련을 지원하기 위해 ``nn.DataParallel`` 에서 모델을 래핑할 수 있습니다.
여기서도 래핑을 감싸다로 순화할 수 있을듯합니다

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 이것이 전부입니다! 이제 파이토치 모델의 매개변수를 조정할 수 있습니다.
unix호환 운영체제에서는 (linux포함)
텍스트 파일의 끝에는 newline으로 끝나는걸 권장하고 있습니다
newline캐릭터가 맨 마지막에도 필요합니다

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +하이퍼파라미터 튜닝은 평균적인 모델과 매우 정확한 모델간의 차이를 만들어 낼 수 있습니다.
여기서 average는 평균보다는 보통의 의미에 더 가까울듯합니다

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +`Ray Tune <https://docs.ray.io/en/latest/tune.html>`_ 은 하이퍼파라미터 튜닝을 위해 배포된 업계 표준 도구입니다.
distributed hyperparameter tuning의 번역이 
'하이퍼파라미터 튜닝위해 배포된'인데
'분산 하이퍼파라미터 튜닝'에 더 가깝지 않을까요?

2022-09-10 13:41 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +`Ray' 에서 제공되는 기계학습엔진
분산 기계 학습 엔진이 조금 더 원래 의미에 가까울듯합니다

2022-09-10 21:46 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 훈련 스크립트를 ``train_cifar(config, checkpoint_dir=None, data_dir=None)`` 함수로 래핑합니다.
'감싸둡니다'로 수정하였습니다

2022-09-10 21:46 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 복원하는 데 사용됩니다. ``data_dir`` 은 데이터를 로드하고 저장하는 디렉토리를 지정하므로,
수정 완료했습니다.

2022-09-10 21:47 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 따라서 여러 GPU에서 데이터 병렬 훈련을 지원하기 위해 ``nn.DataParallel`` 에서 모델을 래핑할 수 있습니다.
네 반영했습니다!

2022-09-10 21:51 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# 이것이 전부입니다! 이제 파이토치 모델의 매개변수를 조정할 수 있습니다.
해당 부분 수정했습니다

2022-09-10 21:53 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +하이퍼파라미터 튜닝은 평균적인 모델과 매우 정확한 모델간의 차이를 만들어 낼 수 있습니다.
네 수정하였습니다!

2022-09-10 21:58 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +`Ray' 에서 제공되는 기계학습엔진
수정사항 반영했습니다.

2022-09-10 21:58 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +`Ray' 에서 제공되는 기계학습엔진
제안해주신 내용들 전체적으로 검토 후 반영 완료했습니다:)

2022-09-10 21:59 UTC, 95hj commented on beginner_source/hyperparameter_tuning_tutorial.py
> +`Ray Tune <https://docs.ray.io/en/latest/tune.html>`_ 은 하이퍼파라미터 튜닝을 위해 배포된 업계 표준 도구입니다.
번역하면서도 이상하다 싶었는데 '분산 하이퍼파라미터 튜닝'으로 번역하는 것이 맞는 것 같습니다. 수정사항 반영하였습니다!

2022-09-11 16:06 UTC, hyoyoung requested changes
2가지 사항을 추가로 제안드립니다.

1. 래핑 -> 감싸두기로 순화

2. 시도 -> 실험으로 순화
trial은 보통 시도로 번역합니다만
여기서는 다양한 트레이닝 실험을 해서 정확도를 올리는 방법을 소개하고 있으므로
시도보다는 실험으로 의역하는 것이 조금 더 읽기 편할듯 한데
어떻게 생각하시나요?
trial에는 실제로 실험이라는 뜻도 있긴합니다.
만약 동의하신다면 '시도'는 모두 '실험'으로 변경 부탁드립니다.

https://en.dict.naver.com/#/entry/enko/7e20a8f23bb444d7901351430e98d765

2022-09-11 16:06 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +1. 함수에서 데이터 로딩 및 학습을 래핑하고,
1. 여러 함수들에서 데이터 읽어오기 및 학습 부분을 감싸두고,

정도로 순화하면 어떨까요?

2022-09-11 16:06 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# data loader를 자체 함수로 래핑하고 전역 데이터 디렉토리로 전달합니다.
래핑 -> 감싸두고

2022-09-11 16:06 UTC, hyoyoung commented on beginner_source/hyperparameter_tuning_tutorial.py
> +# Test set 또한 함수로 래핑할 수 있습니다.
래핑할 수 -> 감싸둘 수

2022-09-11 22:37 UTC, 95hj commented
말씀해주신 내용들에 동의합니다. 실험으로 번역하는것이 더 타당해 보입니다. '래핑->감싸다', '시도->실험'으로 수정 완료했습니다!

2022-09-12 00:33 UTC, hyoyoung approved these changes
good

2022-09-12 00:34 UTC, merged