intermediate_source/tensorboard_profiler_tutorial.py 번역 진행
PyTorchKorea/tutorials-kr pull request #761
Opened 2023-09-01 17:37 UTC by dnd-qodqks

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #748 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

아직 번역되지 않은 'intermediate_source/tensorboard_profiler_tutorial.py' 문서를 번역하였습니다.

2023-09-07 11:29 UTC, jiho3004 reviewed
리뷰 진행하였습니다.

2023-09-07 11:29 UTC, jiho3004 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# GPU에서 실행하기 위해 모델 및 손실을 GPU 장지로 이동합니다.
68번 라인의 오타를 수정하면 좋을 것 같습니다.
장지 -> 장치

2023-09-07 11:29 UTC, jiho3004 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# "단계 시간 세분화(Step Time Breakdown)"는 각 단계에서 수행된 시가느이 분포를 보여줍니다.
197번 라인의 오타를 수정하면 좋을 것 같습니다.
시가느이 -> 시간의

2023-09-07 11:29 UTC, jiho3004 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 메모리 보기(memory view)는 다음과 같이 세 가지 구성 요소로 구성됩니다.
325번 라인의 세 가지 구성 요소 -> 세 가지 요소 로 번역하여도 좋을 것 같습니다.

2023-09-07 11:29 UTC, jiho3004 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 예를 들어, 한 작업자의 연산 + 중첨 시간이 다른 작업자보다 훨씬 큰 경우,
379번 라인의 중첨을 수정하면 좋을 것 같습니다. 
overlapping이라는 단어가 377번 라인에서는 '중복'이라는 단어로, 379번 라인에서는 '중첩'이라는 단어로 번역되었는데 하나로 통일하는 것은 어떨까요?

2023-09-07 11:29 UTC, jiho3004 commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# "동기화/통신 개요(Synchronizing/Communication Overview)"는 통신의 효율성을 보여줍니다.
377번 라인에서 Communication을 '커뮤니케이션'으로 작성해 주셨는데, 382번 라인의 Communication이 '통신'으로 번역되어 있어 하나로 통일하면 좋을 것 같습니다. 389번 라인의 Communication도 함께 고려해 주시면 될 것 같습니다.

2023-09-10 02:04 UTC, dnd-qodqks commented
리뷰 감사합니다! 말씀해주신 부분 수정해보았습니다 :)

2023-09-10 03:06 UTC, falconlee236 reviewed
문서 리뷰를 완료했습니다
전체적으로 용어를 한국어로 번역한 것이 있는데, 대부분은 잘 표현한 것 같지만 몇가지가 조금 어색한 것이 있어서 그것만 수정 부탁드렸습니다
긴 문서 번역하느라 고생 많으셨습니다

2023-09-17 07:42 UTC, hyoyoung requested changes
긴문서 번역하느라 고생하셨습니다
전반적으로 잘되어있으나
번역자 이름 넣는 부분이 빠져있습니다
저자가 없어도 번역자는 넣어두니 다른 페이지 참고하셔서 추가 부탁드립니다.
그리고 다른 분들 피드백도 확인후 수정 부탁드립니다.

2023-09-17 07:42 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 예산 달성 점유율(Est. Achieved Occupancy)은 열의 툴팁(column's tooltip)에 정의되어 있습니다.
예산 달성은 바로 윗줄의 예상 달성의 오타인거 같습니다

2023-09-17 07:42 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# - 트레이스 보기(Trace view)
추적 보기로 바꿔도 좋을거 같습니다

2023-09-17 07:42 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# -  `torch.profiler API <https://pytorch.org/docs/master/profiler.html>`_
원본처럼 줄내림에 
<img width="31" alt="스크린샷 2023-09-17 오후 4 40 23" src="https://github.com/PyTorchKorea/tutorials-kr/assets/1062287/e5a98c0b-3263-4966-b5a0-c2f8bda510df">
마크가 없어야합니다. 아마도 윈도에서 저장하신거 같은데 확인부탁드립니다

2023-09-17 07:42 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 이 작업자는 다른 작업자보다 더 많은 계산 작업량을 가질 수 있는 스트래글러일 수 있습니다’.
straggler는 자주 쓰지 않는 표현이니, 한글로 된 순화표현을 찾아보는게 좋을거 같습니다

2023-09-22 16:26 UTC, dnd-qodqks commented
[falconlee236](https://github.com/falconlee236) 말씀해주신 부분 모두 수정했습니다. 피드백해주셔서 감사합니다. :)

2023-09-22 16:27 UTC, dnd-qodqks commented
[hyoyoung](https://github.com/hyoyoung) 피드백 감사합니다! 말씀해주신 부분 모두 수정하였습니다!!

2023-09-24 09:07 UTC, hyoyoung requested changes
번역자 부분을 이름 넣는게 빠져있는거 같습니다

나머지 추가 피드백도 확인 부탁드립니다

2023-09-24 09:07 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 프로파일러는 컨텍스트(context) 관리자를 통해 활성화되고 몇 가지 매개 변수를 사용할 수 있으며,
'매개 변수'는 보통 띄어쓰기 없이 되어있습니다.
다른 부분도, 띄어쓰기 제거 부탁드립니다.

2023-09-24 09:07 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +#   이는 프로파일링 오버헤드(overhead)를 줄이기 위함입니다.
overhead는 딱히 용어집에 없긴한데, 보통 과부하로 번역해도 괜찮을거 같습니다

2023-09-24 09:07 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# - ``profile_memory`` - 트랙 텐서 메모리(Track tensor memory) 할당/할당 해제 여부를 나타냅니다. 주의, 1.10 이전 버전의 파이토치를 사용하는 경우
텐서는 번역하지 않습니다
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2023-09-24 09:07 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 보여줍니다, e.g., tensors. 파이토치에서 캐싱 메커니즘(caching mechanism)은 CUDA 할당기 및 일부 다른 할당기에 사용됩니다.
e.g., tensors 부분이 번역이 안된거 같습니다
예를 들면 텐서 이 정도로 번역하면 좋을거 같습니다

2023-09-25 07:47 UTC, dnd-qodqks commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# - ``profile_memory`` - 트랙 텐서 메모리(Track tensor memory) 할당/할당 해제 여부를 나타냅니다. 주의, 1.10 이전 버전의 파이토치를 사용하는 경우
트랙 텐서 메모리는 번역하지 않고 'Track tensor memory'로 표기하였습니다. 텐서보드도 번역하지 않고 'TensorBoard'로 표기하는게 좋을까요?

2023-09-30 11:59 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다.

사소한 추가 피드백 확인부탁드립니다

2023-09-30 11:59 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 연산 보기(operator view)는 호스트 또는 장치에서 실행되는
위에서 영어 병기가 되어있어서 아래에는 생략해도 될거 같습니다

2023-09-30 11:59 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +#   프로파일링을 시작할 때 오버헤드는 크고 프로파일링 결과에 왜곡을 가져오기 쉽습니다.
위에는 과부하라고 되어있는데, 이 문장에는 오버헤드라고 되어있습니다

2023-09-30 11:59 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +#   프로파일링 후 결과 파일은 ``./log/resnet18`` 디렉토리(directory)에 저장됩니다.
디렉토리는 자주 쓰이므로 영어 병기를 하지 않는게 좋을거 같습니다

2023-09-30 11:59 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 구글 크롬(Google Chrome) 브라우저 또는 마이크로소프트 엣지(Microsoft Edge) 브라우저에서 텐서보드 프로파일(profile) URL을 접속합니다.
'URL을'보다는 'URL에'가 조금 더 자연스럽지 않을까요?

2023-09-30 11:59 UTC, hyoyoung commented on intermediate_source/tensorboard_profiler_tutorial.py
> +# 한 작업자의 "동기화 시간(Synchronizing Time)"이 다른 작업자 보다 훨씬 짧다면’,
위에 병기된 단어에서는 영어 병기가 필요없을거 같습니다

2023-10-05 15:18 UTC, dnd-qodqks commented
추가 피드백 반역하였습니다. 감사합니다 :)

2023-10-08 11:23 UTC, hyoyoung approved these changes
good

2023-10-08 12:27 UTC, dnd-qodqks commented
@hyoyoung 지속적으로 피드백 주셔서 감사합니다 😊

2023-11-26 13:55 UTC, merged