intermediate_source/ensembling.py 번역 진행
PyTorchKorea/tutorials-kr pull request #772
Opened 2023-09-04 15:57 UTC by ChoHyoungSeo

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #755 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
intermediate_source/ensembling.py 파일을 번역했습니다.

2023-09-10 06:00 UTC, khleexv requested changes
https://github.com/PyTorchKorea/tutorials-kr/pull/722 와 같은 상황인 것 같은데, 한 가지 PR에는 한 가지 변경 사항만 있어야 하는 게 원칙이라고 알고 있습니다.
이 PR은 `ensembling.py` 를 번역하는 PR인데, `TRANSLATION_GUIDE.md` 에 변경사항이 있습니다.
`TRANSLATION_GUIDE.md` 파일에 변경사항을 없애주시거나, 새로 PR 올려주시면 좋을 것 같습니다.

2023-09-17 12:49 UTC, hyoyoung requested changes
다른 분들도 말씀해주셨지만 1개의 PR에는 1개의 의미가 담긴 부분만 올려주셔야 됩니다

2가지: 용어번역, 번역PR이 섞여있습니다

수정부탁드립니다

2023-09-17 12:50 UTC, hyoyoung requested changes
피드백 부탁드립니다

2023-09-17 12:50 UTC, hyoyoung commented on intermediate_source/ensembling.py
번역자 부분이 없습니다 다른 문서 참고하셔서 추가 부탁드립니다

2023-10-12 09:40 UTC, ChoHyoungSeo commented on intermediate_source/ensembling.py
네! 감사합니다. 혹시 이전 용어집 PR이 merge 된 이후 다시 번역 PR을 올려도 괜찮을까요??

2023-10-22 13:23 UTC, hyoyoung commented on intermediate_source/ensembling.py
넵 그렇게 하셔도 되는데, 별도 pr 2개로 올려주시는게 더 빨리 진행 됩니다

2023-11-26 14:00 UTC, hyoyoung commented
이전에 피드백 드린대로 용어집 PR은 별도로 제출해주시고
번역 라인의 맨 아래에 불필요한 newline이 삽입되어있습니다
제거후 다시 보내주시기 바랍니다

2023-12-09 14:12 UTC, closed without merging