intermediate_source/scaled_dot_product_attention_tutorial.py 번역 진행
PyTorchKorea/tutorials-kr pull request #773
Opened 2023-09-05 07:56 UTC by khleexv

## 라이선스 동의

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호

- **이슈 번호**: #747 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
현재 번역되지 않은 문서 [intermediate_source/scaled_dot_product_attention_tutorial.py](https://tutorials.pytorch.kr/intermediate/scaled_dot_product_attention_tutorial) 를 번역했습니다.
부담갖지 말고 사소한 의견이어도 남겨주세요 !

2023-09-10 08:45 UTC, 0seob commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 퓨즈드(fused) 구현은 단순한 구현보다 큰 성능 이점을 제공할 수 있습니다.
28번 줄의 Fused와 같이 첫 글자를 대문자로 통일하는 것이 좋아 보입니다.

2023-09-11 02:45 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 퓨즈드(fused) 구현은 단순한 구현보다 큰 성능 이점을 제공할 수 있습니다.
원문 표현이 소문자 `fused` 여서, 원문 표기를 유지한 건데, 다른 분들 의견은 어떠신가요?

2023-09-12 04:14 UTC, falconlee236 reviewed
문서리뷰 완료했습니다!! 다른 사람의 글을 읽어보니까 훨씬 도움이 많이 되는것 같아요
제가 번역할 때 부족한 부분을 많이 확인 할 수 있는 시간이 되었습니다

2023-09-12 04:14 UTC, falconlee236 commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 퓨즈드(fused) 구현은 단순한 구현보다 큰 성능 이점을 제공할 수 있습니다.
저도 일단 원문 표현을 따라가야 한다는 것이 좋은 것 같습니다

2023-09-12 04:56 UTC, khleexv commented
다들 의견 감사합니다 ㅎㅎ

2023-09-17 12:55 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다 몇가지 수정 부탁드립니다

2023-09-17 12:55 UTC, hyoyoung commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +**번역** : `이강희 <https://github.com/khleexv>`_
author도 저자로 번역 부탁드립니다

2023-09-17 12:55 UTC, hyoyoung commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 퓨즈드(Fused) 구현
위에 퓨즈드(Fused)로 되어있으면 뒤에서는 병기 없이 퓨즈드로 하여도 될거 같습니다

2023-09-17 12:55 UTC, hyoyoung commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# memory efficient 구현이 동작하지 않을 수 있습니다.
memory efficient 구현은 메모리 효율적인 구현으로 바꿔쓸수 있을까요?

2023-09-17 14:00 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +**번역** : `이강희 <https://github.com/khleexv>`_
일부 문서에서 `Author` 가 번역이 되어있지 않은 경우가 있는데, 규칙을 정하고 `TRANSLATION_GUIDE.md`에 명시하는 게 좋을 것 같습니다.
- https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html
- https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html

2023-09-17 14:01 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +**번역** : `이강희 <https://github.com/khleexv>`_
우선 수정해두었습니다.

2023-09-17 14:04 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 퓨즈드(Fused) 구현
수정했습니다 👍

2023-09-17 14:05 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# memory efficient 구현이 동작하지 않을 수 있습니다.
본문 상단의 `Memory-Efficient Attention` 논문을 지칭하는 것 같아서 유지해두었는데, 한글로 번역하는 게 괜찮을까요?

2023-09-18 13:56 UTC, hyoyoung approved these changes
추가 피드백 확인 부탁드립니다

2023-09-18 13:56 UTC, hyoyoung commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# memory efficient 구현이 동작하지 않을 수 있습니다.
이거는 제가 맥락파악이 부족했네요. 원래 하신 그대로,두시는게 더 좋겠습니다

2023-09-18 13:56 UTC, hyoyoung commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 높은 수준에서 이 PyTorch 함수는 쿼리(query), 키(key), 값(value) 사이의
At a high level은 높은 수준도 괜찮지만
보통은 고수준이라고 번역하니

고수준에서, 이 PyTorch 함수는 쿼리(query), 키(key), 값(value) 사이의

요렇게 바꿔보는건 어떨까요?

2023-09-18 13:56 UTC, hyoyoung commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 이 함수는 CUDA 텐서 입력을 다음 중 하나의 구현을 사용합니다.
tensor는 번역하지 않습니다

용어집 참고 부탁드립니다
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2023-09-18 14:11 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 높은 수준에서 이 PyTorch 함수는 쿼리(query), 키(key), 값(value) 사이의
"고수준"이 좀 더 이해하기 편한 표현 같습니다. 수정 했습니다 !

2023-09-18 14:12 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 이 함수는 CUDA 텐서 입력을 다음 중 하나의 구현을 사용합니다.
용어집을 제대로 숙지하지 못했네요, tensor 로 다시 복구했습니다.

2023-09-18 14:16 UTC, khleexv commented on intermediate_source/scaled_dot_product_attention_tutorial.py
> +# 퓨즈드(fused) 구현은 단순한 구현보다 큰 성능 이점을 제공할 수 있습니다.
처음 등장하는 26번 라인에서 `퓨즈드(fused)` 로 표기하고, 이후 등장하는 `fused`는 `퓨즈드` 로 번역하는 것으로 하겠습니다.
다른 의견 있으시면 언제든지 남겨주세요 !

2023-11-26 14:01 UTC, merged