prototype_source/torchscript_freezing.py 번역 진행
PyTorchKorea/tutorials-kr pull request #774
Opened 2023-09-05 16:19 UTC by jiho3004

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #749 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
prototype_source/torchscript_freezing.py 튜토리얼을 번역합니다.

2023-09-17 12:58 UTC, hyoyoung requested changes
다른 파일을 지우시면 안됩니다
수정이 필요한 파일에 대해서만 PR 제출 부탁드립니다

2023-09-17 12:58 UTC, hyoyoung commented on prototype_source/torchscript_freezing.py
> +    # 예외 처리 없이는 'conv1' 이라는 이름과 함께 다음을 출력합니다.
'예외 처리 없이는'보다 '예외 처리 없이'로 바꾸면 더 잘 읽힐거 같습니다

2023-09-23 08:06 UTC, jiho3004 commented on prototype_source/torchscript_freezing.py
> +# 동결은 추론 시 모델 최적화를 할 수 있는 유용한 기법이며 TorchScript 워밍업 시간을 크게 줄입니다.
수정하였습니다. 감사합니다.

2023-09-23 08:09 UTC, jiho3004 commented on prototype_source/torchscript_freezing.py
> +    # 예외 처리 없이는 'conv1' 이라는 이름과 함께 다음을 출력합니다.
넵, 새로 PR 제출하였습니다!!([링크](https://github.com/PyTorchKorea/tutorials-kr/pull/788)) 
'예외 처리가 없을 시' 라는 표현은 어떨까요?

2023-09-24 09:08 UTC, hyoyoung commented
https://github.com/PyTorchKorea/tutorials-kr/pull/788/files
새로운 PR이 있으므로, 기존 PR은 닫습니다

2023-09-24 09:08 UTC, closed without merging