finetuning_torchvision_models_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #775
Opened 2023-09-06 07:44 UTC by dudtheheaven

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #770 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
finetuning_torchvision_models_tutorial 문서를 번역하였습니다.

2023-09-10 04:54 UTC, khleexv requested changes
초반에 사소한 실수가 있어서 코멘트 몇 개 남겨드렸습니다.
확인 부탁드려요!

2023-09-10 04:54 UTC, khleexv commented on beginner_source/finetuning_torchvision_models_tutorial.py
>  Finetuning Torchvision Models
한글 제목과 영문 제목이 같이 있는데 영문을 지워야 할 것 같아요.

2023-09-10 04:54 UTC, khleexv commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +
제목 라인과 `=====` 라인 사이에 빈 라인이 있는데, 지워주셔야 할 것 같습니다.

2023-09-10 04:54 UTC, khleexv commented on beginner_source/finetuning_torchvision_models_tutorial.py
> -**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
Author는 남겨둬야하지 않을까요 !!...

2023-09-10 04:58 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> -**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
수정 완료했습니다!
리뷰 감사합니다 😀

2023-09-10 05:54 UTC, khleexv commented on beginner_source/finetuning_torchvision_models_tutorial.py
> -**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
앗,,, 제 의도는 다음처럼 `Author`, `번역자`가 모두 표시될 수 있도록 다음처럼 수정하라는 것이었습니다.

```
**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
**번역**: `송채영 <https://github.com/dudtheheaven>`__
```

2023-09-11 00:34 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> -**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
넵 반영하여 수정하겠습니다!

2023-09-17 13:03 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다

몇가지수정 부탁드립니다

2023-09-17 13:03 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
>  # ----------------
소문단 제목이 길어질 경우 ---도 같이 길어져야합니다

2023-09-17 13:03 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +        # 기본 네트워크(primary net) 처리
primary는 기본보다는 주 네트워크로 하는건 어떨까요?

2023-09-17 13:03 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 데이터 로드
데이터 로드는 데이터 읽어들이기로 순화 가능할거 같습니다

2023-09-18 00:33 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 데이터 로드
네 수정 사항 반영해보겠습니다. 리뷰 감사합니다! 😀

2023-09-18 00:33 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> -**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
네 알겠습니다!

2023-09-18 13:57 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> -**Author:** `Nathan Inkawhich <https://github.com/inkawhich>`__
번역은 잘 추가되었는데, 저자 부분이 빠진거 같습니다 확인부탁드립니다

2023-09-18 14:00 UTC, hyoyoung approved these changes
추가 피드백 확인 부탁드립니다

2023-09-18 14:00 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 사전 학습된 CNN을 고정된 특징 추출기(classifier)로 사용하고
특징 추출기(classifier)가 아니라
특징 추출기(feature-extractor)가 아닐까요?
맞는지 확인 부탁드립니다

2023-09-18 14:00 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# `여기 <https://ruder.io/transfer-lea를 재구성합니다.
ruder.io 관련 링크가 닫힘이 제대로 안된거 같습니다

2023-09-19 10:25 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# `여기 <https://ruder.io/transfer-lea를 재구성합니다.
윗 피드백 모두 수정 완료 하였습니다.
꼼꼼한 리뷰 감사합니다! 😁

2023-09-24 12:25 UTC, hyoyoung requested changes
추가 피드백 처리 부탁드립니다

2023-09-24 12:25 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 모델 매개변수의 .requires_grad 속성 설
속성 설은 속성 설정의 오타인거 같습니다.
확인 부탁드립니다

2023-09-24 12:25 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 이 절차는 자동(automatic) 절차가 아니며 각 모델마다 고유합니다.
자동은 흔히 쓰이는 말이므로 영어 병기가 필요 없을 것 같습니다

2023-09-24 12:25 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# Large-Scale Image Recognition <https://arxiv.org/pdf/1409.1556.pdf>`__. 논문에서 소개되었습니다.
문장 마침표가 . 2개 입니다 중간에는 필요없을거 같습니다

2023-09-24 12:25 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 1x1 컨볼루션 레이어에서 나옵니다:
컨볼류션은 보통 합성곱으로 표시하고 있습니다
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2023-09-29 10:10 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 1x1 컨볼루션 레이어에서 나옵니다:
참고하여 번역 수정하였습니다!
리뷰 늘 감사합니다 😀

2023-09-30 12:22 UTC, hyoyoung requested changes
추가 피드백 확인 부탁드립니다

2023-09-30 12:22 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 분류기(classifier)의 6번 째 레이어에서 나오는 것을 볼 수 있습니다.
'6번 째' 사이에 불필요한 공백이 있는거 같습니다

2023-09-30 12:22 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 방금 인스턴스화한 모델 프린트
프린트는 출력이 더 자연스러울거 같습니다

2023-09-30 12:22 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
>  # ---------
소제목이 길어졌으므로 ---도 길어져야할거 같습니다

2023-09-30 12:22 UTC, hyoyoung commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 이를 확인하려면 프린트된 매개변수를 확인하여 학습하세요.
프린트->출력

2023-09-30 13:23 UTC, dudtheheaven commented on beginner_source/finetuning_torchvision_models_tutorial.py
> +# 이를 확인하려면 프린트된 매개변수를 확인하여 학습하세요.
피드백 주신 부분 모두 반영하여 수정하였습니다!
확인 부탁드립니다 ㅎㅎ

2023-10-08 11:27 UTC, hyoyoung approved these changes
good

2023-11-26 14:07 UTC, merged