beginner_source/flava_finetuning_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #778
Opened 2023-09-07 14:35 UTC by chanmuzi

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #776
## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
Multimodality의 flava_finetuning_tutorial을 한글로 번역합니다.

2023-09-10 05:21 UTC, khleexv requested changes
초반부에 문법 오류가 조금 있는데, 수정 부탁드립니다.

2023-09-10 05:21 UTC, khleexv commented on beginner_source/flava_finetuning_tutorial.py
> +# TorchMultimodal 라이브러리에서 사용하여 멀티 모달 작업인 시각적 질의 응답**(VQA)에 미세조정하는 방법을 보여 드리겠습니다.
`reStructuredText` 문법 오류 있습니다. 14번 라인 앞 부분에 `**` 추가해주셔야 합니다.
그리고 13번 라인 마지막 `**` 뒤에 조사 `를` 앞에 공백 추가되야할 것 같습니다.

2023-09-10 05:21 UTC, khleexv commented on beginner_source/flava_finetuning_tutorial.py
> +# **번역:** `김찬 <https://github.com/chanmzui>`_
렌더링이 제대로 안 되는데, 원인을 모르겠네요.
한번 해결해보시면 좋을 것 같아요.

![image](https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/5c610cc0-64e2-41c9-a10b-1f4734222e3a)

2023-09-10 12:51 UTC, chanmuzi commented on beginner_source/flava_finetuning_tutorial.py
> +# **번역:** `김찬 <https://github.com/chanmzui>`_
말씀해주신 부분들과 여러 오류들 확인하여 수정했습니다!

2023-09-17 13:06 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다 몇가지 수정사항 부탁드립니다

2023-09-17 13:06 UTC, hyoyoung commented on beginner_source/flava_finetuning_tutorial.py
> +# 멀티 모달 AI는 최근에 이미지 캡셔닝, 시각적 검색부터 텍스트로부터 이미지를 생성같은
이미지 캡셔닝은 이미지 자막추가 정도로 순화해보면 어떨까요?

2023-09-17 13:06 UTC, hyoyoung commented on beginner_source/flava_finetuning_tutorial.py
> +# 본 튜토리얼에서는 **사전 훈련된 SoTA 모델인** `FLAVA <https://arxiv.org/pdf/2112.04482.pdf>`__ **를**
해당 문장 뒤에 불필요한 **가 붙어있는거 같습니다

2023-09-18 14:07 UTC, chanmuzi commented on beginner_source/flava_finetuning_tutorial.py
> +# 멀티 모달 AI는 최근에 이미지 캡셔닝, 시각적 검색부터 텍스트로부터 이미지를 생성같은
이미지 자막추가로 수정했습니다!

2023-09-18 14:11 UTC, chanmuzi commented on beginner_source/flava_finetuning_tutorial.py
> +# 본 튜토리얼에서는 **사전 훈련된 SoTA 모델인** `FLAVA <https://arxiv.org/pdf/2112.04482.pdf>`__ **를**
<img width="740" alt="image" src="https://github.com/PyTorchKorea/tutorials-kr/assets/101971295/96de325b-4f25-4933-b715-beaf66b759f2">

---  
`**를**` 의 `**`를 제거하게 되면, 이미지에 나타난 bold 텍스트 중에서 '를'만 제외되기 때문에 어색할 것이라고 생각했는데요..!
다음 문장에서도 bold 텍스트가 이어지기 때문에 일부러 그렇게 한 것인데, 그래도 제외하는 것이 좋을까요?

2024-01-28 08:34 UTC, hyoyoung commented on beginner_source/flava_finetuning_tutorial.py
> +# 본 튜토리얼에서는 **사전 훈련된 SoTA 모델인** `FLAVA <https://arxiv.org/pdf/2112.04482.pdf>`__ **를**
그런 경우라면 제거하지 않는게 좋을것 같습니다.

2024-01-28 08:36 UTC, hyoyoung approved these changes
good

2024-05-12 12:31 UTC, merged