recipes_source/recipes/reasoning_about_shapes.py 번역
PyTorchKorea/tutorials-kr pull request #779
Opened 2023-09-07 14:46 UTC by 0seob

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #754 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
recipes의 reasoning_about_shapes.py를 한글로 번역하였습니다.

2023-09-08 11:38 UTC, khleexv approved these changes
Meta device가 있다는 걸 처음 알았네요.
고생하셨습니다 !

2023-09-17 13:15 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다

몇가지 피드백 부탁드립니다

2023-09-17 13:15 UTC, hyoyoung commented on recipes_source/recipes/reasoning_about_shapes.py
> +`이영섭 <https://github.com/0seob>`_
번역과 이름은 한줄에 붙여서 써주시기 바랍니다

2023-09-17 13:15 UTC, hyoyoung commented on recipes_source/recipes/reasoning_about_shapes.py
> +# torch.device context manager(with 구문) 내부에서 생성된 모든 텐서는
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md
일반적으로 텐서는 tensor로 번역을 하지않고 두기로 하고 있습니다

2023-09-19 11:27 UTC, 0seob commented on recipes_source/recipes/reasoning_about_shapes.py
> +`이영섭 <https://github.com/0seob>`_
수정하였습니다!!

2023-09-19 11:27 UTC, 0seob commented on recipes_source/recipes/reasoning_about_shapes.py
> +# torch.device context manager(with 구문) 내부에서 생성된 모든 텐서는
수정하였습니다!!

2023-09-24 12:26 UTC, hyoyoung approved these changes
good

2023-09-30 12:23 UTC, hyoyoung approved these changes
good

2023-11-26 14:08 UTC, merged