beginner_source/nlp/sequence_models_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #780
Opened 2023-09-08 04:05 UTC by convin305

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #745 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [x] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
beginner_source/nlp/sequence_models_tutorial.py 파일을 번역하였습니다.

2023-09-11 00:15 UTC, convin305 commented on beginner_source/nlp/sequence_models_tutorial.py
> +시퀀스 모델의 고전적인 예는 부분 음성 태깅을 위한 히든 마르코프 모델입니다.
부분 음성 태깅 -> 품사 태깅으로 수정 예정

2023-09-17 13:22 UTC, hyoyoung requested changes
긴문서 번역하느라 수고하셨습니다

몇가지 피드백 부탁드립니다

2023-09-17 13:22 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +Pytorch에서의 LSTM은 모든 입력이 3D 텐서 일 것으로 예상합니다.
보통 tensor는 번역하지 않고 있습니다
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2023-09-17 13:22 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +        # 1단계, Pytorch는 변화도(gradients)를 축적한다는 것을 기억하세요.
용어집에 있는 단어라면 영어 병기가 빠져도 좋을거 같습니다

2023-09-17 13:22 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +        # 2단계, 네트워크에 맞게 인풋을 준비시킵니다.
인풋은 입력으로 순화시킬수 있을거 같습니다

2023-09-24 12:29 UTC, hyoyoung requested changes
전반적으로 잘되어있는데 몇가지 추가 피드백 확인 부탁드립니다

2023-09-24 12:29 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +시퀀스 모델은 NLP의 핵심입니다 : 이는 입력 간에 일종의 시간적 종속성이 존재하는 모델입니다.
한국어 문법에는 : 표현을 잘 쓰지 않습니다 두 문장으로 분리해도 좋을듯합니다

2023-09-24 12:29 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +예를 들면, 출력은 다음 입력의 일부로 사용될 수 있어
문장 구조가 복잡하므로 2문장으로 나눠도 좋을듯합니다

2023-09-24 12:29 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +# 비터비(Viterbi)나 정방향-역방향(Forward-Backward) 같은 것들은 사용하지 않을 것입니다.
보통 forward는 순방향으로 번역하고 있습니다

2023-09-24 12:29 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +        if word not in word_to_ix:  # word는 아직 인덱스가 할당되지 않았습니다
인덱스는 여기서는 번호로 순화해도 좋을듯합니다

2023-09-24 12:29 UTC, hyoyoung commented on beginner_source/nlp/sequence_models_tutorial.py
> +for epoch in range(300):  # 다시 말하지만, 일반적으로 300에폭을 수행하지는 않습니다. 이건 토이 데이터이기 때문입니다.
toy data는 장난감 데이터나 , 예제 데이터로 순화가능할거 같습니다

2023-09-30 12:27 UTC, hyoyoung approved these changes
good

2023-11-26 14:09 UTC, merged