beginner_source/introyt /captumyt.py 번역
PyTorchKorea/tutorials-kr pull request #781
Opened 2023-09-08 10:38 UTC by diligejy

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #750 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

번역되지 않았던 captum 튜토리얼을 번역하였습니다.

2023-09-09 12:08 UTC, khleexv requested changes
번역 리뷰 전에 코멘트 몇 개 남겨뒀는데, 참고하셔서 `reStructuredText` 문법 오류 수정 부탁드립니다.

2023-09-09 12:11 UTC, khleexv commented on beginner_source/introyt/captumyt.py
> +- **특징 속성(Feature Attribution)**는 특정 출력물을 생성한 입력물의 특징적인 측면에서 설명하고자 하며
렌더링 깨진 예시입니다.
<img width="649" alt="chrome_Fly6NeG1q3" src="https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/e33c096e-1b4f-4886-9128-9a0652b96301">
<img width="641" alt="chrome_bngFnWICLs" src="https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/6162584e-9376-41db-a3f6-01e6ebaaf56f">

2023-09-18 14:06 UTC, hyoyoung requested changes
긴 문서 번역하느라 수고하셨습니다

몇가지 수정사항이 있는데 확인 부탁드립니다

2023-09-18 14:06 UTC, hyoyoung commented on beginner_source/introyt/captumyt.py
> +Captum은 통합된 그레디언트(Integrated Gradients)를 포함한 최신 알고리즘을 제공하여 연구자와 개발자에게 어떤 기능이 모델의 출력에 속성하고 있는지 쉽게 파악할 수 있는 방법을 제공합니다.
여기서 feature는 속성하다기보다
모델이나 네트워크가 찾아낸 feature를 의미하므로 특징으로 바꾸는건 어떨까요?

2023-09-18 14:06 UTC, hyoyoung commented on beginner_source/introyt/captumyt.py
> +    **폐색(Occlusion),** **특징 절제(Feature Ablation),** and **기능 순환(Feature Permutation)**은 모두 퍼터베이션 기반 알고리즘입니다.
vision에서는 occlusion을 가려짐으로 번역 가능할거 같습니다

2023-09-18 14:06 UTC, hyoyoung commented on beginner_source/introyt/captumyt.py
> +# 우리는 학습을 시키지 않았기 때문에 일단 평가모드를 사용하겠습니다.
강조의 의미가 아닌경우 주어는 생략하면 좋을거 같습니다

2023-09-18 14:06 UTC, hyoyoung commented on beginner_source/introyt/captumyt.py
> +input_img = input_img.unsqueeze(0) # 모형에 더미 배치 차원(dimension)이 필요함
문장의 종결은 위에서는 평서문으로 하였으므로, 필요합니다 정도로 바꾸는건 어떨까요?

2023-09-18 14:06 UTC, hyoyoung commented on beginner_source/introyt/captumyt.py
> +#
필요하지 않는 # 라인은 추가하지 않는게 좋을거 같습니다

2024-05-12 12:33 UTC, closed without merging

2024-05-12 12:33 UTC, hyoyoung commented
2주 이상 피드백이 없어서 닫습니다 필요하면 다시 열어주시기 바랍니다