forced_alignment_with_torchaudio_tutorial 번역
PyTorchKorea/tutorials-kr pull request #782
Opened 2023-09-08 17:07 UTC by kimgyujin

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #753 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
https://tutorials.pytorch.kr/intermediate/forced_alignment_with_torchaudio_tutorial.html를 번역했습니다.
다만, 현재 레파지토리에 있는 코드는 단순히 리다이렉트 해주는 코드이기 때문에 
리다이렉트 되는 https://pytorch.org/audio/stable/tutorials/forced_alignment_tutorial.html의 코드를 가져와서 추가한 후 이를 번역했습니다.
따라서, intermediate_source/forced_alignment_with_torchaudio_tutorial.py가 새롭게 추가가 됩니다.

2023-09-18 14:17 UTC, hyoyoung requested changes
긴 문서 번역하느라 고생하셨습니다.
전반적으로 잘되어있으나 몇가지 수정이 필요할거 같습니다
확인 부탁드립니다

2023-09-18 14:17 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +**Author**: `Moto Hira <moto@meta.com>`__
저자와 번역자 정보를 다른 페이지 참고해서 추가 부탁드립니다

2023-09-18 14:17 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +이번 튜토리얼에서는 `CTC-Segmentation of Large Corpora for German End-to-end Speech Recognition <https://arxiv.org/abs/2007.09127>`__ 에서 설명한 CTC 분할 알고리즘을 이용하여 torchaudio를 가지고 정답 스크립트를 음성에 맞추는 방법에 대해 설명합니다.
문장 길이가 길어보이므로 적절히 줄내림을 추가 부탁드립니다

2023-09-18 14:17 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +   사용법에 대한 자세한 내용은 다국적 데이터를 위한 강제 정렬을 설명하는 `Forced alignment for multilingual data <forced_alignment_for_multilingual_data_tutorial.html>`__ 를 참조하세요.
다국적 데이터보다는 보통 다국어 데이터로 많이 사용하니 바꾸는건 어떨까요?

2023-09-18 14:17 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +# 1. 오디오로부터 프레임별 라벨 확률을 추정한다.
오디오보다는 오디오 웨이브폼을 명시해주는건 어떨까요?

2023-09-18 14:18 UTC, hyoyoung commented
리뷰 참조용 링크 : https://github.com/pytorch/audio/blob/main/examples/tutorials/forced_alignment_tutorial.py

2023-09-26 01:49 UTC, kimgyujin commented
> 긴 문서 번역하느라 고생하셨습니다. 전반적으로 잘되어있으나 몇가지 수정이 필요할거 같습니다 확인 부탁드립니다

피드백 감사합니다! 피드백 주신 거 반영해서 수정하도록 하겠습니다!

2023-09-29 07:50 UTC, kimgyujin commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +# 1. 오디오로부터 프레임별 라벨 확률을 추정한다.
https://tutorials.pytorch.kr/recipes/recipes/loading_data_recipe.html 여길 보니깐 waveform을 파형이라고 번역을 했는데 오디오 파형이라고 하는 게 좋을 거 같은데 어떠실까요?

2023-09-30 12:27 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +# 1. 오디오로부터 프레임별 라벨 확률을 추정한다.
제가 얘기한 단어보다 더 좋은 제안인거 같습니다

2023-09-30 12:35 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다

사소한 추가 피드백 확인 부탁드립니다

2023-10-06 05:34 UTC, kimgyujin commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +# 단어와 함께 분할을 병합
넵! 제가 번역한 건 지금 보니 너무 어색하고 이상하네요...
phoneme을 발성한 구간을 합쳐서 한 단어를 발성한 구간으로 만들어가는 과정이기 때문에 '여러 분할을 단어로 병합'이 자연스러운 표현이 맞습니다. 오늘 밤에 수정하도록 하겠습니다. 피드백 감사합니다

2023-10-06 05:35 UTC, kimgyujin commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +#
529번째 줄 말씀하시는 걸로 이해했는데 맞을까요??

2023-10-08 09:34 UTC, kimgyujin commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +#
531번째 줄 말씀하신거였군요. 수정하도록 하겠습니다

2023-10-08 11:21 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +# 이번 튜토리얼에서, torchaudio의 wav2vec2 모델을 사용하여 강제 정렬을 위한 CTC 분할을 수행하는 방법을 살펴보았습니다.
해당 줄에서 newline이 아직 포함되어있습니다 수정 부탁드립니다

2023-10-15 11:16 UTC, kimgyujin commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> +# 이번 튜토리얼에서, torchaudio의 wav2vec2 모델을 사용하여 강제 정렬을 위한 CTC 분할을 수행하는 방법을 살펴보았습니다.
많이 늦어서 죄송합니다. 해당 이슈 처리했습니다

2023-10-22 13:25 UTC, hyoyoung requested changes
한가지 추가 수정 부탁드립니다

2023-10-22 13:25 UTC, hyoyoung commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> + **번역**: `김규진 <http://github.com/kimgyujin/>`_
번역 앞에 공백이 있고 author는 저자로 번역하는게 더 좋을거 같습니다

2023-11-11 03:53 UTC, kimgyujin commented on intermediate_source/forced_alignment_with_torchaudio_tutorial.py
> + **번역**: `김규진 <http://github.com/kimgyujin/>`_
수정 반영 했습니다. 피드백 감사합니다. [6d3fa96](https://github.com/PyTorchKorea/tutorials-kr/pull/782/commits/6d3fa96005c5cd24ab37f77b49ef51e9f7f89035)

2023-11-26 14:11 UTC, hyoyoung approved these changes
good

2024-01-28 08:11 UTC, merged