feat: translate fx profiling tutorial #767
PyTorchKorea/tutorials-kr pull request #787
Opened 2023-09-16 07:04 UTC by Ssunbell

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #767 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [x] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_intermediate_source/fx_profiling_tutorial.py 한글 번역_

2023-09-16 07:06 UTC, Ssunbell commented
@hyoyoung #769 에서 특정 커밋을 삭제해달라는 요청이 있으셔서
새롭게 pr을 드립니다. 이전 pr은 이 pr이 accept되면 삭제할 예정입니다.

2023-09-17 03:28 UTC, khleexv commented
권한 없으시면, 이미 제출한 PR이 삭제가 되는지 모르겠네요.
삭제할 예정이시라면, 용어 PR도 따로 올리시고, 기존 #769 PR은 지금 닫아둬도 괜찮을 것 같습니다.

2023-09-17 07:44 UTC, khleexv requested changes
문서 전반적으로 backtick 뒤에 띄어쓰기를 빠뜨리신 경우가 많습니다.
빌드해보시면 렌더링이 제대로 안됩니다 ㅠㅠ
이 부분 수정 부탁드립니다.

### 원문
<img width="640" alt="chrome_YePTwTzzBG" src="https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/6445fadc-b455-4cc6-833d-949cfb3b8c68">

### 현재 PR 올려주신 브랜치 빌드 결과
<img width="633" alt="chrome_HF8UBpoabl" src="https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/2abb41a3-e98b-4b7e-bfcc-58eb80ef8bc4">

---

그리고 추가적으로, `Symbol` 을 `상징`, `기호` 중 어느 것으로 번역할지 정하셔서 일관성 있게 번역해주시면 좋을 것 같습니다.

2023-09-17 07:44 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
불필요한 공백인 것 같습니다.

2023-09-17 07:44 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +1) 코드의 구조와 실행에 대한 통계를 조사하고 수집할 수 있는 방식으로 파이토치 파이썬 코드를 포착합니다.
`포착한다` 는 표현이 조금 어색한 것 같은데, 다른 번역 생각해보시는 게 어떨까요?
의역도 괜찮을 것 같습니다.

2023-09-17 07:44 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +#     ``tabulate``는 파이토치에 종속성이 없는 외부 라이브러리입니다.
backtick 문자 뒤에 띄어쓰기 추가해주셔야 합니다!
렌더링이 제대로 안됩니다.

2023-09-17 07:44 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +# 엣지(각 노드에서 "args" 및 "kwargs"로 표시됨)는
backtick 을 큰따옴표로 수정한 이유가 있을까요?

2023-09-18 12:32 UTC, khleexv requested changes
문서 읽어보면서 늘 새로운 것 배워가는 것 같습니다.
번역에는 문제 없는 것 같습니다. 수고하셨습니다 !

몇 가지 간단한 피드백 남겨드렸습니다.

2023-09-18 12:32 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +        # 1. "mod"의 총 실행 시간 목록. 즉, 인터프리터가 호출될
backtick 을 큰따옴표로 수정하신 이유가 있을까요?

2023-09-18 12:32 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +#       Python의 "time.time" 함수를 사용하여 벽시계의 타임스탬프를
여기도 backtick이 큰따옴표로 바뀌어서 렌더링이 잘 되지 않습니다.

2023-09-18 12:32 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +#   <https://tutorials.pytorch.kr/intermediate/fx_conv_bn_fuser.html>`_.
줄 앞에 backtick이 빠진 것 같습니다.

2023-09-18 14:28 UTC, hyoyoung requested changes
긴문서 번역하느라 수고하셨습니다
몇가지 수정사항이 필요합니다
확인 부탁드립니다

2023-09-18 14:28 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 이 "장치(instrumentation)" 프로세스를 자동화할 것입니다.
instrumentation은 디버거나 컴파일러 관련 정보에서는 계측으로 보통 번역됩니다

https://learn.microsoft.com/ko-kr/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs

장치보다는 계측이 더 나을거 같습니다

2023-09-18 14:28 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +#     당신이 선호하는 파이썬 패키지 소스로부터 tabulate를 설치해주시길 바랍니다.
주어는 강조의 의미가 아니면 생략해도 좋을거 같습니다

2023-09-30 12:39 UTC, hyoyoung requested changes
backtick과 사소한 추가 피드백 확인 부탁드립니다

2023-09-30 12:39 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 상징적 추적(Symbolic Tracing)을 이용하여 모델 포착하기
symbolic을 여기서 상징적이라고 하면 약간 어색한거 같습니다 
보통 번역하지 않거나,
기호 라고 번역하는거 같습니다
https://kr.mathworks.com/help/symbolic/performing-symbolic-computations.html

2023-09-30 12:39 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +        # 1. "mod"의 총 실행 시간 목록. 즉, 인터프리터가 호출될
여기 다른분 피드백 확인부탁드립니다

2023-09-30 12:39 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 여러분들이 생각하시는 어떤 피드백이라도 제보해주시길 바랍니다.
불필요한 newline이 포함되어있습니다

2023-10-05 13:05 UTC, hyoyoung requested changes
아직 수정이 덜된 부분이 남아있습니다
newline, backtick과 오타 수정 부탁드립니다

2023-10-05 13:05 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 다음으로, FX의 Symbolic Tracing 메커니증을 활용하여 우리가 조작하고
메커니증은 오타인거 같습니다

2023-10-05 13:05 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +#   <https://tutorials.pytorch.kr/intermediate/fx_conv_bn_fuser.html>`_.
FX 튜토리얼 앞에 backtick이 빠진거 같습니다

2023-10-08 11:28 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 여러분들이 생각하시는 어떤 피드백이라도 제보해주시길 바랍니다.
요거 에디터 설정 마다 다르게 될수 있으니 vscode같은걸로도 확인 부탁드립니다

2023-10-09 14:37 UTC, khleexv commented
해결된 Feedback들은 보기 편하게 Resolved 상태로 변경해두는 게 좋을 것 같습니다.

2023-10-09 14:47 UTC, khleexv commented on intermediate_source/fx_profiling_tutorial.py
> +# 여러분들이 생각하시는 어떤 피드백이라도 제보해주시길 바랍니다.
다음 사진 PR 올려주신 파일 내용의 끝 부분을 hexdump 로 살펴본 것입니다.
<img width="705" alt="WindowsTerminal_SfiOXEiULg" src="https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/4b284880-96df-4469-9475-f9681b258512">

파일의 마지막 문자가 16진수 `2e` (문자 `.`) 으로 되어있습니다.
아마 에디터 마지막에 줄 하나를 추가하고 저장하시면, 다음처럼 16진수 `0a` (문자 `'\n'`) 문자가 추가되면서 문제가 해결될 것 같습니다.
<img width="702" alt="WindowsTerminal_zzyk9jzdPl" src="https://github.com/PyTorchKorea/tutorials-kr/assets/30896956/251b0337-8974-4ad9-85fc-5b686960232c">

2023-10-18 02:13 UTC, Ssunbell commented
@khleexv @hyoyoung 확인 부탁드립니다

2023-10-22 13:30 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +    # 다음으로, 우리의 첫 번째 매서드인 ``run()`` 을 덮여 씌웁니다. ``Interpreter`` 의 ``run``
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md
method는 용어집에서 ( https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md )
메소드 로 표기하고 있습니다.

2023-10-22 13:30 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 피드백도 기꺼이 귀기울일 것입니다. 파이토치 포럼(https://discuss.pytorch.org/)
'여러분이 것을 사용해보시면서 어떤 피드백도 기꺼이 귀기울일 것입니다'

위 문장은 괜찮긴한데 약간 어색해보입니다.

마지막으로, FX는 여전히 베타 버전이기 때문에, 사용에 관련된 어떤 피드백도 기꺼이 귀기울일 것입니다.

이 정도가 더 자연스럽지 않을까 싶습니다. 이건 단순히 제안이니 확인해보시고 피드백 부탁드립니다

2024-01-28 08:17 UTC, hyoyoung commented
@Ssunbell PR 화면에서 오른쪽 위에 'Reviewers'보시면 지난번에 리뷰한 사람들이 있습니다
여기 이름 옆에 화살표 2개가 서로 회전하는 모습처럼 되어있는데, 이게 're-request review'입니다
이걸 수정후에 한번 눌러주시면 리뷰 필요한 PR볼때 더 편리해서 좋을거 같습니다.
다음부터 request changes가 생기면 re-request review 버튼 눌러주시길 부탁드립니다.

2024-01-28 08:26 UTC, hyoyoung requested changes
몇가지 추가 부분 확인 부탁드립니다

2024-01-28 08:26 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 즉, 다음 호출에 대해서, 모델의 어떤 부분이 가장 오래 걸립니까?
'That is'는 아마도 이전 문장의 'inspect deeper'를 지칭하는 뜻일거 같습니다.
그렇다면 '즉'보다는 '그거라면'과 비슷할텐데.
'즉'이나 '그거라면' 둘중 어떤걸 넣어도 어색하니까 차라리 아예 빼서

'다음 호출에 대해서, 모델의 어떤 부분이 가장 오래 걸립니까?'
이렇게 바꿔보는건 어떨까요?

2024-01-28 08:26 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +#
불필요한 공백이 한줄 추가 되었습니다

2024-01-28 08:26 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 조사할 수 있는 자료구조에서 우리 모델의 정의를 포착할 것입니다.
여기도 '우리 모델'라는 표현보다는 '해당 모델'의 정의로 하거나
'모델'의 정의를 포착한다는 걸로 바꾸는게 더 일관성있을거 같습니다

2024-01-28 08:26 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# 이것은 ResNet18 모델의 그래프 표현을 제공합니다.
주어에서 '이것은' 이라고 하면 조금 어색한듯합니다
'해당 부분은' 이라거나 '이 코드에서는'이라고 바꾸는건 어떨까요?

2024-01-28 08:26 UTC, hyoyoung commented on intermediate_source/fx_profiling_tutorial.py
> +# ``Interpreter`` 로부터 상속받음으로써, 다양한 기능을 덮여씌울 수 있고
'덮여씌울' -> '덮어씌울'의 오타인 것 같습니다 확인 부탁드립니다.

2024-01-29 00:03 UTC, closed without merging