prototype_source/torchscript_freezing.py 번역 진행 v2
PyTorchKorea/tutorials-kr pull request #788
Opened 2023-09-23 08:05 UTC by jiho3004

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #749 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
prototype_source/torchscript_freezing.py 튜토리얼을 번역합니다.

2023-09-24 12:36 UTC, hyoyoung requested changes
추가 피드백 확인 부탁드립니다

2023-09-24 13:21 UTC, jiho3004 commented on prototype_source/torchscript_freezing.py
> +동결은 파이토치 모듈의 매개변수와 속성 값들을 TorchScript 내부 표현으로 인라이닝하는 과정입니다.
병기하면 이해에 더 도움이 될 것 같습니다. 감사합니다.

2023-09-24 13:22 UTC, jiho3004 commented on prototype_source/torchscript_freezing.py
> +# 실행 시간에서 중요한 변화가 있었는데, 동결된 모델이 스크립트된 모델보다 약 15% 더 빠릅니다.
말씀하신 내용이 맞는 것 같습니다. 반영하겠습니다!

2023-09-24 13:23 UTC, jiho3004 commented on prototype_source/torchscript_freezing.py
> +# 실행 시간은 텐서 연산에 의해 지배되기 때문에 입력의 크기가 더 커지면 속도 개선 정도는 더 작아집니다.
넵, 중요한 부분을 놓쳤네요. 반영하겠습니다!

2023-09-30 12:40 UTC, hyoyoung approved these changes
good

2023-11-26 14:09 UTC, merged