문서 번역(#130)
PyTorchKorea/tutorials-kr pull request #795
Opened 2023-11-18 07:59 UTC by josseong

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [X ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #130 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [X ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
파이토치 튜토리얼중 Introduction to PyTorch on YouTube의 INTRODUCTION TO PYTORCH TENSORS문서를 번역하였습니다.

2023-11-18 12:26 UTC, hyoyoung commented
> [X ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.
> [X ] 번역되지 않은 튜토리얼을 번역하는 기여

위 2부분의 X 표시옆에 공백이 있어서 체크가 제대로 안되고 있습니다
수정해서 공백제거 부탁드립니다

2024-01-19 15:58 UTC, khleexv requested changes
번역하시느라 고생 많으셧습니다 !
문서 전반적으로 reStructredText 문법이 맞지 않는 부분이 다수 확인되는데, 그 중 일부 코멘트 달아드렸으니 참고하셔서 수정 부탁드립니다.

2024-01-19 15:58 UTC, khleexv commented on beginner_source/introyt/tensors_deeper_tutorial.py
> +아래 영상이나 `유튜브<https://www.youtube.com/watch?v=r7QDUPb2dCM>`__를 통해 따라할 수 있습니다.
```
`유튜브 <https://www.youtube.com/watch?v=r7QDUPb2dCM>`__  를
```
로 변경해주셔야 합니다.

2024-01-19 15:58 UTC, khleexv commented on beginner_source/introyt/tensors_deeper_tutorial.py
> +# 가장 간단한 방법은 ``torch.empty()``호출을 사용하여 텐서를 생성하는 것입니다:
닫는 `` 뒤에  공백 추가해주셔야 합니다.

2024-01-19 15:58 UTC, khleexv commented on beginner_source/introyt/tensors_deeper_tutorial.py
> +# -  마찬가지로 2차원 텐서는 *행렬*로 자주 언급됩니다.
닫는 * 뒤에 공백 추가해주셔야 합니다.

2024-01-19 15:58 UTC, khleexv commented on beginner_source/introyt/tensors_deeper_tutorial.py
> +# 자세한 내용은`문서 <https://pytorch.org/docs/stable/torch.html#torch.reshape>`__를 참조하세요.
여는 ` 앞에 공백, __ 뒤에 공백 추가되어야 합니다.

2024-01-19 15:58 UTC, khleexv commented on beginner_source/introyt/tensors_deeper_tutorial.py
> +# GPU로 이동하기
위 문단 전반적으로 마크업 문법 뒤에 공백이 빠져있습니다.

2024-01-28 08:05 UTC, khleexv commented
앗 ???,,, 리뷰 도중 뭔가 이상해서 확인해보니 이미 번역되어 있는 문서인 것 같습니다.
https://github.com/PyTorchKorea/tutorials-kr/blob/master/beginner_source/introyt/tensors_deeper_tutorial.py

@josseong 님께서 12월 18일 마스터 브랜치 기준으로 작업해주셨는데,
그 이전에 [이미 번역 중인 PR](https://github.com/PyTorchKorea/tutorials-kr/pull/760)이 있었고,  12월 26일에 마스터 브랜치에 해당 PR이 적용되어서, 번역이 진행 중인 것을 확인하지 못하신 것 같습니다 ㅠㅠ..

이런 경우에는 어떻게 하는 게 좋을까요? @hyoyoung

2024-01-28 08:10 UTC, hyoyoung commented
> 앗 ???,,, 리뷰 도중 뭔가 이상해서 확인해보니 이미 번역되어 있는 문서인 것 같습니다. https://github.com/PyTorchKorea/tutorials-kr/blob/master/beginner_source/introyt/tensors_deeper_tutorial.py
> 
> @josseong 님께서 12월 18일 마스터 브랜치 기준으로 작업해주셨는데, 그 이전에 [이미 번역 중인 PR](https://github.com/PyTorchKorea/tutorials-kr/pull/760)이 있었고, 12월 26일에 마스터 브랜치에 해당 PR이 적용되어서, 번역이 진행 중인 것을 확인하지 못하신 것 같습니다 ㅠㅠ..
> 
> 이런 경우에는 어떻게 하는 게 좋을까요? @hyoyoung

이경우는 열심히 번역해주셔서 죄송한일인데,
닫고 기존 번역 수정으로 하는게 어떨까 싶습니다

@josseong 번역하느라 고생하셨습니다. 확인하고 PR 닫아주시길 부탁드립니다
@khleexv 리뷰하느라 고생하셨습니다

2024-01-28 08:13 UTC, khleexv commented
이와 별개로, 작업해주신 것에 피드백 드리자면, PR 본문에 이슈 번호가 잘못 지정되어 있습니다.
이슈가 먼저 존재하는지 확인하고, 없으면 직접 열어주시면 될 것 같습니다.

그리고, 열심히 고쳐주셨지만, 아직도 문법 오류로 렌더링이 깨지는 부분이 일부 있습니다.
[CONTRIBUTING.md](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md#2-5-%EB%82%B4-%EC%BB%B4%ED%93%A8%ED%84%B0%EC%97%90%EC%84%9C-%EA%B2%B0%EA%B3%BC-%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0) 문서 참고하셔서 직접 빌드해보시면, 문법 에러를 쉽게 찾을 수 있습니다.
어렵지 않으니, 한번 빌드해보시는 것도 나쁘지 않을 것 같습니다.

혹시나 작업 도중 어려움이 있으시면 [discuss.pytorch.kr](https://discuss.pytorch.kr/) 에서 질문해주시면 도움 받으실 수 있으실 겁니다!

2024-05-12 12:34 UTC, hyoyoung commented
2주 이상 피드백이 없어서 닫습니다 필요하면 다시 열어주시기 바랍니다

2024-05-12 12:34 UTC, closed without merging