intermediate_source/ensembling.py 번역 진행
PyTorchKorea/tutorials-kr pull request #796
Opened 2024-01-20 10:00 UTC by ChoHyoungSeo

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #755 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
intermediate_source/ensembling.py 를 번역했습니다.

2024-01-28 08:33 UTC, hyoyoung requested changes
문서 번역하느라 고생하셨습니다. 몇가지 사소한 수정사항 확인 부탁드립니다.

2024-01-28 08:33 UTC, hyoyoung commented on intermediate_source/ensembling.py
> +사용 사례 중 하나는 for 문을 제거하고 벡터화를 통해 속도를 높이는 것입니다.
용어집을 보시면 텐서는 일반적으로 번역하지 않고 tensor로 쓰고 있습니다.

2024-01-28 08:33 UTC, hyoyoung commented on intermediate_source/ensembling.py
> +#
공백이 두줄인데, 한줄은 불필요한 것 같습니다

2024-01-28 08:33 UTC, hyoyoung commented on intermediate_source/ensembling.py
> +# 다음으로, ``vmap`` 에 대한 함수를 정의해야 합니다. 이 함수는 파라미터, 버퍼 그리고 입력값이 주어지면 모델을 실행합니다.
'파라미터, 버퍼 그리고 입력값'로 해도 좋지만
'파라미터, 버퍼, 입력값'으로 바꿔도 좋을 것 같습니다

2024-01-28 08:33 UTC, hyoyoung commented on intermediate_source/ensembling.py
> +# "stateless"는 매개변수가 메타 텐서이며 저장소가 없다는 것을 의미합니다.
tensor

2024-01-28 17:56 UTC, ChoHyoungSeo commented
Review 주셔서 감사합니다. 말씀해주신 부분 수정하여 commit 했습니다!

2024-01-28 18:29 UTC, khleexv approved these changes
앙상블도 지원하는 건 처음 알았네요, 번역하시느라 고생 많으셨습니다 !
번역에 큰 문제는 없는 것 같습니다.

2024-01-28 18:29 UTC, khleexv commented on intermediate_source/ensembling.py
> +# 몇 가지 예외가 있습니다. 이러한 경우가 발견되면, Github에 이슈를 생성해서 알려주시기 바랍니다.
매우 사소한 요소인데, Github => GitHub 이 맞는 표기입니다.

2024-01-29 09:59 UTC, ChoHyoungSeo commented
앗, 꼼꼼히 review 해주셔서 감사합니다! 말씀해주신 부분 수정 완료했습니다.

2024-05-12 12:36 UTC, hyoyoung approved these changes
good

2024-05-12 14:57 UTC, merged