:memo: Docs : TRANSLATION_GUIDE - 'built-in collection' 용어 추가
PyTorchKorea/tutorials-kr pull request #806
Opened 2024-08-01 15:48 UTC by jshEIT

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(805)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [x] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
용어집(TRANSLATION_GUIDE.md)에 새로운 단어를 추가하였습니다.

- 추가 단어 : **built-in collection** -> **내장 컬렉션**

2024-08-04 02:45 UTC, Dabinishere reviewed
collection은 컬렉션이라는 단어로 음차 표기하시고 built-in은  내장으로 번역하셨는데, 각각이 적절한 것 같아서 좋습니다. built-in 이라는 단어는 다른 곳에서는 내부로도 번역되던데, 내장이라는 표현이 훨씬 잘 어울리네요.

2024-08-04 10:14 UTC, jaeseong98 commented
추가된다면 좋을 것 같습니다! 감사합니다

2024-08-17 07:38 UTC, hyoyoung requested changes
PR 자체는 좋은데, 한번에 두가지 의미가 있는 PR이라서 merge하기 어렵습니다.
두 개로 나눠서 보내주시기 바랍니다

2024-08-17 09:32 UTC, jason9865 commented
> PR 자체는 좋은데, 한번에 두가지 의미가 있는 PR이라서 merge하기 어렵습니다. 두 개로 나눠서 보내주시기 바랍니다

수정 완료하였습니다!

2024-09-01 09:46 UTC, closed without merging