recipes_source/recipes/tuning_guide.py 번역
PyTorchKorea/tutorials-kr pull request #879
Opened 2024-08-18 14:52 UTC by ohkingtaek

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #870 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
recipes_source/recipes/tuning_guide.py 번역 진행 중입니다.

2024-09-07 11:04 UTC, jkworldchampion commented on recipes_source/recipes/tuning_guide.py
> +# 비동기식으로 데이터 가져오기 및 데이터 증강을 활성화하는 방법
'데이터 증강을 활성화하는 방법'을 '데이터 증강법'으로 바꾸는 것은 어떨까요?

2024-09-11 15:53 UTC, hyoyoung requested changes
긴 문서를 전반적으로 읽기 좋게 잘 정리해주셨습니다

몇가지 수정사항 및 제안사항을 남기니 확인해보시고 반영가능한 것은 반영 부탁드립니다.

2024-09-11 15:53 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# 사용할 수 있을 때까지 기다려야 실행할 수 있습니다.
As a result는 결론이라기 보다는
따라서나, 결과적으로 정도로 바꿔보는게 어떨까요?

2024-09-11 15:53 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# 역전파 중에 재계산합니다. 메모리 요구 사항이 줄어들어 배치 크기를 증가시킬 수 있으며, 이는 활용도를
여기서 utilization은 활용 효율이 조금 더 어울릴거 같습니다

2024-09-11 15:53 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# ``Tanh`` ), up/down 샘플링, 그리고 적은 축적 뎁스를 가진 행렬-벡터 연산 등이 체크포인트 저장
영어 문법 a,b and c일경우 a,b와 그리고 c입니다로 하지 않고
a,b,c입니다로 해도 자연스럽습니다

축적 뎁스라고 하니 조금 어색해보이는데
작은 누적 깊이(accumulation depth)정도는 어떨까요?

2024-09-11 15:53 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# ``DistributedDataParallel(find_unused_parameters=True)`` 를 사용할 때 모델 생성자와 실제 실행 중인 것의 레이어 순서를 일치시키는 방법
``DistributedDataParallel(find_unused_parameters=True)`` 를 사용할 때 생성자와 실행 레이어 순서를 일치시키는 방법

이렇게 해도 괜찮지 않을까요?

2024-09-11 15:53 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# all-reduce는 주어진 버킷의 모든 파라미터에 대한 변화도가 모두 준비되었을 때 비동기적으로 트리거됩니다.
트리거됩니다 보다 작동되다라는 말로 순화해보면 어떨까요

2024-09-11 15:53 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# 분산 설정에서 작업 로드 밸런싱하는 방법
로드 밸런싱은 부하 분산으로 순화 가능할 것 같습니다

2024-09-14 11:50 UTC, uddk6215 approved these changes
전체적으로 좋은 번역 같습니다.

2024-09-14 11:50 UTC, uddk6215 commented on recipes_source/recipes/tuning_guide.py
> +# ``BatchNorm2d`` 의 첫 단계에서 평균을 빼주기 때문에 필요하지 않으며, 이는 편향의 효과를
원문의 BatchNorm이 BatchNorm2d로 잘못 옮겨진 거 같습니다.:)

2024-09-17 11:59 UTC, ohkingtaek commented
@jkworldchampion @hyoyoung @uddk6215 피드백 감사합니다! 피드백에 맞춰 수정 및 번역 모범 사례 반영하여 추가 수정완료했습니다

2024-09-22 07:05 UTC, jason9865 commented on recipes_source/recipes/tuning_guide.py
> +# 가능해집니다. ``num_workers`` 값은 작업량, CPU, GPU, 학습 데이터의 위치에 따라 조정해야
수동형 -> 능동형으로 바꾸면 가독성이 향상될 것 같습니다.
가능해집니다 -> 가능합니다

2024-09-22 07:07 UTC, jason9865 commented on recipes_source/recipes/tuning_guide.py
> +# 고정된 메모리를 사용하게 되고, 호스트에서 GPU로 더 빠르고 비동기적인 메모리 복사를 가능하게 합니다.
수동형 -> 능동형으로 바꾸면 가독성이 향상될 것 같습니다.
- 사용하게 되고 -> 사용하고
- 비동기적인 메모리 복사를 가능하게 합니다 -> 비동기적으로 메모리를 복사합니다

2024-09-22 07:14 UTC, jason9865 commented on recipes_source/recipes/tuning_guide.py
> +# 함수 등의 point-wise 연산들은 하나의 커널로 결합할 수 있습니다. 이러한 결합은 메모리 접근과 커널
사소한 부분이기는 하지만
- 연산들 -> 연산
과 같이 **번역 모범 사례**와 **KIGO 표준 스타일 가이**드에 명시된 것처럼
복수 표현을 단수표현으로 나타내면 좋을 것 같습니다.

2024-09-22 07:29 UTC, jason9865 commented on recipes_source/recipes/tuning_guide.py
> +# CPU 친화도 설정은 작업이 여러 코어에 분배되는 방식을 제어합니다. 이는 통신 오버헤드와 캐시 라인
"친화도" 대신 Affinity를 그대로 사용하는 것이 어떨까요?
- CPU 친화도 -> CPU Affinity

2024-09-22 07:40 UTC, jaeseong98 reviewed
작업하시느라 수고많으셨습니다!

2024-09-22 07:40 UTC, jaeseong98 commented on recipes_source/recipes/tuning_guide.py
> +# 번만 로드되고 저장됩니다. 특히 이러한 효율적인 방법은 활성화 함수, 옵티마이저, 직접 수정한 RNN 셀
바로 95번째 문장에서 load를 "불러오다"라는 의미로 사용한것으로 보아 99번째에서도 로드되고 -> 불러오고 쓰면 어떨까요? 337번쨰 행도 마찬가지입니다!

2024-09-22 07:41 UTC, jason9865 commented
긴 문서 번역하시느라 고생 많으셨습니다.
몇 가지 comment를 달아놓았으니 확인 부탁드립니다!

2024-10-06 10:26 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# 다중 소켓을 가진 머신에서는 분산 학습이 고효율의 하드웨어 자원 사용을 통해 학습 과정을 가속화합니다.
여러 소켓을 가진 머신에서는, 분산 학습으로 고효율의 하드웨어 자원 사용하여 학습 과정을 가속할 수 있습니다.

이정도로 의역해보면 어떨까요?

2024-10-06 10:26 UTC, hyoyoung commented on recipes_source/recipes/tuning_guide.py
> +# * 입력 크기가 매우 가변적인 경우처럼 드문 상황에서는, 각 입력 크기에 대해 알고리즘 선택과 관련된
드문 상황에서, 예를 들면 입력 크기가 가변적인 경우,

이렇게 바꿔보는게 문맥을 이해하기 쉬워질거 같습니다

2024-10-14 13:09 UTC, hyoyoung approved these changes
good

2024-10-15 11:04 UTC, merged