Translate prototype_source/semi_structured_sparse.rst
PyTorchKorea/tutorials-kr pull request #889
Opened 2024-08-25 09:54 UTC by Dabinishere

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #866 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
prototype_source/semi_structured_sparse.rst 문서를 번역하였습니다.

2024-09-11 12:03 UTC, rumjie commented on prototype_source/semi_structured_sparse.rst
> +반구조적 희소성은 특히 GPU에서 효율적으로 가속화할 수 있고, 다른 희소성 패턴보다 모델의 정확도를 덜 저하시키기 때문에 흥미롭습니다.
"가속화될 수 있고"가 좀더 자연스러운 것 같습니다! 
line 84에서 수동태로 사용하신 것과 통일성도 생길 것 같아요 😀

2024-09-11 12:07 UTC, rumjie commented on prototype_source/semi_structured_sparse.rst
> +            # 해당 예제와 연관된 모든 피처 반복하기
TRANSLATION_GUIDE.md 에 따라 feature는 특징이라고 번역하는 것은 어떨까요?

2024-09-19 00:08 UTC, hyoyoung requested changes
전반적으로 잘되어있으나
몇가지 확인해봐야할 부분이 있습니다.
확인후에 수정 부탁드립니다.

2024-09-19 00:08 UTC, hyoyoung commented on prototype_source/semi_structured_sparse.rst
> +이 두 문제 사이의 자연스러운 핸드오프(handoff) 포인트는 0으로 된 밀집 텐서입니다. 이 형식의 텐서를 압축하고 가속화하도록 추론을 설계했습니다.
용어집에서 tensor는 일반적으로 번역하지 않습니다

2024-09-19 00:08 UTC, hyoyoung commented on prototype_source/semi_structured_sparse.rst
> +    # 2:4 희소성은 fp16이 필요하므로 공정한 비교를 위해 여기서 캐스팅
여기서 캐시팅은 변환이나 형 변환이라고 의역하는게 좋을 거 같습니다

2024-09-19 00:08 UTC, hyoyoung commented on prototype_source/semi_structured_sparse.rst
>  We will explain this process in this tutorial.
위 3문장은 번역되었는데 남아있는 것일까요?

2024-09-19 00:08 UTC, hyoyoung commented on prototype_source/semi_structured_sparse.rst
> +이 튜토리얼을 끝내면, BERT 질문-답변 모델을 2:4 희소성으로 가지치기하고, 거의 모든 F1 손실(밀집 86.92 vs 희소 86.48)을 복구하도록 미세 조정할 수 있습니다.
이 튜토리얼을 끝내면, ~~ 하는 모델이 완성됩니다. 정도는 어떨까요?

2024-09-19 00:08 UTC, hyoyoung commented on prototype_source/semi_structured_sparse.rst
> +(프로토타입) 반구조적 (2:4) 희소성(semi-structured (2:4) sparsity)을 이용한 BERT 가속화하기
semi-structure가 반구조인지 반정형인지, 조금 결정하기 어려운 문제인데
DB용어라면 반정형에 어울릴거 같습니다
https://ko.wikipedia.org/wiki/%EB%B0%98%EC%A0%95%ED%98%95_%EB%8D%B0%EC%9D%B4%ED%84%B0
어떤게 더 나을까요?

2024-09-22 07:46 UTC, jaeseong98 reviewed
번역하시느라 수고많으셨습니다!

2024-09-22 07:46 UTC, jaeseong98 commented on prototype_source/semi_structured_sparse.rst
> +1. 이전의 희소 형식과 달리 반구조적 희소성은 GPU에서 효율적으로 가속화되도록 설계되었습니다.
가속화하다와 가속화되다가 섞여있는것 같아서 둘 중 하나로 통일성을 주면 좋을 것 같습니다!

2024-10-06 10:33 UTC, hyoyoung approved these changes
good

2024-10-14 22:29 UTC, 9bow approved these changes

2024-10-15 01:40 UTC, merged