beginner_source/ddp_series_intro.rst 번역
PyTorchKorea/tutorials-kr pull request #892
Opened 2024-08-25 11:37 UTC by hojunking

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #891

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
beginner_source/ddp_series_intro.rst 번역 완료.

2024-09-14 13:39 UTC, uddk6215 approved these changes
나머진 깔끔하게 잘 번역된 거 같습니다.

2024-09-14 13:39 UTC, uddk6215 commented on beginner_source/ddp_series_intro.rst
> +이 시리즈는 단순한 비분산 학습 작업에서 시작하여, 클러스터 내 여러 기기들(multiple machines)에서 학습 작업을 배포하는 것으로 마무리됩니다. 이 과정에서 `torchrun <https://pytorch.org/docs/stable/elastic/run.html>`__을 사용한 장애 허용(fault-tolerant) 분산 학습에 대해서도 배
이전에 이 문서를 번역하신 분께도 드린 리뷰인데, 다시 한 번 제안드려 봅니다.
fault-tolerant distributed training이란 용어의 뜻을 보니 분산 시스템에서 하나 이상의 장치의 실패에도 계속해서 정상적으로 동작할 수 있는 능력으로 나오더라구요. 장애 허용을 결함 내성 정도로 표현하면 좀 더 직관적일 거 같습니다. :)

2024-09-19 00:11 UTC, hyoyoung requested changes
전반적으로 잘되어있으나 몇가지 확인하면 좋을 부분들이 있습니다.
확인 후에 수정 부탁드립니다

2024-09-19 00:11 UTC, hyoyoung commented on beginner_source/ddp_series_intro.rst
> +저자: `Suraj Subramanian <https://github.com/suraj813>`__
번역자 정보를 아래줄에 넣어주세요

2024-09-19 00:11 UTC, hyoyoung commented on beginner_source/ddp_series_intro.rst
> +아래 비디오를 보거나 `YouTube <https://www.youtube.com/watch/-K3bZYHYHEA>`__에서 함께 시청하세요.
함께 시청할 수 있습니다. 혹은 함께 보실 수 있습니다. 정도로 의역하면 어떨까요?

2024-09-19 00:11 UTC, hyoyoung commented on beginner_source/ddp_series_intro.rst
> +튜토리얼 코드는 이 `GitHub 저장소 <https://github.com/pytorch/examples/tree/main/distributed/ddp-tutorial-series>`__에 호스팅되어 있습니다. 저장소를 복제하고 함께 진행하세요!
호스팅되어 있습니다. 보다는 올라와 있습니다. 혹은 공개되어있습니다. 정도로 의역하는게 어떨까요?

2024-09-20 01:16 UTC, hojunking commented on beginner_source/ddp_series_intro.rst
> +튜토리얼 코드는 이 `GitHub 저장소 <https://github.com/pytorch/examples/tree/main/distributed/ddp-tutorial-series>`__에 호스팅되어 있습니다. 저장소를 복제하고 함께 진행하세요!
수정했습니다! 너무 기계적인 말보단 적당히 의역이 필요하군요! 피드백 감사드립니다!

2024-09-20 01:17 UTC, hojunking commented on beginner_source/ddp_series_intro.rst
> +저자: `Suraj Subramanian <https://github.com/suraj813>`__
추가했습니다.

2024-09-20 01:19 UTC, hojunking commented on beginner_source/ddp_series_intro.rst
> +이 시리즈는 단순한 비분산 학습 작업에서 시작하여, 클러스터 내 여러 기기들(multiple machines)에서 학습 작업을 배포하는 것으로 마무리됩니다. 이 과정에서 `torchrun <https://pytorch.org/docs/stable/elastic/run.html>`__을 사용한 장애 허용(fault-tolerant) 분산 학습에 대해서도 배
저도 앞으론 전문 용어 번역할 때, 관련 지식을 확인해 보겠습니다. 피드백 감사합니다.

2024-09-22 07:40 UTC, jason9865 commented
긴 문서를 번역하시느라 고생 많으셨습니다.
코멘트를 몇 가지 달아놓았으니 확인 부탁드립니다.

2024-10-06 10:35 UTC, hyoyoung approved these changes
good

2024-10-15 03:05 UTC, 9bow approved these changes

2024-10-15 11:05 UTC, merged