beginner_source/ddp_series_theory.rst 번역
PyTorchKorea/tutorials-kr pull request #896
Opened 2024-08-26 13:09 UTC by rumjie

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #872

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
- 문서 번역

2024-09-08 10:43 UTC, jih0-kim reviewed
한국어로의 번역을 자연스럽게 수행해 주셨습니다. 👍 
내용과 관련하여 몇 가지 코멘트를 남겨드리며, 확인해 주시면 좋을 것 같습니다.

2024-09-08 10:43 UTC, jih0-kim commented on beginner_source/ddp_series_theory.rst
> +      *  GPU 간 기울기들이 동기화되는 방법
gradient의 경우 TRANSLATION_GUIDE.md 문서에 따라 '변화도' 라고 표현하는 것을 제안 드립니다.

2024-09-08 10:43 UTC, jih0-kim commented on beginner_source/ddp_series_theory.rst
> +아래의 영상이나 `유투브 영상 youtube <https://www.youtube.com/watch/Cvdhwx-OBBo>`__ 을 따라 진행하세요.
유투브 영상 -> 유튜브 영상으로 표현하는 것을 제안 드립니다.

2024-09-14 12:12 UTC, uddk6215 approved these changes
리뷰를 하기 위해 분산 데이터 병렬처리에 대해 짤막하게나마 공부도 할 수 있었고,
번역도 전반적으로 잘 되어 있는 거 같습니다.

2024-09-14 12:12 UTC, uddk6215 commented on beginner_source/ddp_series_theory.rst
> +     - 빠름; 멀티 프로세싱을 사용하기 때문에 GIL 충돌 없음
-느림;과 빠름;
이전 회의에서 받았던 KIGO 표준 스타일 가이드를 보면 "두 문장 사이의 세미콜론(;)은 쉼표(,) 또는 마침표(.)로 대체
한다." 로 되어있더라구요. 이 부분 표준에 맞게 수정하면 더욱 좋을 거 같습니다. :)

2024-09-15 06:21 UTC, rumjie commented on beginner_source/ddp_series_theory.rst
> +      *  GPU 간 기울기들이 동기화되는 방법
반영하였습니다.

2024-09-15 06:21 UTC, rumjie commented on beginner_source/ddp_series_theory.rst
> +아래의 영상이나 `유투브 영상 youtube <https://www.youtube.com/watch/Cvdhwx-OBBo>`__ 을 따라 진행하세요.
반영하였습니다. 코멘트 감사합니다!

2024-09-15 06:21 UTC, rumjie commented on beginner_source/ddp_series_theory.rst
> +     - 빠름; 멀티 프로세싱을 사용하기 때문에 GIL 충돌 없음
반영하였습니다. 코멘트 감사합니다!

2024-09-19 19:03 UTC, hyoyoung requested changes
전반적으로 잘되어있으나
사소한 수정 사항 몇가지가 필요합니다.
확인 후 수정 부탁드립니다

2024-09-19 19:03 UTC, hyoyoung commented on beginner_source/ddp_series_theory.rst
>  Authors: `Suraj Subramanian <https://github.com/suraj813>`__
author도 저자 정도로 번역 부탁드립니다

2024-09-19 19:03 UTC, hyoyoung commented on beginner_source/ddp_series_theory.rst
> +      *  GPU 간 기울기들이 동기화되는 방법
기울기로 된 단어가 적용이 안된 부분이 있는것 같습니다. 확인 부탁드립니다.

2024-09-19 19:03 UTC, hyoyoung commented on beginner_source/ddp_series_theory.rst
> +모델은 모든 디바이스에 복제되며, 각 사본은 기울기를 계산하는 동시에 `링 올-리듀스
여기도 기울기가 있습니다

2024-09-19 19:03 UTC, hyoyoung commented on beginner_source/ddp_series_theory.rst
> +   * - 작업 부하가 큼; 전파될 때마다 모델이 복제 및 삭제됨
한국어에서는 ;를 잘 안쓰기때문에 문장 2개로 바꾸거나, 1문장으로 합쳐도 좋을 것 같습니다.

2024-09-19 19:03 UTC, hyoyoung commented on beginner_source/ddp_series_theory.rst
> +모델은 모든 디바이스에 복제되며, 각 사본은 기울기를 계산하는 동시에 `링 올-리듀스
링 올-리듀스는 잘 쓰이지 않는 표현이기때문에 영어로 병기하거나
아니면 영어 그 자체로 쓰시는 게 더 가독성에 좋을 듯합니다

2024-09-22 07:00 UTC, jason9865 commented on beginner_source/ddp_series_theory.rst
> +      *  GPU 간 기울기들이 동기화되는 방법
사소한 부분이지만 아래와 같이 바뀐다면 더 좋을 것 같습니다.
기울기들이 -> 기울기를
**번역모범사례**와 **KIGO 표준 스타일 가이드**에 나오는 것처럼
영어의 복수표현은 가급적 단수표현으로 나타내는 것이 권장되기 때문입니다.

2024-09-22 07:01 UTC, jason9865 commented on beginner_source/ddp_series_theory.rst
> +모델은 모든 디바이스에 복제되며, 각 사본은 기울기를 계산하는 동시에 `링 올-리듀스
아래와 같은 표현을 제안합니다.
링-올 리듀스 알고리즘 -> Ring-All-Reduce 알고리즘

2024-09-22 07:02 UTC, jason9865 commented
안녕하세요.
번역하시느라 고생 많으셨습니다.
몇 가지 코멘트를 달아놓았으니, 참고바랍니다.

2024-10-02 14:50 UTC, rumjie commented
주신 코멘트들을 모두 반영한 커밋 push 완료했습니다. 세심한 코멘트 주신 분들께 모두 감사의 말씀 드립니다 🥰

2024-10-06 10:37 UTC, hyoyoung commented on beginner_source/ddp_series_theory.rst
> +     - 빠름, 멀티 프로세싱을 사용하기 때문에 GIL 충돌 없음
ascii로된 table이 list-table형식으로 바꿔두셨는데
혹시 뭔가 이유가 있었을까요?
큰 이유가 없다면 원본 문서 형식을 맞춰두는게 차후 개선을 위해서 편리할거 같습니다

2024-10-06 12:25 UTC, rumjie commented on beginner_source/ddp_series_theory.rst
> +     - 빠름, 멀티 프로세싱을 사용하기 때문에 GIL 충돌 없음
제가 잘못 작성했을 수도 있었을 것 같은데, 빌드해서 홈페이지 확인했을 때 테이블이 깨지는 것을 발견해서 형식을 바꿔두었습니다!

2024-10-06 15:39 UTC, hyoyoung approved these changes
good

2024-10-15 02:31 UTC, 9bow approved these changes

2024-10-15 11:05 UTC, merged