torch_compile_backend_ipex.rst 번역
PyTorchKorea/tutorials-kr pull request #901
Opened 2024-08-30 04:29 UTC by jh941213

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #900 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명

문서번역

2024-09-08 13:49 UTC, hadh93 reviewed
번역하시느라 고생 많으셨습니다!
몇 가지 제안 드리니 확인 부탁드립니다 🙏

2024-09-08 13:49 UTC, hadh93 commented on recipes_source/torch_compile_backend_ipex.rst
> +`torch.compile`을 통해 더 원활한 작동을 위해, Intel® Extension for PyTorch는 ``ipex``라는 백엔드를 구현했습니다. 이 백엔드는 Intel 플랫폼에서 하드웨어 자원 사용 효율성을 개선하여 성능을 향상시키는 것을 목표로 합니다. `ipex` 백엔드는 모델 컴파일을 위한 Intel® Extension for PyTor
1. 마크업 문법이 적용되도록 띄어쓰기가 필요합니다. 
- `torch.compile`을 -> `torch.compile` 을
- ``ipex``라는 -> ``ipex`` 라는

2. To work better with을 ~과 더 잘 작동하도록 으로 번역하면 어떨까요?

2024-09-08 13:49 UTC, hadh93 commented on recipes_source/torch_compile_backend_ipex.rst
>     # Invoke the following API optionally, to apply frontend optimizations
이 부분도 번역이 필요할 것 같아요!

2024-09-08 13:49 UTC, hadh93 commented on recipes_source/torch_compile_backend_ipex.rst
>     #################### code changes ####################
이 부분도 번역이 필요할 것 같아요!

2024-09-08 13:49 UTC, hadh93 commented on recipes_source/torch_compile_backend_ipex.rst
> +아래 예시를 통해 `ipex` 백엔드를 `torch.compile`와 함께 활용하여 FP32 데이터 유형으로 모델을 추론하는 방법을 알아보세요.
1. 빌드해 보니, 아래와 같은 글자 깨짐이 있습니다. 
![image](https://github.com/user-attachments/assets/e794d98c-d640-437a-904f-940410c6b706)
- 'FP32' 앞의 공백을 지웠다가 다시 입력해보시는 건 어떨까요?

2. 마크업 문법이 적용되도록 띄어쓰기가 필요합니다.
- `torch.compile`와 -> `torch.compile` 와

2024-09-09 00:30 UTC, jh941213 commented on recipes_source/torch_compile_backend_ipex.rst
> +`torch.compile`을 통해 더 원활한 작동을 위해, Intel® Extension for PyTorch는 ``ipex``라는 백엔드를 구현했습니다. 이 백엔드는 Intel 플랫폼에서 하드웨어 자원 사용 효율성을 개선하여 성능을 향상시키는 것을 목표로 합니다. `ipex` 백엔드는 모델 컴파일을 위한 Intel® Extension for PyTor
감사합니다. 확인했습니다!

2024-09-09 00:30 UTC, jh941213 commented on recipes_source/torch_compile_backend_ipex.rst
>     # Invoke the following API optionally, to apply frontend optimizations
감사합니다. 확인했습니다!

2024-09-09 00:30 UTC, jh941213 commented on recipes_source/torch_compile_backend_ipex.rst
>     #################### code changes ####################
감사합니다. 확인했습니다!

2024-09-19 19:16 UTC, hyoyoung requested changes
전반적으로 잘되어있는데 몇가지 수정 사항이 필요합니다.
확인 후에 수정 부탁드립니다

2024-09-21 06:32 UTC, oh5221 commented
고생하셨습니다!
원문과 같이 보다 보니 한 가지 점이 눈에 보이네요.
확인 부탁드리겠습니다 ㅎㅎ

2024-09-22 02:54 UTC, jh941213 commented
> 전반적으로 잘되어있는데 몇가지 수정 사항이 필요합니다. 확인 후에 수정 부탁드립니다

@hyoyoung 감사합니다. 쉼표등 생각을 못하고 있었네요. 수정 반영하겠습니다

2024-09-22 06:19 UTC, NK590 commented
다른 분들이 좋은 리뷰 많이 남겨주셔서 크게 수정해야 될 부분은 보이지 않는 것 같습니다. 수고하셨습니다!

2024-09-22 07:15 UTC, Angela-Park-JE commented
잘 되어있는 번역에 피드백까지 반영된 후여서인지 저에게는 좋은 번역으로 보입니다.
원문의 의미를 잘 담은 명확하고 간결한 단어 선택이 정말 좋았습니다. 수고하셨습니다! 👍

2024-09-29 08:31 UTC, hadh93 commented on recipes_source/torch_compile_backend_ipex.rst
>     #################### code changes ####################
피드백 반영해주셔서 감사합니다!
여기 미번역 주석 한 줄 발견해서 코멘트로 알려드립니다ㅎㅎ

2024-10-07 00:53 UTC, jh941213 commented on recipes_source/torch_compile_backend_ipex.rst
>     #################### code changes ####################
감사합니다.

2024-10-14 13:07 UTC, hyoyoung requested changes
몇가지 수정 사항이 있습니다 확인 부탁드립니다.

2024-10-14 13:07 UTC, hyoyoung commented on recipes_source/torch_compile_backend_ipex.rst
> +- `torch.compile` 과 더 잘 작동하도록, Intel® Extension for PyTorch는 ``ipex`` 라는 백엔드를 구현했습니다.
역자 정보 추가 부탁드립니다.

2024-10-15 11:06 UTC, merged