backend_config_tutorial.rst 번역
PyTorchKorea/tutorials-kr pull request #909
Opened 2024-09-01 09:49 UTC by jason9865

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #868 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [x] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
- prototype_source의 backend_config_tutorial.rst를 번역하였습니다.

2024-09-14 13:30 UTC, uddk6215 approved these changes
저도 번역 작업을 하는 과정에서 영문에서 한글로 옮길 때 어색한 부분이 생기는 경우가 많았는데,
그 부분을 신경 많이 쓰신 거 같습니다. 잘 읽었습니다.:)

2024-09-14 13:30 UTC, uddk6215 commented on prototype_source/backend_config_tutorial.rst
> +하나의 양자화된 선형 연산자로 변환하여 사용한다고 가정합시다.
"~ 양자화된 단일 선형 연산자로 축소하여 ~"가 좀 더 정확한 표현일 거 같습니다.

2024-09-20 16:46 UTC, hyoyoung requested changes
긴문서 번역하느라 수고하셨습니다
전반적으로 잘되어있는데 몇가지 수정 사항이 필요합니다
확인해보시고, 필요한경우 반영 부탁드립니다

2024-09-20 16:46 UTC, hyoyoung commented on prototype_source/backend_config_tutorial.rst
>  **Author**: `Andrew Or <https://github.com/andrewor14>`_
번역자 정보 추가 부탁드립니다

2024-09-20 16:46 UTC, hyoyoung commented on prototype_source/backend_config_tutorial.rst
> +
이 줄의 공백은 제거해도 좋을거 같습니다

2024-09-20 16:46 UTC, hyoyoung commented on prototype_source/backend_config_tutorial.rst
> +이를 통해 양자화 파라미터가 서로 다른 양자화 연산자(quant1과 quant2)를 거치며
TRANSLATION_GUIDE.md 보시면 parameter는 매개변수로 번역하라고 권유하고 있습니다

2024-09-20 16:46 UTC, hyoyoung commented on prototype_source/backend_config_tutorial.rst
> +
>We can set up fusion by defining a function that accepts
3 arguments, where the first is whether or not this is for QAT, and the
remaining arguments refer to the individual items of the fused pattern.

이 부분에 대한 번역이 없는거 같습니다

2024-09-21 11:30 UTC, jason9865 commented on prototype_source/backend_config_tutorial.rst
> +하나의 양자화된 선형 연산자로 변환하여 사용한다고 가정합시다.
제시해주신 대안이 더 정확한 표현인 것 같습니다. 피드백 주셔서 감사합니다!

2024-09-21 11:30 UTC, jason9865 commented on prototype_source/backend_config_tutorial.rst
>  **Author**: `Andrew Or <https://github.com/andrewor14>`_
수정완료하였습니다!

2024-09-21 12:02 UTC, jason9865 commented on prototype_source/backend_config_tutorial.rst
> +
수정완료하였습니다!

2024-09-21 12:03 UTC, jason9865 commented on prototype_source/backend_config_tutorial.rst
> +이를 통해 양자화 파라미터가 서로 다른 양자화 연산자(quant1과 quant2)를 거치며
수정완료하였습니다!

2024-10-06 11:40 UTC, hyoyoung commented on prototype_source/backend_config_tutorial.rst
> -BackendConfig, please refer to this
번역정보를 넣어서 좋아졌는데
이번엔 저자 정보가 빠졌습니다
추가 부탁드립니다

2024-10-06 11:40 UTC, hyoyoung commented on prototype_source/backend_config_tutorial.rst
> +5. 백엔드 환경 제약조건을 충족하기 위해 QConfigMapping 설정하기
백엔드 환경 제약조건을 만족시키는 QConfigMapping 설정하기

요정도로 바꿔보는건 어떨까요

2024-10-06 15:40 UTC, hyoyoung approved these changes
good

2024-10-15 01:41 UTC, merged