beginner_source/ddp_series_multigpu.rst 번역
PyTorchKorea/tutorials-kr pull request #912
Opened 2024-09-03 12:12 UTC by NK590

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #890 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

beginner_source/ddp_series_multigpu.rst 파일을 영어에서 한국어로 번역하였습니다.
빌드 후 정상적으로 표기되는 것 확인하였습니다.

2024-09-10 07:03 UTC, hadh93 commented on beginner_source/ddp_series_multigpu.rst
> +   `torch.nn.SyncBatchNorm.convert_sync_batchnorm(model) <https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html#torch.nn.SyncBatchNorm.convert_sync_batchnorm>`__ 를 이용하여 모델 안의 ``BatchN
문체가 '-세요', '-십시오' 등 여러 가지가 사용되었는데, '-세요'로 일관되게 사용하면 어떨까요?

- c.f. 모던 자바스크립트 튜토리얼의 [번역 모범 사례](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%8B%9C%EB%8A%94-%EC%A0%9C%ED%95%9C%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%A9%EB%8B%88%EB%8B%A4)

2024-09-10 07:10 UTC, hadh93 commented on beginner_source/ddp_series_multigpu.rst
> +-  `DDP와 함께 시작하기 <https://tutorials.pytorch.kr/intermediate/ddp_tutorial.html>`__
이 문서는 '분산 데이터 병렬 처리 시작하기'라는 제목으로 이미 번역되어 있네요!
여기서도 같은 제목을 사용하면 좋을 것 같습니다.

2024-09-20 16:52 UTC, hyoyoung requested changes
긴문서 번역하느라 수고하셨습니다
전반적으로 잘되어있고
몇가지 수정사항을 제안드리니 확인하고 반영 필요한 부분은 수정 부탁드립니다

2024-09-20 16:52 UTC, hyoyoung commented on beginner_source/ddp_series_multigpu.rst
> +      -  분할 환경에서 모델을 저장 및 로드하는 법
여기서 로드하는 법은 읽어오는 법으로 순화해도 좋을 듯 합니다

2024-09-20 16:52 UTC, hyoyoung commented on beginner_source/ddp_series_multigpu.rst
> +`이전 튜토리얼 <ddp_series_theory.html>`__ 에서, 우리는 DDP가 어떻게 동작하는지에 대해 전반적으로 알아보았으므로, 이제 실제로 DDP를 어떻게 사용하는지 코드를 볼 차례입니다.
> 우리는 DDP가 어떻게 동작하는지에 대해 전반적으로 알아보았으므로,

DDP가 어떻게 동작하는지 전반적으로 알아보았으므로,

이정도로 바꿔보면 어떨까요?

2024-09-20 16:52 UTC, hyoyoung commented on beginner_source/ddp_series_multigpu.rst
> +이 과정에서, 분할 훈련(distributed training)에 대한 중요한 개념들을 직접 코드로 구현하면서 다루게 될 것입니다.
보통 distribute는 분산으로 쓰고 있습니다

2024-09-20 16:52 UTC, hyoyoung commented on beginner_source/ddp_series_multigpu.rst
> +   다음 도움 함수(helper function)
도움 함수 사용하기 정도는 어떨까요?

2024-09-20 16:52 UTC, hyoyoung commented on beginner_source/ddp_series_multigpu.rst
> +   DDP 환경에서 모델의 저장과 불러오기 등에 대해 자세한 내용을 확인할 수 있습니다.
위에서 load는 로드로 되어있으므로 같은 용어로 맞추면 더 좋을거 같습니다

2024-09-21 06:47 UTC, oh5221 commented
고생하셨습니다! :)
많이 고민하신 티가 나네요.
작은 오타를 발견해서 피드백 남깁니다...!

2024-09-22 02:41 UTC, jh941213 commented
고생하셨습니다. 
피드백 부분 수정보완하면 더 좋을 것 같습니다!

2024-09-22 06:35 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +      * `DDP가 어떻게 동작하는지 <ddp_series_theory.html>`__ 에 대한 높은 이해도
좋은 지적 감사합니다!

2024-09-22 06:35 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +   `torch.nn.SyncBatchNorm.convert_sync_batchnorm(model) <https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html#torch.nn.SyncBatchNorm.convert_sync_batchnorm>`__ 를 이용하여 모델 안의 ``BatchN
맹점이었네요. 확인 감사합니다!

2024-09-22 06:48 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +-  `DDP와 함께 시작하기 <https://tutorials.pytorch.kr/intermediate/ddp_tutorial.html>`__
확인 감사합니다!

2024-09-22 06:49 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +      -  분할 환경에서 모델을 저장 및 로드하는 법
확인 감사합니다!

2024-09-22 06:49 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +`이전 튜토리얼 <ddp_series_theory.html>`__ 에서, 우리는 DDP가 어떻게 동작하는지에 대해 전반적으로 알아보았으므로, 이제 실제로 DDP를 어떻게 사용하는지 코드를 볼 차례입니다.
없어도 되는 주어 표현 최대한 자제하려고 했는데 무의식적으로 또 넣었네요 ㅜㅜ 감사합니다!

2024-09-22 06:50 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +   DDP 환경에서 모델의 저장과 불러오기 등에 대해 자세한 내용을 확인할 수 있습니다.
확인 감사합니다!

2024-09-22 06:50 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +   다음 도움 함수(helper function)
그게 더 나을 것 같네요. 감사합니다!

2024-09-22 07:48 UTC, Angela-Park-JE commented
번역 수고 많으셨습니다! 전반적으로 간결하게 번역하려고 노력하신 부분이 보이는 번역이었습니다.
두 가지, 작은 부분에 대해 수정 사항을 제안드립니다 😄👍

2024-09-22 07:50 UTC, Angela-Park-JE commented on beginner_source/ddp_series_multigpu.rst
> +   이 예제에서는, `_save_checkpoint` 오로지 ``rank:0`` 프로세스에서만 실행되기 때문에, 어떠한 집합 콜도 가지고 있으면 안 됩니다.
의미상 "이 예제에서, `_save_checkpoint` 는" 도 좋을 것 같습니다!
번역문에서 주어의 조사가 빠져있어 다소 어색한 느낌을 받았습니다.

2024-09-22 07:52 UTC, Angela-Park-JE commented on beginner_source/ddp_series_multigpu.rst
> +-  (``device`` 를 대신할) 새로운 인자값 ``rank`` 와 ``world_size`` 를 도입합니다.
원문에서는 ``device``를 대신하는 것은 ``rank``로 보이나, 번역에서 ``world_size``도 함께 지칭되는 것으로 보이기도 하는 것 같습니다! 이렇게 번역하는 것은 어떠실까요?  
- 새로운 인자값 ``rank``(``device``를 대체)와 ``wolrd_size`` 를 도입합니다.

2024-09-23 06:16 UTC, NK590 commented on beginner_source/ddp_series_multigpu.rst
> +   이 예제에서는, `_save_checkpoint` 오로지 ``rank:0`` 프로세스에서만 실행되기 때문에, 어떠한 집합 콜도 가지고 있으면 안 됩니다.
꼼꼼하게 잘 찾아주셨네요. 감사합니다!

2024-09-29 08:27 UTC, hadh93 approved these changes
반영해 주신 부분 확인했습니다!
LGTM입니다 ☺️

2024-10-06 11:43 UTC, hyoyoung commented on beginner_source/ddp_series_multigpu.rst
> +
빈줄이어야하는데 공백이 있습니다

2024-10-06 11:49 UTC, hyoyoung approved these changes
good

2024-10-14 23:19 UTC, 9bow approved these changes

2024-10-15 01:42 UTC, merged