recipes_source /torch_compile_user_defined_triton_kernel_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #918
Opened 2024-09-05 14:34 UTC by dlcodns

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(911)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명

recipes_source의 torch_compile_user_defined_triton_kernel_tutorial.py파일을 전체 번역하였습니다.

2024-09-24 15:49 UTC, hyoyoung requested changes
전반적으로 잘 되어있으나
몇가지 확인 사항이 필요합니다. 보시고 맞게 수정 부탁드립니다.

2024-09-24 15:49 UTC, hyoyoung commented on recipes_source/torch_compile_user_defined_triton_kernel_tutorial.py
> +**저자:** `Oguz Ulgen <https://github.com/oulgen>`_
아래줄에 번역자 정보 추가 부탁드립니다

2024-09-24 15:49 UTC, hyoyoung commented on recipes_source/torch_compile_user_defined_triton_kernel_tutorial.py
> +# Triton의 자동 튜닝 기능은 Triton 커널의 구성 파라미터를 자동으로 최적화해주는 강력한 도구입니다.
용어집에서 parameter(s)는 매개변수로 번역하도록 권장하고 있습니다

2024-09-24 15:49 UTC, hyoyoung commented on recipes_source/torch_compile_user_defined_triton_kernel_tutorial.py
> +# .. 참고::
여기서 참고는 note의 번역으로 보이는데요
restructedText 문법의 일부로 보입니다.
빌드 한번 해서 확인 하고 맞게 되는지 확인 부탁드립니다.

2024-09-24 15:49 UTC, hyoyoung commented on recipes_source/torch_compile_user_defined_triton_kernel_tutorial.py
> +# 그러나 알아두어야 할 몇 가지 제한 사항이 있습니다:
한국어 마침표기에는 일반적으로 :를 쓰지 않으니 제외해도 좋을 것 같습니다

2024-10-14 13:15 UTC, hyoyoung commented
최종 코멘트 후 2주가 지났습니다. 일정 기간 답변이 없는 경우 자동으로 닫고 있습니다.
필요한 내용이 있으면 내일까지 수정 부탁드리겠습니다

2024-10-15 08:50 UTC, dlcodns commented
네, 빠르게 수정하도록 하겠습니다.

2024-10-15 10:56 UTC, dlcodns commented
수정을 완료했습니다! 피드백에 감사드립니다.

2024-10-15 11:02 UTC, hyoyoung approved these changes
good

2024-10-15 11:07 UTC, merged

2024-10-18 01:28 UTC, kookyungseon commented
## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호: #(911)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
recipes_source의 torch_compile_user_defined_triton_kernel_tutorial.py파일을 전체 번역하였습니다.