beginner_source/introyt/tensorboardyt_tutorial.py 번역
PyTorchKorea/tutorials-kr pull request #923
Opened 2024-09-06 14:04 UTC by Angela-Park-JE

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #871

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

TensorBoard 유튜브 튜토리얼 문서를 번역하였습니다. 
- 명확하게 의미가 필요한 두루뭉술한 단어(예시: 쓰기- ~use~, write)의 경우 원어표기를 함께 하였습니다. 
- 주로, '의미' 대신 원문 그대로의 '양'을 이어받는 줄바꿈을 사용하였습니다. 
- 중간에 **동의문**이 발견되었으나(_Visualizing Your Dataset with Embeddings_ 단원), 해당 부분은 PyTorch 공식 문서에서 수정이 이루어져야 하는 부분으로 보였습니다. 따라서 동의문 느낌은 최대한 덜어내고 원문 그대로 의미가 전달될 수 있도록 노력하였습니다.

2024-09-10 11:50 UTC, hadh93 reviewed
여러 군데에서 깊이 고민하신 흔적이 보이는 매끄러운 번역입니다. 고생 많으셨어요!
몇 가지 사소한 코멘트를 남기니, 참고 부탁드립니다 😄

2024-09-10 11:50 UTC, hadh93 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +for epoch in range(1):  # 데이터셋을 여러 번 반복
번역은 옳게 하셨는데, 코드의 상태를 보니 range(1) 때문에 1번 반복하는 코드네요!
필요 시 range() 안의 숫자를 수정해서 여러 번 반복하라는 힌트를 주는 주석 같은데, 그런 부분을 감안한 표현으로 바꿔보면 어떨까요?

2024-09-10 11:50 UTC, hadh93 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +#   documentation <https://www.tensorflow.org/tensorboard>`_\을 참고하세요.
세 줄 위에서 'PyTorch documentation'을 'PyTorch 문서'로 번역하셨네요!
'TensorBoard documentation'도 통일성 있게 번역되면 더욱 좋을 것 같습니다.

2024-09-14 09:54 UTC, oh5221 commented
고생하셨습니다! 전반적으로 깔끔하고 보기 좋은 것 같아요 :))

2024-09-22 02:38 UTC, jh941213 commented
고생하셨습니다. 제가 봤을땐 따로 고칠건 없어보이네요 수고하셨어요

2024-09-25 16:30 UTC, hyoyoung requested changes
긴 문서를 전반적으로 흠없이 잘 번역하였습니다. 수고 많이 하셨네요.
사소한 코멘트를 몇개 남기니 확인 후에 필요한 부분은 수정 부탁드립니다.

2024-09-25 16:30 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +한번 종속된 모듈을 설치하고 나서,
패키지 dependency라면 보통은 의존성이라고 쓰는게 널리 쓰이는거 같습니다.

한번 의존성이 있는 모듈을 설치하고 나서,

이정도로 바꿔보면 어떨까요?

2024-09-25 16:30 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +변형된 LeNet-5를 학습시킬 것입니다.
이 notebook에서는 변형된 LeNet-5를 Fashion-MNIST 데이터셋으로 학습시킬 것입니다.

요렇게 바꿔보면 어떨까요?

2024-09-25 16:30 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +Fashion-MNIST는 의류의 종류를 나타내는 10개의 클래스 레이블을 포함하는
사소하지만 류가 반복되고 있습니다
의복의 종류 정도로 해보면 어떨까요?

2024-09-25 16:31 UTC, hyoyoung commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 유리할 수 있죠. ``add_embedding()`` 메소드는
여기서 어투가 살짝 바뀐거 같습니다.
다른 부분은 ~입니다. ~습니다인데, 여기서는 ~요, ~죠 스타일이니
같은 방식으로 유리할 수 있습니다. 정도는 어떨까요?

2024-09-29 05:46 UTC, rumjie commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 데이터의 랜덤 서브셋과 대응하는 레이블을 선택
튜토리얼 흐름 상 데이터로부터 무작위로 샘플링하는 단계로 생각되는데, 서브셋이라는 음차 표기보다는 내용의 흐름 상 "샘플" 혹은 "부분집합"으로 의미가 더 잘 드러나도록 의역하는 것이 내용 이해에 더 도움될 것 같습니다!

2024-09-29 09:39 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 데이터의 랜덤 서브셋과 대응하는 레이블을 선택
저도 고민했던 부분이에요. 의견 주신 것 정말 감사합니다!! 
샘플은 원어에서도  sample일 것 같은 느낌이 강해서 추천해주신 "부분집합" 으로 변경하였습니다. 감사합니다 😁

2024-09-29 09:40 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +한번 종속된 모듈을 설치하고 나서,
의존이 먼저 떠오르긴 했으나 마땅한 표현이 생각나지 않아 고민했던 부분입니다! 의견 반영하여 수정하였습니다. 감사합니다!

2024-09-29 09:41 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +변형된 LeNet-5를 학습시킬 것입니다.
훨씬 정리된 표현같아요! 읽기 편한 문장으로 의견주셔서 감사합니다! 반영하여 수정하였습니다.

2024-09-29 09:43 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +Fashion-MNIST는 의류의 종류를 나타내는 10개의 클래스 레이블을 포함하는
의견 주셔서 너무 감사합니다. 아래에서도 의류라고 표현하기 때문에 의류로 통일하는게 좋을지, 의복으로 쓰면 아래에서도 의복의 종류라고 하는게 좋을텐데 동일하지 않게 해도 괜찮을지 고심 했었습니다. 피드백 사항 반영, 수정하였습니다!

2024-09-29 09:44 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +# 유리할 수 있죠. ``add_embedding()`` 메소드는
저도 걸렸던 부분입니다. '~ 수 있습니다'가 반복되는 것 같아서 썼긴 했지만 확실히 통일성을 지키는게 훨씬 좋아보이네요! 감사합니다. 피드백 사항 반영하여 수정하였습니다. 😄

2024-09-29 09:46 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +for epoch in range(1):  # 데이터셋을 여러 번 반복
정말 중요한 부분을 짚어주셨습니다! 감사합니다! 
"(필요 시 횟수를 조정합니다.)" 라고 추가적인 부분을 달아 수정하였습니다!

2024-09-29 09:53 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +#   documentation <https://www.tensorflow.org/tensorboard>`_\을 참고하세요.
저도 고민했던 부분을 말씀주셔서 정말 감사합니다! 마지막 줄이라 더 오래 붙잡고 고민했던 기억이 납니다🤣 <br/>
다만 이 부분은 실제 원어 문서에서 Pytorch documentation은 아니나, TensorBoard documentation은 링크의 이름으로 처리 되어있어서 따로 번역하지 않았는데요! 
<img width="638" alt="image" src="https://github.com/user-attachments/assets/f22e5236-a87a-47e6-82a0-1eab93c95628">
링크와 상관없이 바꾸어도 괜찮은 걸까요? 제 문서는 링크가 많지 않았다 보니 링크의 제목도 번역을 해두는게 맞다는 판단이 서지 않았던 것도 있습니다 😭 이 부분은 동훈님 의견을 한 번 더 들은 후에 변경하는게 좋을 것 같아서 아직 반영하지 않았습니다.🙏

2024-09-29 11:22 UTC, hadh93 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +#   documentation <https://www.tensorflow.org/tensorboard>`_\을 참고하세요.
남겨주신 답변을 들으니 어떤 부분에서 고민하셨는지 이해가 되네요!

제 개인적인 의견으로는, _링크에 문서의 제목이 정확히 그대로 사용된 경우_ 나 _번역된 문서명이 존재하는 경우_ 를 제외하면 번역해도 된다고 생각합니다.
즉 TensorBoard documentation 링크가 가리키는 문서가
- 제목이 'TensorBoard documentation'이 아니고,
- 누군가 다른 이름 (e.g. 텐서보드 도큐멘테이션, 텐서보드 문서) 등으로 번역해놓지 않았으므로 (->이 경우에는 이 이름을 따르는 게 맞다고 생각합니다),

이 경우에는 정은님이 번역하신 문서의 맥락에 맞게 번역하셔도 좋다고 (개인적으로) 생각합니다 :)

2024-09-29 11:34 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +#   documentation <https://www.tensorflow.org/tensorboard>`_\을 참고하세요.
우와... 역시 동훈님입니다.🙏 
"링크에 문서의 제목이 정확히 그대로 사용된 경우" 나 "번역된 문서명이 존재하는 경우"라고 말씀주시니 번역의 가이드라인을 하나 더 배운 기분이에요. _문서명인가 아닌가_, 라는 기준이 무척 좋은 것 같습니다. 
말씀에 매우 동감하는 부분이라 그렇게 번역해야겠네요! 재 피드백 주신 부분 반영해서 수정하였습니다. 정말 감사드려요 :D

2024-09-30 02:09 UTC, hadh93 commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +#   documentation <https://www.tensorflow.org/tensorboard>`_\을 참고하세요.
앗 과찬이십니다 😊 
지극히 개인적인 제 의견에 귀 기울여 주셔서 감사합니다!
(지나가는 어느 고수님께서 저의 사견을 부디 검증해주시길 바라며..)

수정해주신 부분 확인했습니다! 
문서 뒤의 조사를 -을 에서 -를로 바꿔주시면 더욱 좋을 것 같아요 👍

2024-09-30 11:42 UTC, Angela-Park-JE commented on beginner_source/introyt/tensorboardyt_tutorial.py
> +#   documentation <https://www.tensorflow.org/tensorboard>`_\을 참고하세요.
역시 예리하십니다😭 해당 부분 수정하여 commit 올렸습니다! 
덕분에 훨씬 완성도 있는 문서로 변모한 것 같습니다. 정말 감사합니다 ☺️🙏

2024-09-30 11:55 UTC, hadh93 approved these changes
반영해 주신 부분 확인했습니다!
LGTM입니다 ☺️

2024-10-06 11:48 UTC, hyoyoung approved these changes
good

2024-10-09 00:11 UTC, 9bow approved these changes

2024-10-14 13:08 UTC, merged