advanced_source/semi_structured_sparse.py 번역
PyTorchKorea/tutorials-kr pull request #927
Opened 2024-09-09 03:10 UTC by dlcodns

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [ x ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #925

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ x ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
기존에 없던 문서 번역 https://tutorials.pytorch.kr/advanced/semi_structured_sparse.html

2024-09-25 16:44 UTC, hyoyoung requested changes
긴문서를 보기 쉽게 잘 정리해주셨습니다.
몇가지 확인 사항을 남기니 보시고 필요한 부분은 수정 부탁드립니다.

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +**저자**: `Jesse Cai <https://github.com/jcaip>`_
번역자 정보도 아래 줄에 넣어주세요

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +# 이 튜토리얼은 반구조적 희소성 및 일반적인 희소성에 대한 초보자를 위해 설계되었습니다.
design은 여기서는 굳이 설계되었다고 하지 않아도 될거 같습니다.

이 튜토리얼은 초보자에게 반구조적 희소성 및 일반적인 희소성을 맞춤 설명합니다.

이정도로 의역해보면 어떨까요?

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +# 그 이유는 밀집 텐서(dense tensor)가 여전히 가지치기된(0인) 요소를 포함하고 있으며,
용어집에서 tensor는 일반적으로 번역하지 않습니다.

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +# 희소 레이아웃은 두 가지 이유로 특히 흥미롭습니다:
흥미로운 두 가지 이유가 있습니다.
정도로 하면 더 읽기 편할거 같습니다.

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +#   그들의 `백서 <https://arxiv.org/abs/2104.08378>`_
NVIDIA가 공개한 백서...

요정도로 바꿔보면 어떨까요?

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +# - 정확도 - 2:4 희소 가중치 세트를 찾아 모델의 정확도 저하를 최소화할 수 있는 방법은 무엇인가?
전반적으로 경어체를 썼으므로 여기서도, 무엇인가요?로 바꾸는게 좋을거 같습니다.

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +# 모델 로드
모델 불러오기 나 읽어들이기로 해도 좋을 거 같습니다.

2024-09-25 16:44 UTC, hyoyoung commented on advanced_source/semi_structured_sparse.py
> +# 모델을 가지치기하는 첫 번째 단계는 모델의 가중치를 마스킹하기 위한 파라미터화를 삽입하는 것입니다.
매개변수화라고 해도 괜찮지 않을까요?

2024-10-14 13:16 UTC, hyoyoung commented
최종 코멘트 후 2주가 지났습니다. 일정 기간 답변이 없는 경우 자동으로 닫고 있습니다.
필요한 내용이 있으면 내일까지 수정 부탁드리겠습니다

2024-10-15 08:50 UTC, dlcodns commented
네, 수정하도록 하겠습니다.

2024-10-15 10:56 UTC, dlcodns commented
수정을 완료했습니다! 피드백에 감사드립니다.

2024-10-15 11:03 UTC, hyoyoung approved these changes
good

2024-10-15 11:08 UTC, hyoyoung commented
최종 merge하기전에 살펴보니,
올려주신 분의 이름이 역자에 없는데 어떤 이유일까요?

2024-10-15 11:09 UTC, hyoyoung commented
아 방금 코멘트는 다른 PR에 달릴거였네요. 이 PR은 merge할테니 방금 전 코멘트는 신경 안쓰셔도 됩니다.

2024-10-15 11:09 UTC, merged