recipes_source/recipes/swap_tensors.py 번역
PyTorchKorea/tutorials-kr pull request #928
Opened 2024-09-09 04:38 UTC by dlcodns

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #926

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
기존에 없던 문서 번역 https://tutorials.pytorch.kr/recipes/recipes/swap_tensors.html

2024-09-26 14:42 UTC, hyoyoung requested changes
긴 문서 번역하느라 수고하셨습니다.
몇가지 번역체 어투가 보이고 수정 가능한 부분이 몇군데 있습니다.
확인해보시고 수정 부탁드립니다.

2024-10-14 13:16 UTC, hyoyoung commented
최종 코멘트 후 2주가 지났습니다. 일정 기간 답변이 없는 경우 자동으로 닫고 있습니다.
필요한 내용이 있으면 내일까지 수정 부탁드리겠습니다

2024-10-15 08:51 UTC, dlcodns commented
네, 수정하도록 하겠습니다.

2024-10-15 11:09 UTC, hyoyoung commented
최종 merge하기전에 살펴보니,
올려주신 분의 이름이 역자에 없는데 어떤 이유일까요?

2024-10-15 14:18 UTC, kookyungseon commented
pull request를 같이 올렸는데, 번역 자체는 제가 진행하여 역자에 제 이름만 넣었습니다.

2024-10-15 14:18 UTC, dlcodns commented
네, 저희는 학교에서 2인 1조로 오픈소스 컨트리뷰션 강의를 듣는 과정에서 이 활동을 했습니다. 2인 파트를 분배하다보니, @kookyungseon 이 친구는 issue를 작성하고 제가 풀리퀘를 작성하게 되었습니다!  그리고 1개는 같이 번역, 1개씩 따로 번역을 맡게되어 이 파일처럼 각각 1개씩은 역자가 홀로 되어 있습니다.

2024-10-15 14:19 UTC, dlcodns commented
혹시 이러면 문제가 되는건가요?

2024-10-17 13:16 UTC, hyoyoung commented
> 혹시 이러면 문제가 되는건가요?

1. 네 문제가 됩니다. 가장 주요한 문제는 제일 위에 '라이선스 동의'를 하신 분하고
PR 내용에 있는 분이 다르기 때문에 생기는 문제입니다. 이번 PR은 더이상 수정할 부분은 지금 없어보이니,
역자 내용안에 있는 분이 올려주시는게 좋을거 같습니다.
번거롭지만 해당 PR은 닫고 역자로 되어있는 분이 올려주시길 부탁드립니다.

2. https://github.com/PyTorchKorea/tutorials-kr/pull/918
이전에 완료된 PR이지만 kookyungseon님의 '라이선스 동의'부분이 없습니다.
@kookyungseon 님이 이 완료된 PR의 리플에 '라이선스 동의'을 복사해서 붙여주시면 좋겠습니다.
대표로 올리신 분이 동의하셨지만, 혹시 차후에 생길지 모르는 이슈를 사전에 방지하는 차원이라고 생각하시면 됩니다.

2024-10-18 01:34 UTC, kookyungseon commented
1. 넵 이 PR은 닫고 다시 올리도록 하겠습니다. 
2. https://github.com/PyTorchKorea/tutorials-kr/pull/918 해당 파일 PR에 라이선스 동의 복사해서 붙여놨습니다.

2024-10-18 02:13 UTC, closed without merging