beginner_source/hta_trace_diff_tutorial.rst 번역
PyTorchKorea/tutorials-kr pull request #941
Opened 2024-09-14 10:00 UTC by uddk6215

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(940)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
hta_trace_diff_tutorial.rst 파일을 전체 번역했습니다.

2024-09-22 06:50 UTC, jason9865 commented on beginner_source/hta_trace_diff_tutorial.rst
> +이러한 요구를 지원하기 위해 HTA는 트레이스 비교 기능을 제공합니다. 이 기능을 통해 사용자는 두 세트의 트레이스 파일을 입력할 수 있는데,
사소한 부분이긴 하지만 가독성 측면에서 아래와 같이 표현한다면 어떨까요?
- 이러한 요구를 지원하기 위해 -> 이를 위해

2024-09-22 06:51 UTC, jason9865 commented
> ## 라이선스 동의
> _변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._ _더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._ _동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._
> 
> * [x]  기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.
> 
> ## 관련 이슈 번호
> _이 Pull Request와 관련있는 이슈 번호를 적어주세요._ _이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_
> 
> * **이슈 번호**: #(940)
> 
> ## PR 종류
> _이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._
> 
> * [ ]  오탈자를 수정하거나 번역을 개선하는 기여
> * [x]  번역되지 않은 튜토리얼을 번역하는 기여
> * [ ]  공식 튜토리얼 내용을 반영하는 기여
> * [ ]  위 종류에 포함되지 않는 기여
> 
> ## PR 설명
> hta_trace_diff_tutorial.rst 파일을 전체 번역했습니다.
 
 전반적으로 훌륭하게 번역해주신 것 같습니다!

2024-09-26 14:46 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다.
몇가지 확인사항을 남기니 수정 부탁드립니다.

2024-09-26 14:46 UTC, hyoyoung commented on beginner_source/hta_trace_diff_tutorial.rst
>  **Author:** `Anupam Bhatnagar <https://github.com/anupambhatnagar>`_
author는 저자로 변환 해주시고
저자 정보 아래에 번역자 정보 추가 부탁드립니다.

2024-09-26 14:46 UTC, hyoyoung commented on beginner_source/hta_trace_diff_tutorial.rst
> +`TraceDiff <https://hta.readthedocs.io/en/latest/source/api/trace_diff_api.html>`_ 클래스는 다음과 같은 메서드를 가지고 있습니다.
용어집에서 method는 메소드로 권장하고 있습니다.

2024-09-29 09:36 UTC, uddk6215 commented on beginner_source/hta_trace_diff_tutorial.rst
> +이러한 요구를 지원하기 위해 HTA는 트레이스 비교 기능을 제공합니다. 이 기능을 통해 사용자는 두 세트의 트레이스 파일을 입력할 수 있는데,
훨씬 보기 좋네요. 감사합니다.

2024-09-29 09:36 UTC, uddk6215 commented on beginner_source/hta_trace_diff_tutorial.rst
> +`TraceDiff <https://hta.readthedocs.io/en/latest/source/api/trace_diff_api.html>`_ 클래스는 다음과 같은 메서드를 가지고 있습니다.
모두 반영했습니다!

2024-10-06 11:51 UTC, hyoyoung commented on beginner_source/hta_trace_diff_tutorial.rst
> +TraceDiff 클래스의 메서드:
위의 줄에서는 메소드이고 아래줄에서는 메서드입니다

2024-10-09 16:22 UTC, hyoyoung commented on beginner_source/hta_trace_diff_tutorial.rst
> +마지막 두 메서드는 compare_traces 메서드의 출력을 사용하여 CPU 연산자와 GPU 커널의
여기도 메서드가 남아있습니다 확인 부탁드릴게요

2024-10-14 06:39 UTC, uddk6215 commented on beginner_source/hta_trace_diff_tutorial.rst
> +마지막 두 메서드는 compare_traces 메서드의 출력을 사용하여 CPU 연산자와 GPU 커널의
반영했습니다!

2024-10-14 13:06 UTC, hyoyoung approved these changes
good

2024-10-14 22:29 UTC, 9bow approved these changes

2024-10-15 01:39 UTC, merged