beginner_source/nlp/README.txt 번역
PyTorchKorea/tutorials-kr pull request #952
Opened 2024-09-29 14:12 UTC by Choigapju

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #874

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
beginner_source/nlp/README.txt 번역, PyTorch, TensorFlow 등 영어 원문으로써 사용이 잦은 용어들에 대해서는 번역 미진행.

2024-10-20 08:37 UTC, jih0-kim reviewed
번역 과정 고생하셨습니다. 몇 가지 리뷰 드리니 참고하여 검토 요청드립니다.

2024-10-20 08:37 UTC, jih0-kim commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 PyTorch를 활용한 딥러닝 프로그래밍의 핵심 개념들을 단계별로 안내합니다. 여기서 다루는 많은 개념들(예를 들어, 계산 그래프 추상화와 자동 미분)은 PyTorch에만 국한된 것이 아니라 현존, 모든 딥러닝 도구에 공통적으로 적용되는 원리입니다.
현존, -> 현존하는 으로 수정 의견 드립니다.

2024-10-20 08:37 UTC, jih0-kim commented on beginner_source/nlp/README.txt
> +일반적으로 이런 강좌들은 순방향 신경망의 기본적인 역전파 알고리즘을 다루며, 신경망이 선형 변환과 비선형 활성화 함수의 연쇄 구성이라는 점을 강조합니다. 본 튜토리얼의 주된 목표는 이러한 선수 지식을 바탕으로 여러분이 실제로 딥러닝 코드를 작성하기 시작할 수 있도록 안내하는 것입니다.
용어집에 따라 순방향 신경망 -> 순전파 신경망 으로 번역 수정 요청 드립니다.

2024-10-20 08:37 UTC, jih0-kim commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 특히, 어떤 딥러닝 프레임워크(예: TensorFlow, Theano, Keras, DyNet)로 코드를 작성해 본 경험이 전혀 없는 사람들을 위한 자연어 처리(NLP)에 초점을 맞추고 있습니다. 이 튜토리얼은 품사 태깅, 언어 모델링 등 핵심 NLP 문제에 대한 실용적 지식을 전제로 합니다. 또한 입문 수준의 인공지능 강의(예: R
마찬가지로, 용어집에 따라 순방향 신경망 -> 순전파 신경망 으로 번역 수정 요청 드립니다.

2024-10-20 11:43 UTC, hyoyoung requested changes
1. 아래 원문은 지워주시고, 1~5번 사항도 같이 번역 부탁드립니다.
2. 역자 표시도 다른 문서처럼 추가 부탁드립니다.

2024-10-20 11:43 UTC, hyoyoung commented on beginner_source/nlp/README.txt
> +유의하실 점은 이 튜토리얼들이 데이터가 아닌 모델에 관한 것이라는 점입니다. 모든 모델에 대해, 작은 차원의 테스트 예제들이 몇 가지 제공되어 학습 과정에서 가중치가 어떻게 변화하는지 직접 확인할 수 있습니다. 만약 실제 데이터로 시도해 보고 싶다면, 이 노트북에서 제공하는 모델들을 그대로 가져와 여러분의 데이터에 적용할 수 있을 것입니다.
원문에는 모델을 강조표시가 되어있습니다 원문을 표시가 되도록 유지되면 좋겠습니다

2024-10-20 14:33 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +유의하실 점은 이 튜토리얼들이 데이터가 아닌 모델에 관한 것이라는 점입니다. 모든 모델에 대해, 작은 차원의 테스트 예제들이 몇 가지 제공되어 학습 과정에서 가중치가 어떻게 변화하는지 직접 확인할 수 있습니다. 만약 실제 데이터로 시도해 보고 싶다면, 이 노트북에서 제공하는 모델들을 그대로 가져와 여러분의 데이터에 적용할 수 있을 것입니다.
확인하였습니다-!

2024-10-21 05:08 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 특히, 어떤 딥러닝 프레임워크(예: TensorFlow, Theano, Keras, DyNet)로 코드를 작성해 본 경험이 전혀 없는 사람들을 위한 자연어 처리(NLP)에 초점을 맞추고 있습니다. 이 튜토리얼은 품사 태깅, 언어 모델링 등 핵심 NLP 문제에 대한 실용적 지식을 전제로 합니다. 또한 입문 수준의 인공지능 강의(예: R
PR 내역이 로컬에서 사라져 새로 PR 하였습니다.

2024-10-21 05:08 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +유의하실 점은 이 튜토리얼들이 데이터가 아닌 모델에 관한 것이라는 점입니다. 모든 모델에 대해, 작은 차원의 테스트 예제들이 몇 가지 제공되어 학습 과정에서 가중치가 어떻게 변화하는지 직접 확인할 수 있습니다. 만약 실제 데이터로 시도해 보고 싶다면, 이 노트북에서 제공하는 모델들을 그대로 가져와 여러분의 데이터에 적용할 수 있을 것입니다.
PR 내역이 로컬에서 사라져 새로 PR 하였습니다.

2024-10-21 05:08 UTC, closed without merging