intermediate_source/FSDP_tutorial.rst 번역
PyTorchKorea/tutorials-kr pull request #953
Opened 2024-10-02 13:34 UTC by uddk6215

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(951)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
FSDP 튜토리얼 문서를 일부 번역하였습니다. 곧 전체 번역 완료할 예정입니다.

2024-10-23 15:13 UTC, hyoyoung requested changes
긴 문서 번역하느라 수고하셨습니다.
몇가지 어색한 부분이 있는데 확인 후 수정 부탁드립니다.

2024-10-23 15:13 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +대규모 AI 모델을 학습하는 것은 많은 컴퓨팅 파워와 리소스를 필요로 하는 어려운 작업입니다.
리소스는 자원으로 순화해도 좋을 듯합니다

2024-10-23 15:13 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +FSDP는 모델 파라미터, 옵티마이저 상태, 변화도를 DDP rank들에 걸쳐 샤딩하는 데이터 병렬 처리 방식입니다.
parameter는 용어집에서 매개변수로 쓰도록 권고하고 있습니다.

2024-10-23 15:13 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +다만 이는 통신량 증가라는 비용을 수반합니다. 이 때 발생하는 오버헤드는 통신과 계산을 중첩하는 등의 내부 최적화를 통해 줄어듭니다.
이 때 발생하는 통신 오버헤드라고 해주는데 더 명확할거 같습니다.

2024-10-23 15:13 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +* 모델 파라미터들을 샤딩하고 각 랭크는 자신의 샤드만 유지합니다.
parameter는 용어집 참조

2024-10-23 15:13 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +* 파라미터를 폐기합니다.
폐기보다는 버린다고 하는게 더 알기 쉬울거 같습니다.

2024-11-02 02:53 UTC, uddk6215 commented on intermediate_source/FSDP_tutorial.rst
> +* 파라미터를 폐기합니다.
모두 반영완료하였습니다. 감사합니다!

2024-11-10 13:09 UTC, hyoyoung requested changes
몇가지 확인 사항을 부탁드립니다

2024-11-10 13:09 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +2.4 모델을 FSDP로 래핑하는 분산 학습 함수 정의
여기서 래핑은 감싸다로 순화 가능할거 같습니다

2024-11-10 13:09 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +FSDP로 모델을 래핑하면, 모델은 다음과 같이 보일 것입니다. 모델이 하나의 FSDP 유닛으로 래핑된 것을 볼 수 있습니다.
여기 랩핑도 마찬가지로 순화가능할거 같습니다

2024-11-10 13:09 UTC, hyoyoung commented on intermediate_source/FSDP_tutorial.rst
> +이 기능을 사용하면 호스트와 디바이스 간 텐서의 빈번한 복사로 인해 학습 속도가 상당히 느려질 수 있지만,
텐서는 일반적으로 tensor로 두고, 번역하지 않습니다

2024-11-17 07:56 UTC, uddk6215 commented on intermediate_source/FSDP_tutorial.rst
> +이 기능을 사용하면 호스트와 디바이스 간 텐서의 빈번한 복사로 인해 학습 속도가 상당히 느려질 수 있지만,
수정완료하였습니다.

2024-11-25 14:06 UTC, hyoyoung approved these changes
good

2024-11-30 14:54 UTC, merged