beginner_source/nlp/README.txt 번역
PyTorchKorea/tutorials-kr pull request #956
Opened 2024-10-21 05:07 UTC by Choigapju

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #874 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
이전 PR이 로컬 환경에서 날아가, 코멘트 해주신 내용을 포함하여 다시 번역해 PR 했습니다.
지난 PR 내용 : beginner_source/nlp/README.txt 번역, PyTorch, TensorFlow 등 영어 원문으로써 사용이 잦은 용어들에 대해서는 번역 미진행.

2024-10-23 15:00 UTC, hyoyoung commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 PyTorch를 활용한 딥러닝 프로그래밍의 핵심 개념들을 단계별로 안내합니다. 여기서 다루는 많은 개념들(예를 들어, 계산 그래프 추상화와 자동 미분)은 PyTorch에만 국한된 것이 아니라 현존하는 모든 딥러닝 도구에 공통적으로 적용되는 원리입니다.
반드시 그럴 필요는 없지만 글의 줄 바꿈을 원문과 비슷하게 유지하는 것을 권고 드립니다.

2024-10-23 15:01 UTC, hyoyoung commented on beginner_source/nlp/README.txt
> +유의하실 점은 이 튜토리얼들이 데이터가 아닌 모델에 관한 것이라는 점입니다. 모든 *모델*에 대해, 작은 차원의 테스트 예제들이 몇 가지 제공되어 학습 과정에서 가중치가 어떻게 변화하는지 직접 확인할 수 있습니다. 만약 실제 데이터로 시도해 보고 싶다면, 이 노트북에서 제공하는 모델들을 그대로 가져와 여러분의 데이터에 적용할 수 있을 것입니다.
원문의 '모델'의 강조 * 가 첫번째 문장인데, 여기서는 두번째 문장이 되었습니다.

2024-10-25 01:03 UTC, Choigapju commented on beginner_source/nlp/README.txt
>  ----------------------------------
반영하였습니다.

2024-10-25 01:03 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 PyTorch를 활용한 딥러닝 프로그래밍의 핵심 개념들을 단계별로 안내합니다. 여기서 다루는 많은 개념들(예를 들어, 계산 그래프 추상화와 자동 미분)은 PyTorch에만 국한된 것이 아니라 현존하는 모든 딥러닝 도구에 공통적으로 적용되는 원리입니다.
반영하였습니다.

2024-10-25 01:03 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +유의하실 점은 이 튜토리얼들이 데이터가 아닌 모델에 관한 것이라는 점입니다. 모든 *모델*에 대해, 작은 차원의 테스트 예제들이 몇 가지 제공되어 학습 과정에서 가중치가 어떻게 변화하는지 직접 확인할 수 있습니다. 만약 실제 데이터로 시도해 보고 싶다면, 이 노트북에서 제공하는 모델들을 그대로 가져와 여러분의 데이터에 적용할 수 있을 것입니다.
반영하였습니다.

2024-10-27 11:50 UTC, jih0-kim commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 특히, 어떤 딥러닝 프레임워크(예: TensorFlow, Theano, Keras, DyNet)로 코드를 작성해 본 경험이 전혀 없는 사람들을 위한 자연어 처리(NLP)에 초점을 맞추고 있습니다. 이 튜토리얼은 품사 태깅, 언어 모델링 등 핵심 NLP 문제에 대한 실용적 지식을 전제로 합니다. 또한 입문 수준의 인공지능 강의(예: R
원문 기준 한 문단에 대한 번역이 두 번 들어가 있습니다. 중복된 내용 없도록 수정 요청 드립니다.

2024-10-28 13:39 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +이 튜토리얼 시리즈는 특히, 어떤 딥러닝 프레임워크(예: TensorFlow, Theano, Keras, DyNet)로 코드를 작성해 본 경험이 전혀 없는 사람들을 위한 자연어 처리(NLP)에 초점을 맞추고 있습니다. 이 튜토리얼은 품사 태깅, 언어 모델링 등 핵심 NLP 문제에 대한 실용적 지식을 전제로 합니다. 또한 입문 수준의 인공지능 강의(예: R
반영하였습니다

2024-11-10 13:03 UTC, hyoyoung approved these changes
good

2024-11-14 01:04 UTC, 9bow requested changes
링크된 문서의 제목을 반영해주시기 바랍니다.

2024-11-14 01:04 UTC, 9bow commented on beginner_source/nlp/README.txt
> +	https://tutorials.pytorch.kr/beginner/nlp/advanced_tutorial.html
이 `README.txt`는 색인(index)을 위한 용도도 있어, 각 문서의 제목을 반영해주셔야 합니다.

예를 들어, 다음 문서의 제목은 "PyTorch 소개"입니다.

> 1. pytorch_tutorial.py
> 	파이토치 입문
> 	https://tutorials.pytorch.kr/beginner/nlp/pytorch_tutorial.html

2024-11-14 01:45 UTC, Choigapju commented on beginner_source/nlp/README.txt
> +	https://tutorials.pytorch.kr/beginner/nlp/advanced_tutorial.html
반영했습니다.

2024-11-14 16:50 UTC, 9bow approved these changes
감사합니다~

2024-11-14 16:52 UTC, merged